package com.skyhand.redbookhelper;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class id {
        public static final int mBtnReboot = 0x7f010000;
        public static final int mBtnWifi = 0x7f010001;
        public static final int mLayoutHideIcon = 0x7f010002;
        public static final int mRbHide = 0x7f010003;
        public static final int mTestTip = 0x7f010004;
        public static final int mTvAdapter = 0x7f010005;
        public static final int mTvAdapterList = 0x7f010006;
        public static final int mTvQQOne = 0x7f010007;
        public static final int mTvQQTwo = 0x7f010008;
        public static final int mTvTip = 0x7f010009;
        public static final int mTvUsed = 0x7f01000a;
        public static final int mTvUsedTitle = 0x7f01000b;
        public static final int mTvVersion = 0x7f01000c;
        public static final int mTvWechat = 0x7f01000d;
        public static final int mTvWechatTitle = 0x7f01000e;
    }

    public static final class layout {
        public static final int main_activity = 0x7f020000;
    }

    public static final class mipmap {
        public static final int ic_launcher_background = 0x7f030000;
        public static final int ic_launcher_foreground = 0x7f030001;
        public static final int ic_launcher_round = 0x7f030002;
    }

    public static final class string {
        public static final int app_name = 0x7f040000;
        public static final int icon_hide_tip = 0x7f040001;
        public static final int mp = 0x7f040002;
        public static final int used = 0x7f040003;
    }
}
