// 自动恢复的 Objective-C 接口骨架
#import <Foundation/Foundation.h>

@interface CheckFriendsSettingController : NSObject
@end

@interface CheckHelper : NSObject
@end

@interface CheckTipsView : NSObject
@end

@interface ClearFriendsViewController : NSObject
@end

@interface GroupTool : NSObject
@end

@interface KR : NSObject
@end

@interface LMFileBrowserViewController : NSObject
@end

@interface LMFileModel : NSObject
@end

@interface LMUIButton : NSObject
@end

@interface LMUtils : NSObject
@end

@interface MGAudioUtils : NSObject
@end

@interface MGLog : NSObject
@end

@interface MGSessionBoxViewController : NSObject
@end

@interface MGTipsRecordViewController : NSObject
@end

@interface MMActionSheetDatePickerDelegate : NSObject
@end

@interface MMPickLocationViewControllerDelegate : NSObject
@end

@interface MYActionsViewController : NSObject
@end

@interface MYChatGPT : NSObject
@end

@interface MYChatGPTViewController : NSObject
@end

@interface MYEditViewController : NSObject
@end

@interface MYFontViewController : NSObject
@end

@interface MYMessageTask : NSObject
@end

@interface MYMotionManager : NSObject
@end

@interface MYMsgListViewController : NSObject
@end

@interface MYMultiSelectViewController : NSObject
@end

@interface MYPromptsViewController : NSObject
@end

@interface MYReplyConfig : NSObject
@end

@interface MYRoomTool : NSObject
@end

@interface MYThemesViewController : NSObject
@end

@interface MiYouAddTaskViewController : NSObject
@end

@interface MiYouConfig : NSObject
@end

@interface MiYouDanMuView : NSObject
@end

@interface MiYouFloatingView : NSObject
@end

@interface MiYouHudView : NSObject
@end

@interface MiYouIconsViewController : NSObject
@end

@interface MiYouKeyDeleteViewController : NSObject
@end

@interface MiYouKeywordListViewController : NSObject
@end

@interface MiYouKeywordTipsController : NSObject
@end

@interface MiYouMassSendWriteViewController : NSObject
@end

@interface MiYouMessageAction : NSObject
@end

@interface MiYouMessageToolBar : NSObject
@end

@interface MiYouNotificationViewController : NSObject
@end

@interface MiYouPriUtil : NSObject
@end

@interface MiYouRepayMsgViewController : NSObject
@end

@interface MiYouSettingViewController : NSObject
@end

@interface MiYouSlideView : NSObject
@end

@interface MiYouTableViewCell : NSObject
@end

@interface MiYouTaskModel : NSObject
@end

@interface MiYouTaskViewController : NSObject
@end

@interface MiYouToastView : NSObject
@end

@interface MiYouToolActionsViewController : NSObject
@end

@interface MiYouViewController : NSObject
@end

@interface MultiSelectContactsViewControllerDelegate : NSObject
@end

@interface NSObject : NSObject
@end

@interface NSSignature : NSObject
@end

@interface SpotlightUtil : NSObject
@end

@interface UICollectionViewDataSource : NSObject
@end

@interface UICollectionViewDelegate : NSObject
@end

@interface UIDocumentPickerDelegate : NSObject
@end

@interface UIGestureRecognizerDelegate : NSObject
@end

@interface UIImagePickerControllerDelegate : NSObject
@end

@interface UINavigationControllerDelegate : NSObject
@end

@interface UIPickerViewDataSource : NSObject
@end

@interface UIPickerViewDelegate : NSObject
@end

@interface UIScrollViewDelegate : NSObject
@end

@interface UITableViewDataSource : NSObject
@end

@interface UITableViewDelegate : NSObject
@end

@interface UITextViewDelegate : NSObject
@end

@interface WCActionSheetDelegate : NSObject
@end

@interface WCThemeMgr : NSObject
@end

// 未可靠归属到具体类的 selector：
// .cxx_destruct
// AVAudioSessionInterruptionNotification:
// AddAppMsg:MsgWrap:DataPath:Scene:
// AddLocalMsg:MsgWrap:
// AddLocalMsg:MsgWrap:fixTime:NewMsgArriveNotify:
// AddMsg:MsgWrap:
// AddVideoMsg:ToUsr:VideoInfo:
// AsyncOnAddMsg:MsgWrap:
// AutoReplyMessage:MsgWrap:
// BatchAddMsg:ShowPush:
// BrandList
// BuildCacheDataFromContacts
// BuildCacheDataFromFile
// CGColor
// CGPath
// ChangeNotifyStatus:withStatus:sync:
// ChangeSessionUnReadCount:to:
// ChatGPTReply:
// ChatList
// ClearPath:
// ConvertFavItem2FTSFavSearchItem:
// ConvertMsgToTextIfCannotSend:
// CopyFile:To:
// CreatePath:
// DecControl
// DelAllMsgs:
// DelMsg:MsgList:
// DelMsg:MsgList:DelAll:
// DeleteAllSession
// DeleteGroupMember:withMemberList:scene:
// DeleteSessionAtIndex:
// DeleteSessionOfUser:
// DeleteSessionOfUsernames:
// FileExist:
// ForwardFavItem:ToUser:delegate:
// ForwardFavItemList:delegate:
// ForwardMsg:ToContact:
// ForwardMsg:ToContact:Scene:
// ForwardMsg:ToContact:Scene:forwardType:editImageAttr:
// ForwardVoiceMsg:ToContact:
// FriendList
// GenSendMsgTime
// GetActiveUserUnreadCount
// GetChatName
// GetContact
// GetContactLabelItemsFromFile
// GetCurrentLogicController
// GetDataPath
// GetDisplayContent
// GetDocPath
// GetFileName
// GetFilePath
// GetFileSize:
// GetGroupAdmin:
// GetLastMsgFromUsr:
// GetLastMsgToUsr:
// GetMsg:LocalID:
// GetMsg:n64SvrID:
// GetPathOfCacheLocalUsrDir
// GetPathOfMesAudio:LocalID:DocPath:
// GetSessionAtIndex:
// GetSessionByUserName:
// GetSessionCount
// GetSessionInfoList
// GetStrangerAttribute:AttributeName:
// GetThumbPath
// GetTmpPath
// GetTotalUnreadCount
// GetTotalUnreadCountForAppIcon
// GetTransferPrepayRequest:
// GetUserNamesOnSessionList
// HandleHelloMsg:SpcialSession:NotAddDBSession:GetChangeDisplay:
// HasInstallJailbreakPlugin:
// HasInstallJailbreakPluginInvalidIAPPurchase
// InviteGroupMember:withMemberList:
// IsAtMe
// IsJailBreak
// IsShowUserName
// IsTextFold
// JSONObjectWithData:options:error:
// JailBroken
// KeyReplyMessage:
// KeywordDeleteMember:MsgWrap:
// KeywordReplyMessage
// KeywordTips:MsgWrap:
// LoadRequest:
// MiYouFloatingViewNewMsg:
// MiYouJiaYi:
// OnGetNewXmlMsg:Type:MsgWrap:
// OnImageDoubleClick:
// OnWCPayTransferMoneyStatusViewControllerConfirmTransfer
// PopBack
// PostInsertParsedXmlSysMsg:ChatName:
// PresentModalViewController:animated:
// PresentMultiSelectLogicControllerByContact:navigationController:animated:onComplete:
// PushController:
// PushOtherBaseMsgControllerByContact:navigationController:animated:
// PushSearchLogicControllerByContact:navigationController:ForMessageWrap:animated:fromeScene:
// PushViewController:
// PushViewController:animated:
// QuickReplyMessage:
// QuitGroup
// QuitGroup:withUsrName:
// QuitGroup:withUsrName:deleteAllMsg:
// Reject:withRoomId:andKey:
// RemoveFile:
// RenameFile:To:
// ReplyChatRoomList
// ReplyMessage
// ReplyOnlineTime
// ReportLeftSlideSessionDelete:isConfirmed:
// ReportLeftSlideSessionHide:isConfirmed:hasGuideView:
// ResendVoiceMsg:MsgWrap:
// RoomList
// SearchBarBecomeUnActive
// SelectType
// SetIdleTimeDisable:
// SettingOpenIM:
// StartDownloadAppAttach:MsgWrap:
// StartDownloadImage:HD:AutoDownload:
// StartDownloadVideo:DownloadMode:
// StartDownloadVideo:MsgWrap:Priority:DownloadMode:
// StartDownloadVideo:MsgWrap:Priority:Silent:
// StartDownloadWithMediaWrap:
// StartPredownloadImage:HD:useQuota:
// StartPreloadVideoWithMediaWraps:
// StartSpeakText:
// StartUploadTimelineMediaOfSight:
// StopTalk
// SyncFromUI
// SyncFulFillSession:
// T#,R
// T@"<MiYouMessageToolBarDelagate>",&,N,V_delegate
// T@"AVAudioPlayer",&,N,V_blankPlayer
// T@"CAAnimationGroup",&,N,V_animationGroup
// T@"CAShapeLayer",&,N,V_circleShape
// T@"CContactMgr",&,N,V_conontact
// T@"CContactMgr",&,N,V_contactMgr
// T@"CMMotionManager",&,N,V_motionManager
// T@"ContactSelectView",&,N,V_selectView
// T@"MMLoadingView",&,N,V_loadingView
// T@"MMPickLocationViewController",&,N,V_locationVC
// T@"MMTableView",&,N,V_tableView
// T@"MMTextView",&,N,V_textView
// T@"MMUINavigationBar",&,N,V_fakeNaviView
// T@"MiYouTaskModel",&,N,V_model
// T@"NSArray",&,N,V_dataArr
// T@"NSDate",&,N,V_modificationDate
// T@"NSDictionary",&,N,V_assetcs
// T@"NSDictionary",C,N,V_currentCheckResult
// T@"NSMutableArray",&,N,V_BrandList
// T@"NSMutableArray",&,N,V_ChatList
// T@"NSMutableArray",&,N,V_FriendList
// T@"NSMutableArray",&,N,V_RoomList
// T@"NSMutableArray",&,N,V_actions
// T@"NSMutableArray",&,N,V_allBrandList
// T@"NSMutableArray",&,N,V_chatGPTNoAtRoomList
// T@"NSMutableArray",&,N,V_chatGPTUserList
// T@"NSMutableArray",&,N,V_customFont
// T@"NSMutableArray",&,N,V_dataArr
// T@"NSMutableArray",&,N,V_dataSource
// T@"NSMutableArray",&,N,V_dayComponents
// T@"NSMutableArray",&,N,V_fileList
// T@"NSMutableArray",&,N,V_filterFriendList
// T@"NSMutableArray",&,N,V_filterRoomList
// T@"NSMutableArray",&,N,V_filterSessionList
// T@"NSMutableArray",&,N,V_hourComponents
// T@"NSMutableArray",&,N,V_mAtMeMessageList
// T@"NSMutableArray",&,N,V_mAutoDownloadRoomList
// T@"NSMutableArray",&,N,V_mDonotdisturbList
// T@"NSMutableArray",&,N,V_mGroupUndoneList
// T@"NSMutableArray",&,N,V_mKeyDeleRoomList
// T@"NSMutableArray",&,N,V_mKeywordTipsList
// T@"NSMutableArray",&,N,V_mKeywordTipsRecordList
// T@"NSMutableArray",&,N,V_mPatMessageList
// T@"NSMutableArray",&,N,V_mPreviewList
// T@"NSMutableArray",&,N,V_mReplyChatRoomList
// T@"NSMutableArray",&,N,V_mSensitiveArr
// T@"NSMutableArray",&,N,V_mWelcomeGroupList
// T@"NSMutableArray",&,N,V_messageList
// T@"NSMutableArray",&,N,V_minuteComponents
// T@"NSMutableArray",&,N,V_prompts
// T@"NSMutableArray",&,N,V_rooms
// T@"NSMutableArray",&,N,V_selectedSource
// T@"NSMutableArray",&,N,V_sessionDataList
// T@"NSMutableArray",&,N,V_sessionList
// T@"NSMutableArray",&,N,V_systemFont
// T@"NSMutableArray",&,N,V_timeLineHiddenUsers
// T@"NSMutableArray",&,N,V_titleArr
// T@"NSMutableArray",&,N,V_toolActions
// T@"NSMutableArray",&,N,V_users
// T@"NSMutableDictionary",&,N,V_chatContents
// T@"NSMutableDictionary",&,N,V_contents
// T@"NSMutableDictionary",&,N,V_customFontDic
// T@"NSMutableDictionary",&,N,V_mHideFriendList
// T@"NSMutableDictionary",&,N,V_mHideRoomList
// T@"NSMutableDictionary",&,N,V_mKeywordReplyMessage
// T@"NSMutableDictionary",&,N,V_mRegisterFonts
// T@"NSObject<OS_dispatch_semaphore>",&,N,V_checkFriendsSem
// T@"NSObject<OS_dispatch_source>",&,N,V_timer
// T@"NSString",&,N,V_chatModel
// T@"NSString",&,N,V_content
// T@"NSString",&,N,V_customOrigin
// T@"NSString",&,N,V_customParserURL
// T@"NSString",&,N,V_delay
// T@"NSString",&,N,V_friendGroupName
// T@"NSString",&,N,V_gameCustomURL
// T@"NSString",&,N,V_hungUpMessage
// T@"NSString",&,N,V_icon
// T@"NSString",&,N,V_keyword
// T@"NSString",&,N,V_mAutoGetPaySendMsg
// T@"NSString",&,N,V_mAutoReplyMessage
// T@"NSString",&,N,V_mAutoReplyOnlineTime
// T@"NSString",&,N,V_mAutoVerifyContent
// T@"NSString",&,N,V_mAutoVerifyKeyword
// T@"NSString",&,N,V_mChatGPTAPIKey
// T@"NSString",&,N,V_mCustomFontName
// T@"NSString",&,N,V_mDonotdisturbMsg
// T@"NSString",&,N,V_mDonotdisturbWorkingTime
// T@"NSString",&,N,V_mFakeLocationName
// T@"NSString",&,N,V_mFakeNoticeBody
// T@"NSString",&,N,V_mFakeNoticeTitle
// T@"NSString",&,N,V_mHidePassword
// T@"NSString",&,N,V_mHungUpAutoSendMsgText
// T@"NSString",&,N,V_mMsgDateColor
// T@"NSString",&,N,V_mMsgDateFormat
// T@"NSString",&,N,V_mRegisterFontName
// T@"NSString",&,N,V_mWelcomeGroupContent
// T@"NSString",&,N,V_messagePrefix
// T@"NSString",&,N,V_msgs
// T@"NSString",&,N,V_name
// T@"NSString",&,N,V_next
// T@"NSString",&,N,V_openaiProxy
// T@"NSString",&,N,V_path
// T@"NSString",&,N,V_systemMessage
// T@"NSString",&,N,V_text
// T@"NSString",&,N,V_themeName
// T@"NSString",&,N,V_time
// T@"NSString",&,N,V_title
// T@"NSString",&,N,V_turboModel
// T@"NSString",&,N,V_user
// T@"NSString",?,R,C
// T@"NSString",C,N,V_brandName
// T@"NSString",C,N,V_roomName
// T@"NSString",N,V_keywordContent
// T@"NSString",N,V_mStepPrvValue
// T@"NSString",R,C
// T@"NSTimer",&,N,V_bgTaskTimer
// T@"NSUserDefaults",&,N,V_userDefaults
// T@"SilkAudioPlayer",&,N,V_silkPlay
// T@"UIBarButtonItem",&,N,V_actionItem
// T@"UIBarButtonItem",&,N,V_editItem
// T@"UIButton",&,N,V_mainButton
// T@"UIButton",&,N,V_nextBtn
// T@"UICollectionView",&,N,V_collectionView
// T@"UIColor",&,N,V_animationColor
// T@"UIImageView",&,N,V_avatarImage
// T@"UIImageView",&,N,V_headImg
// T@"UIImageView",&,N,V_iconView
// T@"UIImageView",&,N,V_imageView
// T@"UILabel",&,N,V_messageLabel
// T@"UILabel",&,N,V_nameLabel
// T@"UILabel",&,N,V_textLabel
// T@"UILabel",&,N,V_titleLabel
// T@"UILocalNotification",&,N,V_localNotification
// T@"UIPanGestureRecognizer",&,N,V_pan
// T@"UIPercentDrivenInteractiveTransition",&,N,V_interactiveTransition
// T@"UIPickerView",&,N,V_pickview
// T@"UIScrollView",&,N,V_scrollview
// T@"UITableView",&,N,V_tabelView
// T@"UITableView",&,N,V_tableView
// T@"UITableView",&,N,V_tableview
// T@"UITapGestureRecognizer",&,N,V_tap
// T@"UIView",&,N,V_danmuView
// T@"UIView",&,N,V_fakeNaviView
// T@"UIView",&,N,V_hudView
// T@"UIView",&,N,V_mainView
// T@"UIView",&,N,V_nextView
// T@"WCTableViewManager",&,N,V_tableViewManager
// T@?,C,D,N
// T@?,C,N,V_changeAction
// T@?,C,N,V_clickBtnBlock
// T@?,C,N,V_clickViewBlock
// T@?,C,N,V_onActionBlock
// T@?,C,N,V_onDoneBlock
// T@?,C,N,V_onIconChangeAction
// T@?,C,N,V_onSendMessageBlock
// T@?,C,N,V_selectRowBlock
// TB,N,V_checkFriendsEnd
// TB,N,V_customQRCode
// TB,N,V_enabled
// TB,N,V_firstStart
// TB,N,V_hiddenToolBarTitle
// TB,N,V_hungUpEnabled
// TB,N,V_inputHiddenToolBar
// TB,N,V_isAddChatBox
// TB,N,V_isBrandSessionHolderTop
// TB,N,V_isBrandShowRedDot
// TB,N,V_isBrandTop
// TB,N,V_isChatBoxTop
// TB,N,V_isCreate
// TB,N,V_isEditModel
// TB,N,V_isHelperTop
// TB,N,V_isImageCountEnabled
// TB,N,V_isInRoomList
// TB,N,V_isInsertEdit
// TB,N,V_isJumpAd
// TB,N,V_isManagerChatBox
// TB,N,V_isOpenBrandEnable
// TB,N,V_isOpenBrandHelper
// TB,N,V_isOpenBrandNewEnable
// TB,N,V_isOpenFriendEnable
// TB,N,V_isOpenIM
// TB,N,V_isOpenInRoom
// TB,N,V_isOpenRoomEnable
// TB,N,V_isOpenRoomHelper
// TB,N,V_isPatTipsEnabled
// TB,N,V_isSelectesAll
// TB,N,V_isToOriginalMsg
// TB,N,V_isWeAppJumpEnabled
// TB,N,V_keepSendMsg
// TB,N,V_keywordReply
// TB,N,V_mDanMuPreview
// TB,N,V_mDelAllMessage
// TB,N,V_mFastJumpVideo
// TB,N,V_mFavMessagePreview
// TB,N,V_mIsAccountSwitch
// TB,N,V_mIsAddDonotdisturbMenu
// TB,N,V_mIsAllGroupUndeno
// TB,N,V_mIsAllUserEnabled
// TB,N,V_mIsAllowedOnlyRoomMessage
// TB,N,V_mIsAtAllUser
// TB,N,V_mIsAtAllUserMessage
// TB,N,V_mIsAtMeMessage
// TB,N,V_mIsAutoConfirmLogin
// TB,N,V_mIsAutoDownloadFiles
// TB,N,V_mIsAutoDownloadImage
// TB,N,V_mIsAutoDownloadVideo
// TB,N,V_mIsAutoGetPay
// TB,N,V_mIsAutoGetPayTips
// TB,N,V_mIsAutoHungUp
// TB,N,V_mIsAutoLock
// TB,N,V_mIsAutoNotifyOpen
// TB,N,V_mIsAutoReplyMessage
// TB,N,V_mIsAutoReplyOnlineTime
// TB,N,V_mIsAutoVerifyFriend
// TB,N,V_mIsBackEdgeGesture
// TB,N,V_mIsBakgrunnur
// TB,N,V_mIsBakgrunnurTips
// TB,N,V_mIsCallkit
// TB,N,V_mIsChangeVideoTime
// TB,N,V_mIsChatGPTEnabled
// TB,N,V_mIsChatGPTTurboEnabled
// TB,N,V_mIsChatRoomAdmin
// TB,N,V_mIsChatRoomOwner
// TB,N,V_mIsChatVoiceToText
// TB,N,V_mIsCustomFont
// TB,N,V_mIsDelayDelMember
// TB,N,V_mIsDonotdisturbState
// TB,N,V_mIsDoubleTapEnbale
// TB,N,V_mIsFakeLocation
// TB,N,V_mIsFakeNotice
// TB,N,V_mIsFakeStep
// TB,N,V_mIsFastDelGroupMember
// TB,N,V_mIsFastDeleteFriend
// TB,N,V_mIsFirst
// TB,N,V_mIsForwardVoice
// TB,N,V_mIsHiddenHongBao
// TB,N,V_mIsHiddenImage
// TB,N,V_mIsHiddenLocation
// TB,N,V_mIsHiddenMessageTime
// TB,N,V_mIsHiddenShareGroup
// TB,N,V_mIsHiddenTransferMoney
// TB,N,V_mIsHiddenVideo
// TB,N,V_mIsHiddenVoiceInput
// TB,N,V_mIsHideAllFav
// TB,N,V_mIsHideFriend
// TB,N,V_mIsHideMode
// TB,N,V_mIsHideSetting
// TB,N,V_mIsKeepDelMessage
// TB,N,V_mIsKeyDelGroupMember
// TB,N,V_mIsKeywordAlertTips
// TB,N,V_mIsKeywordReplyMessage
// TB,N,V_mIsKeywordReplySelfMessage
// TB,N,V_mIsKeywordTips
// TB,N,V_mIsLargeVideoFile
// TB,N,V_mIsLineBottomTool
// TB,N,V_mIsLinkToSafari
// TB,N,V_mIsMHungUpAutoSendMsg
// TB,N,V_mIsMP3SendToFilehelper
// TB,N,V_mIsMessageTime
// TB,N,V_mIsMotionHide
// TB,N,V_mIsMsgGestureEnbale
// TB,N,V_mIsMsgGestureRightEnbale
// TB,N,V_mIsMultiplechoiceChat
// TB,N,V_mIsNeedAtMeEnabled
// TB,N,V_mIsNoRevokeContent
// TB,N,V_mIsOpenMiYou
// TB,N,V_mIsOpenNotice
// TB,N,V_mIsOriginalImage
// TB,N,V_mIsPatMessage
// TB,N,V_mIsPlayPayMessage
// TB,N,V_mIsQuickNewLine
// TB,N,V_mIsQuoteAtUser
// TB,N,V_mIsRecentForward
// TB,N,V_mIsRedTips
// TB,N,V_mIsReferModeEnabled
// TB,N,V_mIsReplyChatRoomMessage
// TB,N,V_mIsReset
// TB,N,V_mIsRevokeMsg
// TB,N,V_mIsRoomLiveEntry
// TB,N,V_mIsRoomVoiceToText
// TB,N,V_mIsSanCodeInCamera
// TB,N,V_mIsSelectedCustomFont
// TB,N,V_mIsSendToGroupHelper
// TB,N,V_mIsSessionGesture
// TB,N,V_mIsShockNotice
// TB,N,V_mIsShowNewMessage
// TB,N,V_mIsShowUserName
// TB,N,V_mIsShowVoiceTag
// TB,N,V_mIsSpotlightSearch
// TB,N,V_mIsTextFold
// TB,N,V_mIsTextJaiYi
// TB,N,V_mIsTheContextEnabled
// TB,N,V_mIsTransferMoney
// TB,N,V_mIsTwoFingersEnbale
// TB,N,V_mIsUnSendTyping
// TB,N,V_mIsUpdateTips
// TB,N,V_mIsVideoAnalysis
// TB,N,V_mIsVideoDownLoad
// TB,N,V_mIsVisualEffectView
// TB,N,V_mIsVoiceJaiYi
// TB,N,V_mIsVoiceToMP3File
// TB,N,V_mIsWeiShang
// TB,N,V_mIsWelcomeToGroup
// TB,N,V_mIsiPadLogin
// TB,N,V_mMakeMove
// TB,N,V_mMessagePreview
// TB,N,V_mMsgDateBoldFont
// TB,N,V_mQuickReplyView
// TB,N,V_mQuitMonitorEnable
// TB,N,V_mRedDetailEnable
// TB,N,V_mRoomMessagePreview
// TB,N,V_mRoomMsgPreview
// TB,N,V_mSeenMessage
// TB,N,V_messageToolBar
// TB,N,V_msgFloating
// TB,N,V_msgFloatingTips
// TB,N,V_multiplexEnabled
// TB,N,V_radom
// TB,N,V_searchItem
// TB,N,V_shareTimeLine
// TB,N,V_timeLineHiddenUser
// TB,N,V_timing
// TB,N,V_toolBarClearColor
// TB,N,V_useApnsToken
// TQ,N,V_bgTaskIdentifier
// TQ,N,V_type
// TQ,R
// Td,N,V_cellHeight
// Td,N,V_floatingFrameX
// Td,N,V_floatingFrameY
// Td,N,V_itemSize
// Td,N,V_mFakeLocationX
// Td,N,V_mFakeLocationY
// Td,N,V_size
// TextDidChanged:selectedRange:
// Ti,N,V_brandReadCount
// Ti,N,V_friendReadCount
// Ti,N,V_roomReadCount
// Ti,N,V_selectType
// Ti,N,V_type
// TopSessionByName:
// Tq,N,V_SelectType
// Tq,N,V_brandIdx
// Tq,N,V_brandIncoType
// Tq,N,V_chatBoxTopInList
// Tq,N,V_contactType
// Tq,N,V_delayTime
// Tq,N,V_helperIncoType
// Tq,N,V_mBackgroundTime
// Tq,N,V_mCustomFontSize
// Tq,N,V_mDayStepValue
// Tq,N,V_mHungUpIntervalTime
// Tq,N,V_mHungUpSendMsgTime
// Tq,N,V_mKeyDelDelMemberTime
// Tq,N,V_mMaxDuration
// Tq,N,V_mMsgDateFontSize
// Tq,N,V_mMsgDateShowPosition
// Tq,N,V_mNoticeNum
// Tq,N,V_mSendToGroupDelay
// Tq,N,V_mSendVideoTime
// Tq,N,V_mSendVoiceTime
// Tq,N,V_mStepValue
// Tq,N,V_roomIdx
// Tq,N,V_selectedType
// Tq,N,V_type
// Tq,N,V_voiceTime
// URLWithString:
// UTF8String
// UnZipFile:toPath:
// UntopSessionByName:
// WeChatMiYouSeting
// _BrandList
// _ChatList
// _FriendList
// _RoomList
// _SelectType
// _actionItem
// _actions
// _allBrandList
// _animationColor
// _animationGroup
// _assetcs
// _avatarImage
// _bgTaskIdentifier
// _bgTaskTimer
// _blankPlayer
// _brandIdx
// _brandIncoType
// _brandName
// _brandReadCount
// _cachedInteractionController
// _cellHeight
// _changeAction
// _chatBoxTopInList
// _chatContents
// _chatGPTNoAtRoomList
// _chatGPTUserList
// _chatModel
// _checkFriendsEnd
// _checkFriendsSem
// _circleShape
// _clickBtnBlock
// _clickViewBlock
// _collectionView
// _conontact
// _contactMgr
// _contactType
// _content
// _contents
// _currentCheckResult
// _customFont
// _customFontDic
// _customOrigin
// _customParserURL
// _customQRCode
// _danmuView
// _dataArr
// _dataSource
// _dayComponents
// _delay
// _delayTime
// _delegate
// _editItem
// _enabled
// _fakeNaviView
// _fileList
// _filterFriendList
// _filterRoomList
// _filterSessionList
// _firstStart
// _floatingFrameX
// _floatingFrameY
// _friendGroupName
// _friendReadCount
// _gameCustomURL
// _headImg
// _helperIncoType
// _hiddenToolBarTitle
// _hourComponents
// _hudView
// _hungUpEnabled
// _hungUpMessage
// _icon
// _iconView
// _imageView
// _inputHiddenToolBar
// _interactiveTransition
// _isAddChatBox
// _isBrandSessionHolderTop
// _isBrandShowRedDot
// _isBrandTop
// _isChatBoxTop
// _isCreate
// _isEditModel
// _isHelperTop
// _isImageCountEnabled
// _isInRoomList
// _isInsertEdit
// _isJumpAd
// _isManagerChatBox
// _isOpenBrandEnable
// _isOpenBrandHelper
// _isOpenBrandNewEnable
// _isOpenFriendEnable
// _isOpenIM
// _isOpenInRoom
// _isOpenRoomEnable
// _isOpenRoomHelper
// _isPatTipsEnabled
// _isSelectesAll
// _isToOriginalMsg
// _isWeAppJumpEnabled
// _itemSize
// _keepSendMsg
// _keyword
// _keywordContent
// _keywordReply
// _loadingView
// _localNotification
// _locationVC
// _mAtMeMessageList
// _mAutoDownloadRoomList
// _mAutoGetPaySendMsg
// _mAutoReplyMessage
// _mAutoReplyOnlineTime
// _mAutoVerifyContent
// _mAutoVerifyKeyword
// _mBackgroundTime
// _mChatGPTAPIKey
// _mCustomFontName
// _mCustomFontSize
// _mDanMuPreview
// _mDayStepValue
// _mDelAllMessage
// _mDonotdisturbList
// _mDonotdisturbMsg
// _mDonotdisturbWorkingTime
// _mFakeLocationName
// _mFakeLocationX
// _mFakeLocationY
// _mFakeNoticeBody
// _mFakeNoticeTitle
// _mFastJumpVideo
// _mFavMessagePreview
// _mGroupUndoneList
// _mHideFriendList
// _mHidePassword
// _mHideRoomList
// _mHungUpAutoSendMsgText
// _mHungUpIntervalTime
// _mHungUpSendMsgTime
// _mIsAccountSwitch
// _mIsAddDonotdisturbMenu
// _mIsAllGroupUndeno
// _mIsAllUserEnabled
// _mIsAllowedOnlyRoomMessage
// _mIsAtAllUser
// _mIsAtAllUserMessage
// _mIsAtMeMessage
// _mIsAutoConfirmLogin
// _mIsAutoDownloadFiles
// _mIsAutoDownloadImage
// _mIsAutoDownloadVideo
// _mIsAutoGetPay
// _mIsAutoGetPayTips
// _mIsAutoHungUp
// _mIsAutoLock
// _mIsAutoNotifyOpen
// _mIsAutoReplyMessage
// _mIsAutoReplyOnlineTime
// _mIsAutoVerifyFriend
// _mIsBackEdgeGesture
// _mIsBakgrunnur
// _mIsBakgrunnurTips
// _mIsCallkit
// _mIsChangeVideoTime
// _mIsChatGPTEnabled
// _mIsChatGPTTurboEnabled
// _mIsChatRoomAdmin
// _mIsChatRoomOwner
// _mIsChatVoiceToText
// _mIsCustomFont
// _mIsDelayDelMember
// _mIsDonotdisturbState
// _mIsDoubleTapEnbale
// _mIsFakeLocation
// _mIsFakeNotice
// _mIsFakeStep
// _mIsFastDelGroupMember
// _mIsFastDeleteFriend
// _mIsFirst
// _mIsForwardVoice
// _mIsHiddenHongBao
// _mIsHiddenImage
// _mIsHiddenLocation
// _mIsHiddenMessageTime
// _mIsHiddenShareGroup
// _mIsHiddenTransferMoney
// _mIsHiddenVideo
// _mIsHiddenVoiceInput
// _mIsHideAllFav
// _mIsHideFriend
// _mIsHideMode
// _mIsHideSetting
// _mIsKeepDelMessage
// _mIsKeyDelGroupMember
// _mIsKeywordAlertTips
// _mIsKeywordReplyMessage
// _mIsKeywordReplySelfMessage
// _mIsKeywordTips
// _mIsLargeVideoFile
// _mIsLineBottomTool
// _mIsLinkToSafari
// _mIsMHungUpAutoSendMsg
// _mIsMP3SendToFilehelper
// _mIsMessageTime
// _mIsMotionHide
// _mIsMsgGestureEnbale
// _mIsMsgGestureRightEnbale
// _mIsMultiplechoiceChat
// _mIsNeedAtMeEnabled
// _mIsNoRevokeContent
// _mIsOpenMiYou
// _mIsOpenNotice
// _mIsOriginalImage
// _mIsPatMessage
// _mIsPlayPayMessage
// _mIsQuickNewLine
// _mIsQuoteAtUser
// _mIsRecentForward
// _mIsRedTips
// _mIsReferModeEnabled
// _mIsReplyChatRoomMessage
// _mIsReset
// _mIsRevokeMsg
// _mIsRoomLiveEntry
// _mIsRoomVoiceToText
// _mIsSanCodeInCamera
// _mIsSelectedCustomFont
// _mIsSendToGroupHelper
// _mIsSessionGesture
// _mIsShockNotice
// _mIsShowNewMessage
// _mIsShowUserName
// _mIsShowVoiceTag
// _mIsSpotlightSearch
// _mIsTextFold
// _mIsTextJaiYi
// _mIsTheContextEnabled
// _mIsTransferMoney
// _mIsTwoFingersEnbale
// _mIsUnSendTyping
// _mIsUpdateTips
// _mIsVideoAnalysis
// _mIsVideoDownLoad
// _mIsVisualEffectView
// _mIsVoiceJaiYi
// _mIsVoiceToMP3File
// _mIsWeiShang
// _mIsWelcomeToGroup
// _mIsiPadLogin
// _mKeyDelDelMemberTime
// _mKeyDeleRoomList
// _mKeywordReplyMessage
// _mKeywordTipsList
// _mKeywordTipsRecordList
// _mMakeMove
// _mMaxDuration
// _mMessagePreview
// _mMsgDateBoldFont
// _mMsgDateColor
// _mMsgDateFontSize
// _mMsgDateFormat
// _mMsgDateShowPosition
// _mNoticeNum
// _mPatMessageList
// _mPreviewList
// _mQuickReplyView
// _mQuitMonitorEnable
// _mRedDetailEnable
// _mRegisterFontName
// _mRegisterFonts
// _mReplyChatRoomList
// _mRoomMessagePreview
// _mRoomMsgPreview
// _mSeenMessage
// _mSendToGroupDelay
// _mSendVideoTime
// _mSendVoiceTime
// _mSensitiveArr
// _mStepPrvValue
// _mStepValue
// _mWelcomeGroupContent
// _mWelcomeGroupList
// _mainButton
// _mainView
// _messageLabel
// _messageList
// _messagePrefix
// _messageToolBar
// _minuteComponents
// _model
// _modificationDate
// _motionManager
// _msgFloating
// _msgFloatingTips
// _msgs
// _multiplexEnabled
// _name
// _nameLabel
// _next
// _nextBtn
// _nextView
// _onActionBlock
// _onDoneBlock
// _onIconChangeAction
// _onSendMessageBlock
// _openaiProxy
// _pan
// _path
// _pickview
// _prompts
// _radom
// _roomIdx
// _roomName
// _roomReadCount
// _rooms
// _scrollview
// _searchItem
// _selectRowBlock
// _selectType
// _selectView
// _selectedSource
// _selectedType
// _sessionDataList
// _sessionList
// _shareTimeLine
// _silkPlay
// _size
// _systemFont
// _systemMessage
// _tabelView
// _tableView
// _tableViewManager
// _tableview
// _tap
// _text
// _textChanged:
// _textLabel
// _textView
// _themeName
// _time
// _timeLineHiddenUser
// _timeLineHiddenUsers
// _timer
// _timing
// _title
// _titleArr
// _titleLabel
// _toolActions
// _toolBarClearColor
// _turboModel
// _type
// _useApnsToken
// _user
// _userDefaults
// _users
// _voiceTime
// absoluteString
// acceleration
// accessGroup
// actionBlock
// actionItem
// actionSheet:clickedButtonAtIndex:
// actionStatMgr
// actionWithTitle:style:handler:
// actions
// actionsChange:
// adHasPlayOver
// adaptedWeSVGImageWithName:data:config:
// addAction
// addAction:
// addAction:name:icon:
// addActionWithIcon:title:action:
// addActions
// addAnimation:forKey:
// addAuthorizeSection
// addAutoGetPaySection
// addBtnTitle:handler:
// addButtonAction
// addButtonWithTitle:atIndex:
// addButtonWithTitle:eventAction:
// addCancelBtnTitle:target:sel:
// addCell:
// addCenterCellForSel:title:
// addChatBoxSection
// addChatGPTSection
// addChatGPTSettingSection
// addChatSettingSection
// addCheckSession
// addClearSession
// addContact:AtUser:
// addContactToChatBox:
// addControlEvents:Action:
// addCustomFontSection
// addDeleteFriend:
// addDescEditSection
// addDonotdisturbSection
// addEntriesFromDictionary:
// addFakeLocationSection
// addFakeStepSection
// addFavItemList:
// addFileBrowserSection
// addFileManagerSection
// addFriden:key:
// addGestureRecognizer:
// addGroupHelperSection
// addHideFriendListCell
// addHideFriendSection
// addHideRoomListCell
// addHungUpSection
// addIMBehaviorContactOp:contactOpType:
// addInvalidFriend:
// addKeywordAction
// addKeywordDeleteSection
// addKeywordManagerSection
// addKeywordMessageSection
// addKeywordTipsSection
// addLocalContact:listType:
// addMessageAction
// addMessageFloatingViewSection
// addMessageManageSection
// addMessageNode:layout:addMoreMsg:
// addMessageNode:layout:addMoreMsg:addNewMsg:
// addMessagePreviewSection
// addMessageShieldSection
// addMessageSyncSection
// addMessageTimeSection
// addMessageToolBarSection
// addMiYouSettingSection
// addMsgGestureSection
// addMsgSendOpEntrySection
// addNormalCellForSel:title:rightValue:
// addNormalCellForSel:title:rightValue:userInfo:
// addNotificationSection
// addObject:
// addObjectsFromArray:
// addObserver:selector:name:object:
// addOperationWithBlock:
// addPrompt:prompt:
// addPromptWithName:
// addReplyMessageSection
// addSection:
// addSelect:
// addSelectPhotoSection
// addSelectedMessageSection
// addSelectedUserSection
// addSendToRoomHelper
// addSensitiveListSection
// addSessionBoxSection
// addShareSection
// addSubview:
// addSwitchCellForSel:title:on:
// addTableViewToSuperView:
// addTarget:action:forControlEvents:
// addTask
// addTaskTypeSection
// addToRunLoop:forMode:
// addUserForPreviewList:
// addValidFriend:
// addVisualEffectViewSection
// addVoiceSection
// addkeywordTextSection
// alertControllerTitle:message:btnTitle:
// alertControllerTitle:message:text:block:
// alertControllerTitle:message:text:bolck:
// alertControllerWithTitle:message:preferredStyle:
// alertMessage:message:
// allBrandList
// allFilesAtPath:
// allFriends
// allKeys
// allTask
// alloc
// animateKeyframesWithDuration:delay:options:animations:completion:
// animateWithDuration:animations:
// animateWithDuration:animations:completion:
// animateWithDuration:delay:options:animations:completion:
// animation
// animationColor
// animationDidEndRemainView:hintDataItem:
// animationGroup
// animationWithKeyPath:
// appendFormat:
// appendString:
// application:continueUserActivity:restorationHandler:
// application:didFinishLaunchingWithOptions:
// applicationDidBecomeActive:
// applicationDidEnterBackground:
// applicationState
// applicationWillResignActive:
// applicationWillTerminate:
// applyBGWithController:
// arrFavItem
// arrMenuItems
// array
// arrayByAddingObjectsFromArray:
// arrayWithArray:
// arrayWithObject:
// arrayWithObjects:
// arrayWithObjects:count:
// assetWithURL:
// assetcs
// asyncSaveFrontUserName
// attachmentButton
// attributesOfItemAtPath:error:
// autoVoiceTrans
// autorelease
// avatarImage
// awakeFromNib
// backgroundColor
// backgroundTimeRemaining
// base64EncodedStringWithOptions:
// baseContent
// basePrompt
// becomeFirstResponder
// beginBackgroundTaskWithExpirationHandler:
// bezierPathWithRoundedRect:cornerRadius:
// bgTaskIdentifier
// bgTaskTimer
// bitInFileName
// blackColor
// blankPlayer
// boldSystemFontOfSize:
// boolForKey:
// boolValue
// bounds
// brandIdx
// brandIncoType
// brandName
// brandReadCount
// bundleID
// bundleId
// bundleIdentifier
// bundlePath
// buttonAnimation
// buttonTarget
// buttonTitleList
// buttonWidth:
// buttonWithType:
// bytes
// cStringUsingEncoding:
// cache
// canBeForwardWithMsg
// canEvaluatePolicy:error:
// canFoldTopSession
// canOpenURL:
// canSendOriginImage
// canSendOriginalImage
// canShowBottomBar
// cancel
// cancelLocalNotification:
// cancelPreviousPerformRequestsWithTarget:selector:object:
// cellBackgroundColor
// cellForMakeSel:makeTarget:height:userInfo:
// cellForRowAtIndexPath:
// cellHeight
// cellMenuBackgroundColor
// cellView
// cellViewClassName
// center
// centerCellForSel:target:title:
// centerY
// changBoundsabovePanPoint:
// changeAction
// changeIndex:
// changeStatus
// changeTaskState:
// characterAtIndex:
// chatBoxSessions
// chatBoxTopInList
// chatContents
// chatGPTNoAtRoomList
// chatGPTTurboWithContents:success:failure:
// chatGPTTurboWithUser:message:
// chatGPTUserList
// chatGPTWithPrompt:success:failure:
// chatGPTWithUser:message:
// chatModel
// chatProfileSwitchSetting:withType:andValue:
// chatToolBar
// chatroomManager
// checkAndAllowNewSelect:
// checkAndRunTask
// checkAndUpdateLeftNavBarItemForMiniTaskEntry
// checkConsistency:
// checkCount
// checkDeleteFriends
// checkFridens
// checkFriends
// checkFriendsEnd
// checkFriendsEnd:
// checkFriendsSem
// checkHook:
// checkHookWithSeq:
// checkInvalidFriends
// checkLoadData
// checkLoadSessions
// checkTableViewEditingStyle
// checkTasks
// choiceVideoAction
// circleShape
// class
// clearAllSection
// clearColor
// clearConfig
// clearDeleteFridens
// clearFridens
// clearFridensConfig
// clearValidateDeleteFridens
// click:
// clickBtnBlock
// clickOnLinkEvent:
// clickViewBlock
// code
// collectionView
// collectionView:canEditItemAtIndexPath:
// collectionView:canFocusItemAtIndexPath:
// collectionView:canMoveItemAtIndexPath:
// collectionView:canPerformAction:forItemAtIndexPath:withSender:
// collectionView:canPerformPrimaryActionForItemAtIndexPath:
// collectionView:cellForItemAtIndexPath:
// collectionView:contextMenuConfiguration:dismissalPreviewForItemAtIndexPath:
// collectionView:contextMenuConfiguration:highlightPreviewForItemAtIndexPath:
// collectionView:contextMenuConfigurationForItemAtIndexPath:point:
// collectionView:contextMenuConfigurationForItemsAtIndexPaths:point:
// collectionView:didBeginMultipleSelectionInteractionAtIndexPath:
// collectionView:didDeselectItemAtIndexPath:
// collectionView:didEndDisplayingCell:forItemAtIndexPath:
// collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:
// collectionView:didHighlightItemAtIndexPath:
// collectionView:didSelectItemAtIndexPath:
// collectionView:didUnhighlightItemAtIndexPath:
// collectionView:didUpdateFocusInContext:withAnimationCoordinator:
// collectionView:indexPathForIndexTitle:atIndex:
// collectionView:layout:insetForSectionAtIndex:
// collectionView:layout:minimumLineSpacingForSectionAtIndex:
// collectionView:layout:sizeForItemAtIndexPath:
// collectionView:moveItemAtIndexPath:toIndexPath:
// collectionView:numberOfItemsInSection:
// collectionView:performAction:forItemAtIndexPath:withSender:
// collectionView:performPrimaryActionForItemAtIndexPath:
// collectionView:previewForDismissingContextMenuWithConfiguration:
// collectionView:previewForHighlightingContextMenuWithConfiguration:
// collectionView:sceneActivationConfigurationForItemAtIndexPath:point:
// collectionView:selectionFollowsFocusForItemAtIndexPath:
// collectionView:shouldBeginMultipleSelectionInteractionAtIndexPath:
// collectionView:shouldDeselectItemAtIndexPath:
// collectionView:shouldHighlightItemAtIndexPath:
// collectionView:shouldSelectItemAtIndexPath:
// collectionView:shouldShowMenuForItemAtIndexPath:
// collectionView:shouldSpringLoadItemAtIndexPath:withContext:
// collectionView:shouldUpdateFocusInContext:
// collectionView:targetContentOffsetForProposedContentOffset:
// collectionView:targetIndexPathForMoveFromItemAtIndexPath:toProposedIndexPath:
// collectionView:targetIndexPathForMoveOfItemFromOriginalIndexPath:atCurrentIndexPath:toProposedIndexPath:
// collectionView:transitionLayoutForOldLayout:newLayout:
// collectionView:viewForSupplementaryElementOfKind:atIndexPath:
// collectionView:willDisplayCell:forItemAtIndexPath:
// collectionView:willDisplayContextMenuWithConfiguration:animator:
// collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath:
// collectionView:willEndContextMenuInteractionWithConfiguration:animator:
// collectionView:willPerformPreviewActionForMenuWithConfiguration:animator:
// collectionViewDidEndMultipleSelectionInteraction:
// colorInLightMode:DarkMode:
// colorWithRed:green:blue:alpha:
// colorWithWhite:alpha:
// combineToolView
// comment
// commentCount
// commentUsers
// compare:
// components:fromDate:
// componentsJoinedByString:
// componentsSeparatedByString:
// configVoiceComponent
// configurationWithActions:
// conformsToProtocol:
// conontact
// contactList
// contactMgr
// contactSelected
// contactType
// contactsDict
// contactsForRecentForwardMenu
// contactsKeyArray
// containsObject:
// containsString:
// content
// contentDesc
// contentObj
// contentView
// contents
// contentsOfDirectoryAtPath:error:
// contextMenuEnabled
// contextualActionWithStyle:title:handler:
// convertBytesToString:
// convertPcmToMp3WithPcmPath:mp3Path:
// convertSilkToPcmWithSilkPath:pcmPath:
// coordinate
// coordinateReadingItemAtURL:options:error:byAccessor:
// copy
// copyItemAtPath:toPath:error:
// copywxid
// count
// countByEnumeratingWithState:objects:count:
// counter
// createCirclePathWithRadius:radius:
// createCircleShapeWithPosition:pathRect:radius:
// createDirectoryAtPath:withIntermediateDirectories:attributes:error:
// createError:
// createFlashAnimationWithScale:duration:
// createSegmentedControl
// createSessionWithUserName:nickName:showRedDot:readAsRedDot:
// createSpotlightSearch
// createZipFileAtPath:withContentsOfDirectory:
// createZipFileAtPath:withFilesAtPaths:
// creditgrants
// creditgrants:success:
// currentCheckResult
// currentContext
// currentMedia
// currentRunLoop
// currentTempVideoPath
// currentTheme
// currentThread
// currentTitleColor
// currentVideoPath
// customFont
// customFontDic
// customFontWithName:size:
// customFontWithPath:size:
// customOrigin
// customParserURL
// customQRCode
// customizeActionsForActionSheet:
// danmuView
// dataArr
// dataItem
// dataList
// dataSource
// dataTaskWithRequest:completionHandler:
// dataUsingEncoding:
// dataWithBytesNoCopy:length:
// dataWithContentsOfFile:
// dataWithContentsOfURL:
// dataWithData:
// dataWithJSONObject:options:error:
// date
// dateFromComponents:
// dateFromString:
// datePickerConfirm:
// dateWithTimeIntervalSince1970:
// dateWithTimeIntervalSinceNow:
// day
// dayComponents
// dealloc
// debugDescription
// decSizeBytes
// defaultCenter
// defaultManager
// defaultParamWithMediaInfo:
// defaultSearchableIndex
// defaultSessionConfiguration
// delay
// delayTime
// delegate
// delegateEx
// deleteAllSearchableItems
// deleteAllSearchableItemsWithCompletionHandler:
// deleteAllTips
// deleteContact:listType:
// deleteContactLocal:listType:
// deleteFontFile
// deleteFriend:
// deleteFriends
// deleteFriends:
// deleteInvalidFriend:
// deleteMiYouList
// deleteOpenImContact:
// deleteOpenImContact:isRetainChatHistory:
// deleteSearchableItemsWithIdentifiers:completionHandler:
// deleteSessionAtIndex:
// deleteSuccess:
// deleteTaskWithModel:
// deleteValidateFridens
// deleteValidateSuccess:
// dequeueReusableCellWithIdentifier:
// dequeueReusableCellWithIdentifier:forIndexPath:
// dequeueReusableCellWithReuseIdentifier:forIndexPath:
// description
// deselectRowAtIndexPath:animated:
// detailTextLabel
// deviceXml
// dictionary
// dictionaryWithContentsOfFile:
// dictionaryWithDictionary:
// dictionaryWithObjects:forKeys:count:
// didSelectContact:
// didSelectDeleteTag:
// didSelectGuoup:
// didSelectItem:
// didSelectJumpToChat
// direction
// dismissAnimated:
// dismissViewControllerAnimated:completion:
// dismissWithAnimated:
// displayLinkWithTarget:selector:
// displaySignalMessage:
// documentPicker:didPickDocumentAtURL:
// documentPicker:didPickDocumentsAtURLs:
// documentPickerMode
// documentPickerWasCancelled:
// doubleForKey:
// doubleValue
// downloadCDNMgr
// draftWithVideoURL:
// drawInRect:
// duration
// editAction
// editItem
// editKeyword:
// effectWithStyle:
// enabled
// endBackgroundTask:
// enumerateByteRangesUsingBlock:
// enumerateKeysAndObjectsUsingBlock:
// enumerateObjectsUsingBlock:
// errorInfo
// errorWithDomain:code:userInfo:
// evaluatePolicy:localizedReason:reply:
// executablePath
// fakeNaviView
// familyName
// familyNames
// fileExistsAtPath:
// fileExistsAtPath:isDirectory:
// fileFormat
// fileLength
// fileList
// fileURLWithPath:
// filtCacheArr:
// filtDataItemArr:
// filtFavDataArr:
// filtGroupUndoneBarArr:
// filtMessageHidden:
// filtPatMessageArr:
// filtSNSMessageArr:
// filtShareSessionArr:
// filtTimelineDataItem:
// filtUserArr:
// filterFriendList
// filterRoomList
// filterSessionList
// filteredArrayUsingPredicate:
// filteredMenuItems:
// finishSearch
// fire
// firstMatchInString:options:range:
// firstObject
// firstStart
// floatValue
// floatingFrameX
// floatingFrameY
// followAouthor
// font
// fontName
// fontPath
// fontWithName:size:
// forceDownloadMediaWithProcessNotify:downloadType:
// forceHideMenuOptionsAnimated:
// forwardMessage:fromViewController:
// frame
// frames
// friendGroupName
// friendReadCount
// fromScene
// fromUsr
// fulFillSession:
// functionWithName:
// gameCustomURL
// genCurrentTime
// genInviteMessageFromVoipMonoMsg:
// genItemWithID:title:imageName:actionType:actionName:pluginUserName:
// genServerCurrentTime
// generalPasteboard
// generateOperationMenu
// generateReplySummary:
// generateVideoThumbImage:atTime:
// gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:
// gestureRecognizer:shouldReceiveEvent:
// gestureRecognizer:shouldReceivePress:
// gestureRecognizer:shouldReceiveTouch:
// gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
// gestureRecognizer:shouldRequireFailureOfGestureRecognizer:
// gestureRecognizerShouldBegin:
// getAllBrandContacts
// getAllContacts
// getAppViewControllerManager
// getBarButtonWithImageName:target:action:style:accessibility:
// getBarButtonWithTitle:target:action:style:
// getBrandContactType
// getBytes:length:
// getCache
// getCellData:
// getChatRoomMemberWithoutMyself:
// getChatUsername
// getColor:
// getContact:
// getContactByName:
// getContactForSearchByName:
// getContactFrom:
// getContactHeadImage
// getContactList:contactType:
// getContactsArrayWith:
// getContactsFromServer:
// getContactsFromServer:chatContact:withScene:withTicket:usrData:
// getContentsWithUser:message:
// getCurUsrName
// getCurrentNavigationController
// getCurrentPOIInfo
// getCurrentTotalCount
// getDateStringWithTimeStr:
// getDicContacts
// getDicWithUserNameForAllTag
// getFileType:
// getFileWithName:
// getFirstHasUnreadMsgSessionIndexFrom:
// getFirstPageFavoritesItemList:byType:
// getFirstPageFavoritesList:
// getFormatVideoPath
// getGroupUndoneBarHeight
// getHeadImage:withCategory:
// getHeadImageView
// getHour
// getIconImageByFileExt:iconSize:
// getJailbreakPath
// getJailbreakRootDir
// getLastWCObject
// getLink:
// getLocalUsrName:
// getMainWindow
// getMd5:
// getMessageFrom:maxCount:
// getMinute
// getMobileProvision
// getNextPageFavoritesList:byCurMinUpdateTime:
// getPromptWithUser:message:
// getRandomNumber:to:
// getRecentShareSessionWithSessionList:
// getRightBarButton
// getSearchResult
// getSectionAt:
// getSelfContact
// getService:
// getSessionCount
// getSessionCountForSection:
// getSessionInfo:
// getSessionInfoAtIndexPath:
// getSoundName
// getStringForCurLanguage:
// getTableView
// getTaskNextRunTime:
// getTextFieldText
// getTimeStrWithString:
// getToDay
// getTomorrowDay
// getTopViewController
// getTransToolHeight
// getUnReadMessageCount
// getUnReadMessages
// getUnReadMessagesLimit:
// getValueOfProperty:inRuleSet:
// getViewController
// getWechatUserName
// handleDoubleTapFrom:
// handleNavigation:
// handleNavigationTransition:
// handleSingle:
// handlelongGesture:
// hasImages
// hasPrefix:
// hasRecentForwardSessions
// hasSharedGroup
// hasSuffix:
// hash
// hashPathForString:
// headImg
// height
// helperIncoType
// hexStringToColor:
// hiddenBottomTool
// hiddenToolBarTitle
// hide
// hideMenuOptionsAnimated:
// hideMessage
// hideSession:
// hkStepCount
// homePageMaxContinueReqCount
// hourComponents
// hudView
// hungUpEnabled
// hungUpMessage
// icon
// iconView
// image
// imageData:fromConfig:
// imageData:resize:scale:
// imageInLightMode:darkMode:
// imageNamed:
// imageNamed:fromConfig:
// imagePickerController:didFinishPickingImage:editingInfo:
// imagePickerController:didFinishPickingMediaWithInfo:
// imagePickerControllerDidCancel:
// imageView
// imageWithContentsOfFile:
// imageWithData:
// impactOccurred
// importFont
// importFont:
// importTheme
// importTheme:
// inFile
// inRoomList
// indexPathForPreferredFocusedViewInCollectionView:
// indexPathForPreferredFocusedViewInTableView:
// indexPathForRow:inSection:
// indexPathWithIndexes:length:
// indexPathsForSelectedRows
// indexSearchableItems:completionHandler:
// indexTitlesForCollectionView:
// infoDictionary
// init
// initData
// initData:
// initFontData
// initMsgSearchHelper:
// initNav
// initNavHeaderIfNeed
// initNavHeaderView
// initTableView
// initUI
// initView
// initViews
// initWithActivityItems:applicationActivities:
// initWithBarButtonSystemItem:target:action:
// initWithBase64EncodedString:options:
// initWithCalendarIdentifier:
// initWithContactType:
// initWithContentsOfURL:error:
// initWithCustomView:
// initWithData:
// initWithData:encoding:
// initWithDataItem:
// initWithDocumentTypes:inMode:
// initWithEffect:
// initWithFrame:
// initWithFrame:collectionViewLayout:
// initWithFrame:countdownNum:
// initWithFrame:style:
// initWithImage:
// initWithImages:contacts:
// initWithItemContentType:
// initWithItems:
// initWithKey:ascending:
// initWithLoginInfo:
// initWithMainBrandContact:fromScene:
// initWithMessage:name:avatar:
// initWithMsgType:
// initWithNibName:bundle:
// initWithPath:
// initWithPreferredDate:
// initWithRootViewController:
// initWithScene:delegate:sort:extendChatRoom:
// initWithSceneType:OnlyUseUserLocation:
// initWithSessionInfo:
// initWithSightDraft:
// initWithString:
// initWithStyle:
// initWithStyle:reuseIdentifier:
// initWithSuiteName:
// initWithTarget:action:
// initWithTimeIntervalSinceNow:
// initWithTitle:action:
// initWithTitle:cancelButtonTitle:
// initWithTitle:message:
// initWithTitle:svgName:action:
// initWithURL:entersReaderIfAvailable:
// initWithURL:inMode:
// initWithURLString:fromScene:extInfo:
// initWithUTF8String:
// initWithUniqueIdentifier:domainIdentifier:attributeSet:
// initWithViewModel:
// initWithWeAppUsername:
// inputHidden:
// inputHiddenToolBar
// inputMode
// inputModeChangeButton
// insertObject:atIndex:
// insertString:
// insideCallBackGetTransferPrepayResponse:OnRequest:
// intValue
// integerForKey:
// integerValue
// intelligentMsgBrowseView:willChangeCheckMarkTo:withMsgInfo:
// interactiveTransition
// internalHandleJump:translateInfo:parentViewController:
// intrinsicContentSize
// invalidate
// isAddChatBox
// isAddGesture
// isAdmin
// isBrandContact
// isBrandSessionHolder
// isBrandSessionHolderTop
// isBrandShowRedDot
// isBrandTimelineOpen
// isBrandTop
// isCallkitAvailable
// isChatBoxTop
// isChatStatusNotifyOpen
// isChatroom
// isContactInChatBox:
// isContactSessionTop
// isCreate
// isDeviceCallkitAvailable
// isDownloadH265File
// isDownloadH266File
// isEditModel
// isEqual:
// isEqualToArray:
// isEqualToDictionary:
// isEqualToString:
// isExceptionFileName:
// isFavour
// isFileHelper
// isFollowAuthor
// isGroupCard
// isHelperTop
// isImage:
// isImageCountEnabled
// isInContactList:
// isInMyContactList
// isInRoomList
// isInVoip
// isInsertEdit
// isJumpAd
// isKindOfClass:
// isLbsroom
// isLocalizedContact
// isLogin
// isMMContact
// isMacHelper
// isManagerChatBox
// isMemberOfClass:
// isNeedHideUserName
// isOn
// isOpenBrandEnable
// isOpenBrandHelper
// isOpenBrandNewEnable
// isOpenFriendEnable
// isOpenIM
// isOpenImContact
// isOpenInRoom
// isOpenRoomEnable
// isOpenRoomHelper
// isOpenSendOriginVideo
// isOriginalImage
// isOverADay
// isOwner
// isPatTipsEnabled
// isProxy
// isQQMBlog
// isSelectesAll
// isSelf
// isSenderFromMsgWrap:
// isShowToolBarInMsg
// isSnsBlack
// isTemplateMsgHolder
// isTimelineVideoSightAutoPlayEnable
// isToOriginalMsg
// isValidFriend:
// isWAVideoCompressed
// isWeAppJumpEnabled
// isWeAppJumpEnabled:
// isWeiShang
// isWeixinTeamContact
// isWorkinghours
// isiPad
// item
// itemSize
// itemSwitchChange:
// itemType
// jumpToCameraScanInTopViewController:
// jumpToOfflinePayWithEntryVC:
// justbegin
// keepSendMsg
// keepSendMsg:
// keyWindow
// keyword
// keywordContent
// keywordReply
// labelColor
// lastObject
// lastPathComponent
// layer
// layoutFinished
// layoutSubviews
// len
// length
// lengthOfString:
// likeCount
// likeUsers
// load:accessGroup:migratable:
// loadData
// loadSignature
// loadTableData
// loadWXGame
// loadingView
// localAuthenticationSuccess:failure:
// localId
// localNotification
// localizedCompare:
// localizedDescription
// locationChange:
// locationInView:
// locationVC
// logicController
// logicGetSessionAtIndexPath:
// loginSegmentedControl
// loginUrl
// longLongValue
// lowercaseString
// m7StepCount
// mAtMeMessageList
// mAutoDownloadRoomList
// mAutoGetPaySendMsg
// mAutoReplyMessage
// mAutoReplyOnlineTime
// mAutoVerifyContent
// mAutoVerifyKeyword
// mBackgroundTime
// mChatGPTAPIKey
// mCustomFontName
// mCustomFontSize
// mDanMuPreview
// mDayStepValue
// mDelAllMessage
// mDonotdisturbList
// mDonotdisturbMsg
// mDonotdisturbWorkingTime
// mFakeLocationName
// mFakeLocationX
// mFakeLocationY
// mFakeNoticeBody
// mFakeNoticeTitle
// mFastJumpVideo
// mFavMessagePreview
// mGroupUndoneList
// mHideFriendList
// mHidePassword
// mHideRoomList
// mHungUpAutoSendMsgText
// mHungUpIntervalTime
// mHungUpSendMsgTime
// mIsAccountSwitch
// mIsAddDonotdisturbMenu
// mIsAllGroupUndeno
// mIsAllUserEnabled
// mIsAllowedOnlyRoomMessage
// mIsAtAllUser
// mIsAtAllUserMessage
// mIsAtMeMessage
// mIsAutoConfirmLogin
// mIsAutoDownloadFiles
// mIsAutoDownloadImage
// mIsAutoDownloadVideo
// mIsAutoGetPay
// mIsAutoGetPayTips
// mIsAutoHungUp
// mIsAutoLock
// mIsAutoNotifyOpen
// mIsAutoReplyMessage
// mIsAutoReplyOnlineTime
// mIsAutoVerifyFriend
// mIsBackEdgeGesture
// mIsBakgrunnur
// mIsBakgrunnurTips
// mIsCallkit
// mIsChangeVideoTime
// mIsChatGPTEnabled
// mIsChatGPTTurboEnabled
// mIsChatRoomAdmin
// mIsChatRoomOwner
// mIsChatVoiceToText
// mIsCustomFont
// mIsDelayDelMember
// mIsDonotdisturbState
// mIsDoubleTapEnbale
// mIsFakeLocation
// mIsFakeNotice
// mIsFakeStep
// mIsFastDelGroupMember
// mIsFastDeleteFriend
// mIsFirst
// mIsForwardVoice
// mIsHiddenHongBao
// mIsHiddenImage
// mIsHiddenLocation
// mIsHiddenMessageTime
// mIsHiddenShareGroup
// mIsHiddenTransferMoney
// mIsHiddenVideo
// mIsHiddenVoiceInput
// mIsHideAllFav
// mIsHideFriend
// mIsHideMode
// mIsHideSetting
// mIsKeepDelMessage
// mIsKeyDelGroupMember
// mIsKeywordAlertTips
// mIsKeywordReplyMessage
// mIsKeywordReplySelfMessage
// mIsKeywordTips
// mIsLargeVideoFile
// mIsLineBottomTool
// mIsLinkToSafari
// mIsMHungUpAutoSendMsg
// mIsMP3SendToFilehelper
// mIsMessageTime
// mIsMotionHide
// mIsMsgGestureEnbale
// mIsMsgGestureRightEnbale
// mIsMultiplechoiceChat
// mIsNeedAtMeEnabled
// mIsNoRevokeContent
// mIsOpenMiYou
// mIsOpenNotice
// mIsOriginalImage
// mIsPatMessage
// mIsPlayPayMessage
// mIsQuickNewLine
// mIsQuoteAtUser
// mIsRecentForward
// mIsRedTips
// mIsReferModeEnabled
// mIsReplyChatRoomMessage
// mIsReset
// mIsRevokeMsg
// mIsRoomLiveEntry
// mIsRoomVoiceToText
// mIsSanCodeInCamera
// mIsSelectedCustomFont
// mIsSendToGroupHelper
// mIsSessionGesture
// mIsShockNotice
// mIsShowNewMessage
// mIsShowUserName
// mIsShowVoiceTag
// mIsSpotlightSearch
// mIsTextFold
// mIsTextJaiYi
// mIsTheContextEnabled
// mIsTransferMoney
// mIsTwoFingersEnbale
// mIsUnSendTyping
// mIsUpdateTips
// mIsVideoAnalysis
// mIsVideoDownLoad
// mIsVisualEffectView
// mIsVoiceJaiYi
// mIsVoiceToMP3File
// mIsWeiShang
// mIsWelcomeToGroup
// mIsiPadLogin
// mKeyDelDelMemberTime
// mKeyDeleRoomList
// mKeywordReplyMessage
// mKeywordTipsList
// mKeywordTipsRecordList
// mMakeMove
// mMaxDuration
// mMessagePreview
// mMsgDateBoldFont
// mMsgDateColor
// mMsgDateFontSize
// mMsgDateFormat
// mMsgDateShowPosition
// mNavigationbarHeight
// mNoticeNum
// mPatMessageList
// mPreviewList
// mQuickReplyView
// mQuitMonitorEnable
// mRedDetailEnable
// mRegisterFontName
// mRegisterFonts
// mReplyChatRoomList
// mRoomMessagePreview
// mRoomMsgPreview
// mSeenMessage
// mSendToGroupDelay
// mSendVideoTime
// mSendVoiceTime
// mSensitiveArr
// mStepPrvValue
// mStepValue
// mWelcomeGroupContent
// mWelcomeGroupList
// m_arrContactNameList
// m_arrShowIDs
// m_bIsTop
// m_bShowUnReadAsRedDot
// m_cache
// m_cellData
// m_chatRoomContact
// m_componentData
// m_contact
// m_data
// m_delegate
// m_dicMultiSelect
// m_extendInfoWithMsgType
// m_extendInfoWithMsgTypeForBiz
// m_extraInfo
// m_fromUser
// m_isJustReturnMMAsset
// m_isPlugin
// m_item
// m_lRecAmount
// m_lRecNum
// m_lTotalAmount
// m_lTotalNum
// m_likeBtn
// m_mode
// m_msgWrap
// m_n64MesSvrID
// m_nameComData
// m_normalSessions
// m_nsActionName
// m_nsAliasName
// m_nsAppFileExt
// m_nsAtAll
// m_nsAtUserList
// m_nsChatRoomAdminList
// m_nsChatRoomMemList
// m_nsChatRoomUserName
// m_nsContent
// m_nsDes
// m_nsDisplayNamePY
// m_nsEncodeUserName
// m_nsExternalInfo
// m_nsFromUsr
// m_nsFullPY
// m_nsMsgSource
// m_nsName
// m_nsNickName
// m_nsOwner
// m_nsPushBody
// m_nsPushTitle
// m_nsRealChatUsr
// m_nsRemark
// m_nsShortPY
// m_nsTicket
// m_nsTitle
// m_nsToUsr
// m_nsTranferMoneyString
// m_nsUserName
// m_nsUsrName
// m_oSetting
// m_oWCPayInfoItem
// m_oWCRedEnvelopesDetailInfo
// m_rawRelativeURL
// m_receiveTime
// m_refMessageWrap
// m_roomId
// m_roomKey
// m_sessionInfo
// m_sessionShowContent
// m_shareButton
// m_shareLineView
// m_shareSubView
// m_tableView
// m_topSessions
// m_uUnReadCount
// m_uiCreateTime
// m_uiFriendScene
// m_uiID
// m_uiMesLocalID
// m_uiMessageType
// m_uiSex
// m_uiType
// m_uiVideoTime
// m_uiVoiceFormat
// m_uiVoiceTime
// m_uiWCFlag
// m_voiceComData
// mainBtnTouchDown
// mainBundle
// mainButton
// mainScreen
// mainScreenWidth
// mainView
// makeEditCell:
// makeObjectsPerformSelector:
// matchesInString:options:range:
// media
// mediaArray
// mediaList
// mediaWrapWith:
// mediaWrapWithParam:
// mergeChatRoomData:oldContact:
// message
// messageLabel
// messageList
// messageMgr
// messagePrefix
// messageSendToGroup:
// messageToolBar
// messageToolBar:
// messageWasSwiped:
// messageWrap
// methodForSelector:
// miYouSettingController
// minuteComponents
// mmSearchBarTextDidChange:
// model
// modificationDate
// modifyDataItem:notify:
// motionManager
// movePath:to:
// moveToRootViewController
// msgFloating
// msgFloatingTips
// msgFloatingTips:message:
// msgSearchBarCancel
// msgTimeLabel
// msgs
// multiplexEnabled
// mutableCopy
// n64MsgID
// nBytes
// name
// nameLabel
// navHeaderView
// navigationBar
// navigationBarHeight
// navigationContrioller
// navigationController
// navigationController:animationControllerForOperation:fromViewController:toViewController:
// navigationController:didShowViewController:animated:
// navigationController:interactionControllerForAnimationController:
// navigationController:willShowViewController:animated:
// navigationControllerPreferredInterfaceOrientationForPresentation:
// navigationControllerSupportedInterfaceOrientations:
// navigationItem
// needShowUnreadCountOnSession
// new
// newMsgTips
// newMsgTips:
// newMsgTips:user:
// newSessionMgr
// newlineCharacterSet
// next
// nextBtn
// nextResponder
// nextView
// normalCellForSel:target:title:customView:
// normalCellForSel:target:title:rightValue:
// normalCellForSel:target:title:rightValue:WithDisclosureIndicator:
// normalSessions
// normalStatusBarHeight
// notifyItem
// notifyMiniTaskEntryWhenViewWillDisappear
// notifySuspendOnMainThread
// nsTitle
// null
// numberOfComponentsInPickerView:
// numberOfRanges
// numberOfSectionsInCollectionView:
// numberOfSectionsInTableView:
// numberWithBool:
// numberWithDouble:
// numberWithInt:
// numberWithInteger:
// numberWithLongLong:
// numberWithUnsignedInt:
// object
// objectAtIndex:
// objectAtIndexedSubscript:
// objectForKey:
// objectForKeyedSubscript:
// onActionBlock
// onActionSheetIconView:didTapedWithItem:
// onAddKeyword
// onAddMessage
// onAllSelect
// onAttachmentModeChangeButtonClicked:
// onBack
// onCancelSeletctedLocation
// onChangeGameSource
// onClickItemAction:
// onCommitEditingWithStyle:tableView:
// onDone
// onDone:
// onDoneBlock
// onForward:
// onGames
// onGetRightBarButton
// onIconChangeAction
// onItemAction:
// onMonoServiceMsgStartWithMsg:
// onMultiSelectContactCancelForSns
// onMultiSelectContactReturnForSns:
// onMultiplex:
// onNavigationCancelItemClick
// onNeedReload
// onNormalContactVerifyDone:
// onNormalContactVerifyDone:encodeUserName:
// onOtherDeviceHandleTalk:WithStatus:
// onRecoverFavDB
// onReplyMsg:
// onReturnToOriginalMsg
// onRevokeMsg:
// onScanViewController
// onSearchItem
// onSendGroup
// onSendMessageBlock
// onSevLocation:
// onShareToTimeLine:
// onShouldSelectContact:
// onTapMsgReplyView:
// onTextFieldChanged:
// onToFile:
// onVideoDidPlayToEndTime
// onVideoPlayFinish
// onVoiceTrans:
// openApp:taskExtInfo:onSuccess:onFailed:
// openAudioWindowWithContact:msgWrap:isCaller:from:
// openAudioWindowWithContact:msgWrap:monoMsg:isCaller:from:
// openFileBrowser
// openIMMgr
// openToFileBrowser:
// openVideoVoipViewWithContact:isCaller:andMsgWrap:isEarMode:
// openVideoWindowWithContact:msgWrap:isCaller:from:
// openVideoWindowWithContact:msgWrap:monoMsg:isCaller:from:
// openVoipViewWithContact:isCaller:andMsgWrap:
// openWindowWithContact:msgWrap:isCaller:from:startInApp:isEarMode:isAudioMode:completion:
// openaiProxy
// orangeColor
// otherSettingSection
// out
// outFile
// outPtr
// outputAccelertionData:
// packetSize_ms
// pan
// parseFloatFromValues:
// parserData:
// parserVideo:success:failure:
// paste:
// path
// pathExtension
// pathForData
// pathForResource:ofType:
// pathsForResourcesOfType:inDirectory:
// pause
// payload
// payloadToDec
// performSelector:
// performSelector:withObject:
// performSelector:withObject:afterDelay:
// performSelector:withObject:withObject:
// pickerView:attributedTitleForRow:forComponent:
// pickerView:didSelectRow:inComponent:
// pickerView:numberOfRowsInComponent:
// pickerView:rowHeightForComponent:
// pickerView:titleForRow:forComponent:
// pickerView:viewForRow:forComponent:reusingView:
// pickerView:widthForComponent:
// pickview
// play
// playAtTime:
// playBlankAudio
// playNotice
// player
// playerWithURL:
// poiName
// popToRootViewControllerAnimated:
// popViewControllerAnimated:
// positionMode
// postNotificationName:object:
// postNotificationName:object:userInfo:
// predicateWithFormat:
// preparePlayWithFile:
// preparePlayWithSilkFile:
// presentViewController:animated:completion:
// presentingModalViewController
// printLogIvarlist:
// printLogWithClass:
// privateConfirmLoginWithInfo:
// prompts
// propertyListWithData:options:format:error:
// proxySetting
// psDec
// pushSearchControllerWithCompletion:
// queryItems
// quickRepaySheetAdapter
// quickReply
// radom
// radomMessage:
// range
// rangeAtIndex:
// rangeOfComposedCharacterSequenceAtIndex:
// rangeOfString:
// rangeOfString:options:
// rate
// rebuildMainSessions
// recentForwardContacts
// redColor
// refUserName
// refreshWholeView
// registerAddImageCallBack
// registerClass:forCellReuseIdentifier:
// registerClass:forCellWithReuseIdentifier:
// registerControllerWithTitle:version:controller:
// registerCustomFont
// registerExtension:withKey:withTarget:
// registerExtension:withTarget:
// regularExpressionWithPattern:options:error:
// release
// reloadAll
// reloadAllComponents
// reloadAllItems
// reloadData
// reloadDataWrap
// reloadProfileTableData
// reloadSensitiveData
// reloadTableData
// reloadTableView
// reloadTableViewData
// reloadTimelineDataItems
// removeAllObjects
// removeContactFromChatBox:
// removeFirstObject
// removeFromSuperlayer
// removeFromSuperview
// removeItemAtPath:error:
// removeObject:
// removeObjectAtIndex:
// removeObjectForKey:
// removeObserver:
// removeViewAnimation
// replaceBytesInRange:withBytes:length:
// replaceOccurrencesOfString:withString:options:range:
// reportAppList:
// reportIncomingCallFromUser:ofType:withMsg:
// requestMoreTime
// requestWithURL:
// requestWithURL:cachePolicy:timeoutInterval:
// requestWithUser:message:
// resortSessions
// resourcePath
// respondsToSelector:
// resume
// ret
// retain
// retainCount
// rightBarButtonAction
// rightBarButtonItem
// rightEditaction
// roomIdx
// roomName
// roomReadCount
// rooms
// rootViewController
// row
// rowActionWithStyle:title:handler:
// rowHeight
// runBackground
// runBackgroundTask
// runTask
// runTaskWithModel:
// runTimerTask
// safeAddObject:
// safeAreaInsets
// safeInsertObject:atIndex:
// safeRemoveObject:
// safeSetObject:forKey:
// sampleRate
// save:data:accessGroup:migratable:
// saveTask
// saveTaskWithModel:
// saveVideo:
// savedPhotoImage:didFinishSavingWithError:contextInfo:
// scale
// scanUpToString:intoString:
// scannerWithString:
// scheduleLocalNotification:
// scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:
// screenBounds
// scrollViewDidChangeAdjustedContentInset:
// scrollViewDidEndDecelerating:
// scrollViewDidEndDragging:willDecelerate:
// scrollViewDidEndScrollingAnimation:
// scrollViewDidEndZooming:withView:atScale:
// scrollViewDidScroll:
// scrollViewDidScrollToTop:
// scrollViewDidZoom:
// scrollViewShouldScrollToTop:
// scrollViewWillBeginDecelerating:
// scrollViewWillBeginDragging:
// scrollViewWillBeginZooming:withView:
// scrollViewWillEndDragging:withVelocity:targetContentOffset:
// scrollview
// searchBar
// searchBar:textDidChange:
// searchBarText
// searchController
// searchItem
// searcher
// secondaryLabelColor
// section
// sectionIndexTitlesForTableView:
// sectionWithHeader:Footer:
// selectPositionItem:
// selectRow:inComponent:animated:
// selectRowAtIndexPath:animated:scrollPosition:
// selectRowBlock
// selectTiming
// selectType
// selectUsers
// selectView
// selectable
// selectedMessage
// selectedQRCode
// selectedRoom
// selectedRowInComponent:
// selectedSegmentIndex
// selectedSource
// selectedType
// selectedUser
// selectionKeyword:
// self
// sendErrorMessage:message:
// sendImage:toUser:
// sendLocalMsgWithID:toUser:
// sendLoginConfirmRequest
// sendMsg:toUser:
// sendMsg:toUser:type:
// sendMsgWithLocalID:toUser:
// sendReplyMsg:MsgWrap:
// sendTextMsg:MsgWrap:
// sendVideoJsEvent:param:
// sensitiveManager
// seperatorColor
// session:inSessions:
// sessionDataList
// sessionInfo
// sessionList
// sessionManager
// sessionWithConfiguration:
// sessions:removeSession:
// setAccelerometerUpdateInterval:
// setAccessoryType:
// setAccessoryView:
// setActionBlock:
// setActionItem:
// setActions:
// setActive:
// setActive:error:
// setAlertBody:
// setAlertTitle:
// setAllBrandList:
// setAllowsEditing:
// setAllowsMultipleSelection:
// setAlpha:
// setAnimationColor:
// setAnimationGroup:
// setAnimations:
// setArrContacts:
// setAssetcs:
// setAutoLogin:
// setAutomaticallyAdjustsScrollViewInsets:
// setAutoresizingMask:
// setAvatarImage:
// setBUsePanCancelGesture:
// setBackgroundColor:
// setBackgroundView:
// setBadge:
// setBgTaskIdentifier:
// setBgTaskTimer:
// setBlankPlayer:
// setBody:
// setBool:forKey:
// setBounds:
// setBrandIdx:
// setBrandIncoType:
// setBrandList:
// setBrandName:
// setBrandReadCount:
// setBundleId:
// setCache:
// setCanSendOriginalImage:
// setCategory:error:
// setCategory:withOptions:error:
// setCellHeight:
// setCenter:
// setCenterY:
// setChangeAction:
// setChatBoxTopInList:
// setChatContents:
// setChatGPTNoAtRoomList:
// setChatGPTUserList:
// setChatList:
// setChatModel:
// setChatStatusNotifyOpen:
// setChatToolBar:
// setCheckFriendsEnd:
// setCheckFriendsSem:
// setCircleShape:
// setClickBtnBlock:
// setClickViewBlock:
// setClipsToBounds:
// setCollectionView:
// setComfirmText:
// setCommentCount:
// setCommentUsers:
// setConnectionProxyDictionary:
// setConontact:
// setContact:sessionTop:sync:
// setContactMgr:
// setContactType:
// setContent:
// setContentHeight:
// setContentInset:
// setContentInsetAdjustmentBehavior:
// setContentMode:
// setContentSize:
// setContents:
// setContextMenuEnabled:
// setCornerRadius:
// setCurrentCheckResult:
// setCustomDatePickerView:
// setCustomFont:
// setCustomFontDic:
// setCustomOrigin:
// setCustomParserURL:
// setCustomQRCode:
// setDanmuView:
// setDataArr:
// setDataSource:
// setDateFormat:
// setDatePickerMode:
// setDay:
// setDayComponents:
// setDelay:
// setDelayTime:
// setDelaysTouchesBegan:
// setDelegate:
// setDelegateEx:
// setDelegateObj:
// setDirection:
// setDirectionalLockEnabled:
// setDouble:forKey:
// setDuration:
// setEdges:
// setEditItem:
// setEditing:
// setEditing:animated:
// setEditingStyle:
// setEnableDragToClose:
// setEnableEdgeSlideToClose:
// setEnabled:
// setEstimatedRowHeight:
// setFCellHeight:
// setFakeNaviView:
// setFileList:
// setFillColor:
// setFilterFriendList:
// setFilterRoomList:
// setFilterSessionList:
// setFireDate:
// setFirstStart:
// setFloatingFrameX:
// setFloatingFrameY:
// setFont:
// setForbidDisplayMenuWithGestures:
// setFrame:
// setFriendGroupName:
// setFriendList:
// setFriendReadCount:
// setFromValue:
// setGameCustomURL:
// setHTTPBody:
// setHTTPMethod:
// setHeadImageByName:
// setHeadImg:
// setHeight:
// setHelperIncoType:
// setHidden:
// setHiddenToolBarTitle:
// setHidesBottomBarWhenPushed:
// setHostView:
// setHostViewController:
// setHourComponents:
// setHudView:
// setHungUpEnabled:
// setHungUpMessage:
// setIcon:
// setIconImg:
// setIconView:
// setImage:
// setImage:forState:
// setImage:withData:isLongOriginImage:
// setImageEdgeInsets:
// setImageView:
// setInRoomList:
// setInputHiddenToolBar:
// setInputMode:animated:
// setInteger:forKey:
// setInteractiveTransition:
// setIsAddChatBox:
// setIsAddGesture:
// setIsAllowTapBgMaskToClose:
// setIsBrandSessionHolderTop:
// setIsBrandShowRedDot:
// setIsBrandTop:
// setIsChatBoxTop:
// setIsCreate:
// setIsEditModel:
// setIsHelperTop:
// setIsImageCountEnabled:
// setIsInRoomList:
// setIsInsertEdit:
// setIsJumpAd:
// setIsManagerChatBox:
// setIsOpenBrandEnable:
// setIsOpenBrandHelper:
// setIsOpenBrandNewEnable:
// setIsOpenFriendEnable:
// setIsOpenIM:
// setIsOpenInRoom:
// setIsOpenRoomEnable:
// setIsOpenRoomHelper:
// setIsOpenSendOriginVideo:
// setIsPatTipsEnabled:
// setIsSelectesAll:
// setIsToOriginalMsg:
// setIsWAVideoCompressed:
// setIsWeAppJumpEnabled:
// setItemArray:
// setItemSize:
// setItemType:
// setKeepSendMsg:
// setKeyword:
// setKeywordContent:
// setKeywordReply:
// setKeywords:
// setLayoutMargins:
// setLeftBarButtonItem:
// setLikeCount:
// setLikeUsers:
// setLineBreakMode:
// setLineWidth:
// setLoadingView:
// setLocalNotification:
// setLocale:
// setLocalizedFallbackTitle:
// setLocationVC:
// setLoginSegmentedControl:
// setMAtMeMessageList:
// setMAutoDownloadRoomList:
// setMAutoGetPaySendMsg:
// setMAutoReplyMessage:
// setMAutoReplyOnlineTime:
// setMAutoVerifyContent:
// setMAutoVerifyKeyword:
// setMBackgroundTime:
// setMChatGPTAPIKey:
// setMCustomFontName:
// setMCustomFontSize:
// setMDanMuPreview:
// setMDayStepValue:
// setMDelAllMessage:
// setMDonotdisturbList:
// setMDonotdisturbMsg:
// setMDonotdisturbWorkingTime:
// setMFakeLocationName:
// setMFakeLocationX:
// setMFakeLocationY:
// setMFakeNoticeBody:
// setMFakeNoticeTitle:
// setMFastJumpVideo:
// setMFavMessagePreview:
// setMGroupUndoneList:
// setMHideFriendList:
// setMHidePassword:
// setMHideRoomList:
// setMHungUpAutoSendMsgText:
// setMHungUpIntervalTime:
// setMHungUpSendMsgTime:
// setMIsAccountSwitch:
// setMIsAddDonotdisturbMenu:
// setMIsAllGroupUndeno:
// setMIsAllUserEnabled:
// setMIsAllowedOnlyRoomMessage:
// setMIsAtAllUser:
// setMIsAtAllUserMessage:
// setMIsAtMeMessage:
// setMIsAutoConfirmLogin:
// setMIsAutoDownloadFiles:
// setMIsAutoDownloadImage:
// setMIsAutoDownloadVideo:
// setMIsAutoGetPay:
// setMIsAutoGetPayTips:
// setMIsAutoHungUp:
// setMIsAutoLock:
// setMIsAutoNotifyOpen:
// setMIsAutoReplyMessage:
// setMIsAutoReplyOnlineTime:
// setMIsAutoVerifyFriend:
// setMIsBackEdgeGesture:
// setMIsBakgrunnur:
// setMIsBakgrunnurTips:
// setMIsCallkit:
// setMIsChangeVideoTime:
// setMIsChatGPTEnabled:
// setMIsChatGPTTurboEnabled:
// setMIsChatRoomAdmin:
// setMIsChatRoomOwner:
// setMIsChatVoiceToText:
// setMIsCustomFont:
// setMIsDelayDelMember:
// setMIsDonotdisturbState:
// setMIsDoubleTapEnbale:
// setMIsFakeLocation:
// setMIsFakeNotice:
// setMIsFakeStep:
// setMIsFastDelGroupMember:
// setMIsFastDeleteFriend:
// setMIsFirst:
// setMIsForwardVoice:
// setMIsHiddenHongBao:
// setMIsHiddenImage:
// setMIsHiddenLocation:
// setMIsHiddenMessageTime:
// setMIsHiddenShareGroup:
// setMIsHiddenTransferMoney:
// setMIsHiddenVideo:
// setMIsHiddenVoiceInput:
// setMIsHideAllFav:
// setMIsHideFriend:
// setMIsHideMode:
// setMIsHideSetting:
// setMIsKeepDelMessage:
// setMIsKeyDelGroupMember:
// setMIsKeywordAlertTips:
// setMIsKeywordReplyMessage:
// setMIsKeywordReplySelfMessage:
// setMIsKeywordTips:
// setMIsLargeVideoFile:
// setMIsLineBottomTool:
// setMIsLinkToSafari:
// setMIsMHungUpAutoSendMsg:
// setMIsMP3SendToFilehelper:
// setMIsMessageTime:
// setMIsMotionHide:
// setMIsMsgGestureEnbale:
// setMIsMsgGestureRightEnbale:
// setMIsMultiplechoiceChat:
// setMIsNeedAtMeEnabled:
// setMIsNoRevokeContent:
// setMIsOpenMiYou:
// setMIsOpenNotice:
// setMIsOriginalImage:
// setMIsPatMessage:
// setMIsPlayPayMessage:
// setMIsQuickNewLine:
// setMIsQuoteAtUser:
// setMIsRecentForward:
// setMIsRedTips:
// setMIsReferModeEnabled:
// setMIsReplyChatRoomMessage:
// setMIsReset:
// setMIsRevokeMsg:
// setMIsRoomLiveEntry:
// setMIsRoomVoiceToText:
// setMIsSanCodeInCamera:
// setMIsSelectedCustomFont:
// setMIsSendToGroupHelper:
// setMIsSessionGesture:
// setMIsShockNotice:
// setMIsShowNewMessage:
// setMIsShowUserName:
// setMIsShowVoiceTag:
// setMIsSpotlightSearch:
// setMIsTextFold:
// setMIsTextJaiYi:
// setMIsTheContextEnabled:
// setMIsTransferMoney:
// setMIsTwoFingersEnbale:
// setMIsUnSendTyping:
// setMIsUpdateTips:
// setMIsVideoAnalysis:
// setMIsVideoDownLoad:
// setMIsVisualEffectView:
// setMIsVoiceJaiYi:
// setMIsVoiceToMP3File:
// setMIsWeiShang:
// setMIsWelcomeToGroup:
// setMIsiPadLogin:
// setMKeyDelDelMemberTime:
// setMKeyDeleRoomList:
// setMKeywordReplyMessage:
// setMKeywordTipsList:
// setMKeywordTipsRecordList:
// setMMakeMove:
// setMMaxDuration:
// setMMessagePreview:
// setMMsgDateBoldFont:
// setMMsgDateColor:
// setMMsgDateFontSize:
// setMMsgDateFormat:
// setMMsgDateShowPosition:
// setMNoticeNum:
// setMPatMessageList:
// setMPreviewList:
// setMQuickReplyView:
// setMQuitMonitorEnable:
// setMRedDetailEnable:
// setMRegisterFontName:
// setMRegisterFonts:
// setMReplyChatRoomList:
// setMRoomMessagePreview:
// setMRoomMsgPreview:
// setMSeenMessage:
// setMSendToGroupDelay:
// setMSendVideoTime:
// setMSendVoiceTime:
// setMSensitiveArr:
// setMStepPrvValue:
// setMStepValue:
// setMWelcomeGroupContent:
// setMWelcomeGroupList:
// setM_appMsgSourceType:
// setM_audioData:
// setM_bForward:
// setM_bInteractivePopEnabled:
// setM_bIsForceUpdate:
// setM_bIsTop:
// setM_bMultiSelect:
// setM_bShowUnReadAsRedDot:
// setM_contact:
// setM_delegate:
// setM_des:
// setM_dicExistContact:
// setM_dicForwardParas:
// setM_dicMultiSelect:
// setM_dtThumbnail:
// setM_dtVoice:
// setM_extendInfoWithMsgType:
// setM_forwardType:
// setM_isJustReturnMMAsset:
// setM_isShowRedDot:
// setM_lastUnReadCount:
// setM_msgWrap:
// setM_n64MesSvrID:
// setM_nsAppFileExt:
// setM_nsAppName:
// setM_nsBypMsgExtInfo:
// setM_nsChatRoomUserName:
// setM_nsContent:
// setM_nsControlTransationID:
// setM_nsCurrentUserName:
// setM_nsFromUsr:
// setM_nsMsgSource:
// setM_nsNickName:
// setM_nsPagePath:
// setM_nsProducetDesc:
// setM_nsReceiverUserName:
// setM_nsTicket:
// setM_nsTitle:
// setM_nsToUsr:
// setM_nsTranferMoneyString:
// setM_nsTransferID:
// setM_nsUserName:
// setM_nsUsrName:
// setM_oSelectedMessageWrap:
// setM_oVerifyContact:
// setM_pay_msg_type:
// setM_refMessageWrap:
// setM_scene:
// setM_sessionInfo:
// setM_shareButton:
// setM_shareLineView:
// setM_shareSubView:
// setM_textForMessageLabel:
// setM_textForNameLabel:
// setM_transferScene:
// setM_uUnReadCount:
// setM_uiAppDataSize:
// setM_uiAppMsgInnerType:
// setM_uiCreateTime:
// setM_uiDownloadStatus:
// setM_uiEffectiveDate:
// setM_uiFeeType:
// setM_uiGroupScene:
// setM_uiMesLocalID:
// setM_uiPayChannel:
// setM_uiPayScene:
// setM_uiScene:
// setM_uiStatus:
// setM_uiTotalFee:
// setM_uiTransferInvalidTime:
// setM_uiType:
// setM_uiVideoSource:
// setM_uiVoiceFormat:
// setM_uiVoiceForwardFlag:
// setM_uiVoiceTime:
// setM_uiWCFlag:
// setMainButton:
// setMainView:
// setMasksToBounds:
// setMaxConcurrentOperationCount:
// setMaxImageCount:
// setMaxMovieDuration:
// setMenuItemType:
// setMessageLabel:
// setMessageList:
// setMessagePrefix:
// setMessageToolBar:
// setMinimumPressDuration:
// setMinuteComponents:
// setModalPresentationStyle:
// setModel:
// setModificationDate:
// setMotionManager:
// setMsgFloating:
// setMsgFloatingTips:
// setMsgTimeLabel:
// setMsgs:
// setMultiplexEnabled:
// setName:
// setNameLabel:
// setNavBarBackgroundColor:
// setNavLeftStyle:
// setNavRightButton:
// setNeedEditState:
// setNeedsDisplay
// setNext:
// setNextBtn:
// setNextView:
// setNormalSessions:
// setNsTitle:
// setNumberOfLines:
// setNumberOfTapsRequired:
// setNumberOfTouchesRequired:
// setObject:atIndexedSubscript:
// setObject:forKey:
// setObject:forKeyedSubscript:
// setOn:
// setOnActionBlock:
// setOnDoneBlock:
// setOnIconChangeAction:
// setOnSendMessageBlock:
// setOpacity:
// setOpenaiProxy:
// setPageSheetConfig:
// setPan:
// setPath:
// setPerformsFirstActionWithFullSwipe:
// setPickview:
// setPlaceorderReserves:
// setPlayer:
// setPosition:
// setPostPrivacy:
// setPreservesSuperviewLayoutMargins:
// setPrompts:
// setQuickRepaySheetAdapter:
// setRadom:
// setRate:
// setRecentForwardContacts:
// setRepeatCount:
// setRightBarButtonItem:
// setRightBarButtonItems:
// setRoomIdx:
// setRoomList:
// setRoomName:
// setRoomReadCount:
// setRooms:
// setRowHeight:
// setScrollEnabled:
// setScrollview:
// setSearchItem:
// setSelectRowBlock:
// setSelectType:
// setSelectView:
// setSelected:animated:
// setSelectedRange:
// setSelectedSegmentIndex:
// setSelectedSource:
// setSelectedType:
// setSelectionStyle:
// setSeparatorColor:
// setSeparatorInset:
// setSeparatorStyle:
// setSessionDataList:
// setSessionList:
// setShareTimeLine:
// setShowAutoLoginEntrance:
// setShowSyncChat:
// setShowSyncChatEntrance:
// setShowsHorizontalScrollIndicator:
// setShowsVerticalScrollIndicator:
// setSilkPlay:
// setSize:
// setSoundName:
// setSourceType:
// setStatusBarStyle:viewController:
// setString:
// setSyncChat:
// setSystemFont:
// setSystemMessage:
// setTabelView:
// setTableFooterView:
// setTableView:
// setTableViewManager:
// setTableview:
// setTag:
// setTailColor:
// setTap:
// setTempSelectContacts:
// setText:
// setTextAlignment:
// setTextColor:
// setTextFieldDefaultText:
// setTextFieldPlaceHolder:
// setTextLabel:
// setTextView:
// setThemeName:
// setThumb_path:
// setThumbnailData:
// setTime:
// setTimeLineHiddenUser:
// setTimeLineHiddenUsers:
// setTimer:
// setTiming:
// setTimingFunction:
// setTintColor:
// setTitle:
// setTitle:forState:
// setTitleArr:
// setTitleColor:forState:
// setTitleLabel:
// setToValue:
// setToolActions:
// setToolBarClearColor:
// setToolViewHidden:
// setTopSessions:
// setTurboModel:
// setType:
// setUiMaxVideoDuration:
// setUiOfflinePayLimit:
// setUseApnsToken:
// setUseLargeFileAPI:
// setUser:
// setUserDefaults:
// setUserInfo:
// setUserInteractionEnabled:
// setUsers:
// setValue:forHTTPHeaderField:
// setValue:forKey:
// setValue:forKeyPath:
// setVideoPath:initialTime:isHLS:
// setVideoQualityType:
// setVideo_path:
// setVideo_time:
// setVoice:
// setVoiceTime:
// setVolume:
// setWidth:
// setX:
// setY:
// settimgImageCount:
// settingAPIKEY
// settingAccountSwitch:
// settingActions
// settingAddChatBoxEnable:
// settingAddDonotdisturbMenu:
// settingAlertTips:
// settingAllGroupUndone:
// settingAllUserEnabled:
// settingAllowedOnlyRoomMessage:
// settingAtAllUser:
// settingAtMeEnabled:
// settingAtMeMessage:
// settingAutoConfirmLogin:
// settingAutoDownload:
// settingAutoDownloadFilesEnable:
// settingAutoDownloadImageEnable:
// settingAutoDownloadVideoEnable:
// settingAutoGetPayEnable:
// settingAutoGetPayTipsEnable:
// settingAutoHungUp:
// settingAutoLock:
// settingAutoSendMsg
// settingAutoVerifyContent
// settingAutoVerifyFriend:
// settingAutoVerifyKeyword
// settingBackEdgeGesture:
// settingBackgroundTime
// settingBakgrunnur:
// settingBakgrunnurTips:
// settingBoldFontSize:
// settingBottomToolEnable:
// settingBrandEnable:
// settingBrandIconType
// settingBrandNewEnable:
// settingBrandSessionTop:
// settingBrandTopEnable:
// settingChangeVideoTime:
// settingChatBoxTopEnable:
// settingChatGPT
// settingChatGPT:
// settingChatModel
// settingChatRoomAdmin:
// settingChatRoomOwner:
// settingChatVoiceToText:
// settingCheckFriends
// settingCustomEnabled:
// settingCustomFont:
// settingCustomFontName
// settingCustomOrigin
// settingDanMuPreview:
// settingDateColor
// settingDateFormat
// settingDelAllMessage:
// settingDelay
// settingDelayDelMember:
// settingDelayTime
// settingDonotdisturbMsg
// settingDonotdisturbState:
// settingDoubleTapEnable:
// settingEnabled:
// settingFakeLocation:
// settingFakeNotice:
// settingFakeStep:
// settingFastDeleteFriend:
// settingFastGroupMember:
// settingFavMessagePreview:
// settingFileToUser:
// settingFilterRoom:
// settingFontSize
// settingForwardVoice:
// settingFriendEnable:
// settingFriendName
// settingGPTTurboEnabled:
// settingHiddenHiddenLocation:
// settingHiddenHiddenVoiceInput:
// settingHiddenHongBao:
// settingHiddenImage:
// settingHiddenShareGroup:
// settingHiddenTime:
// settingHiddenTransferMoney:
// settingHiddenVideo:
// settingHideAllFav:
// settingHideFriend:
// settingHideNotice
// settingHidePassword
// settingHideSetting:
// settingHungUpAutoReplayMsg:
// settingHungUpAutoSendMsg:
// settingHungUpAutoSendMsgText
// settingHungUpIntervalTime
// settingHungUpMessage
// settingHungUpSendMsgTime
// settingIconType
// settingIsHelperTop:
// settingIsWeiShang:
// settingJumpVideo:
// settingKeepDelMessage:
// settingKeyDelDelMemberTime
// settingKeyDelGroupMember:
// settingKeyDeleRoomList
// settingKeywordReplyMessage:
// settingKeywordTips:
// settingKeywordTipsList
// settingLargeVideoFile:
// settingLinkToSafariEnable:
// settingMakeMove:
// settingManagerChatBoxEnable:
// settingMaxDuration
// settingMessageList
// settingMessagePrefix
// settingMessagePreview:
// settingMessageTime:
// settingModel
// settingMotionHide:
// settingMsgFloating:
// settingMsgFloatingTips:
// settingMsgGestureEnable:
// settingMsgGestureRightEnable:
// settingMsgTask
// settingMsgToGroup
// settingMsgToGroupForTag
// settingMultiplechoiceChat:
// settingMultiplexEnabled:
// settingNoAtChatGPT:
// settingNoUpdateTips:
// settingNoticeBody
// settingNoticeNum
// settingNoticeTitle
// settingOpenCallKit:
// settingOpenNotice:
// settingOpenRoomEnable:
// settingOriginalImage:
// settingParserURL
// settingPatMessage:
// settingPatTips:
// settingPlayPayMessage:
// settingPrompts
// settingQuickNewLine:
// settingQuickRepay:
// settingQuitMonitorEnable:
// settingQuoteAtUserEnable:
// settingRecentForward:
// settingRedDetailEnable:
// settingRedDotEnable:
// settingRedMessageTips:
// settingReferModeEnabled:
// settingReplyChatRoomMessage:
// settingReplyDelayTime
// settingReplyMessage:
// settingReplyOnlineTime:
// settingReplySelfMsg:
// settingRevokeContent:
// settingRevokeMsg:
// settingRoomLiveEntry:
// settingRoomMessagePreview:
// settingRoomMsgPreview:
// settingRoomUnDone:
// settingRoomVoiceToText:
// settingSanCodeInCamera:
// settingSearchEnabled:
// settingSeenMessage:
// settingSendToGroupHelper:
// settingSendVidoTime
// settingSessionGesture:
// settingShockNotice:
// settingShowNewMessage:
// settingShowUserNameEnable:
// settingShowVoiceTag:
// settingSpotlightSearch:
// settingStepPrvValue
// settingStepValue
// settingTaskName
// settingTextFold:
// settingTextJiaYiEnable:
// settingTheme
// settingTiming:
// settingTipsRecord
// settingToOriginalMsg:
// settingTransferMoney:
// settingTurboModel
// settingTwoFingersEnable:
// settingUnSendTyping:
// settingVideoAnalysis:
// settingVideoDown:
// settingVisualEffectView:
// settingVoiceJiaYiEnable:
// settingVoiceTime
// settingVoiceToMP3:
// settingWelcomeToGroup:
// settingWorkingTime
// shareMediaAction:
// shareTimeLine
// shareTimeLine:
// shareTimeLineEnabled:
// shared
// sharedApplication
// sharedConfig
// sharedInstance
// sharedSession
// sharedToUser:
// shouldMiniTaskGestureBegin
// show
// showAlertWithTitle:message:btnTitle:
// showAlertWithTitle:message:btnTitle:handler:
// showAlertWithTitle:message:btnTitle:handler:btnTitle:handler:
// showDeleteSheet
// showDoneToastWithText:
// showDonotdisturbList
// showErrorToastWithText:
// showExtraDeviceLoginViewControllerWithExtInfo:
// showFailText:
// showFilterFriendVC
// showFilterVC
// showHideFriendListVC
// showHideRoomListVC
// showInView:
// showKeywordDeleteVC
// showLocalNotificationWithInfo:
// showLocalNotificationWithMsg:repeatVibration:
// showLocationSettionVC
// showOKText:
// showQuickReplyMsg:message:timeout:
// showQuickReplyMsgSession:message:
// showSaveResultTip:andText:andDelegate:
// showSelectType
// showSheet
// showTextFieldWithMaxLen:
// showWelcomeContentVC
// showWelcomeVC
// showWithAnimated:
// showWithItemData:tipPoint:
// showWithOptionObj:inViewController:
// sightCaptureMaxDuration
// sightCaptureMaxDurationWithScene:
// silkPlay
// size
// sizeWithAttributes:
// sleepForTimeInterval:
// sortedArrayUsingDescriptors:
// sortedArrayUsingSelector:
// sourceDataPath
// speakUtterance:
// speechOutFileName
// standardUserDefaults
// startAccelerometer
// startAccelerometerUpdatesToQueue:withHandler:
// startAnimation
// startDownloadFavoritesItem:IsPriority:
// startForAddVerifyMsg:parentView:
// startForVerifyOK:parentView:
// startHeight
// startLoading
// startLoadingWithText:
// startLogic
// startReceiveRedEnvelopesLogic:Data:
// state
// statusBarFrame
// statusBarHeight
// statusCode
// stop
// stopAccelerometer
// stopAccelerometerUpdates
// stopAccessingSecurityScopedResource
// stopAnimation
// stopBackground
// stopLoading
// stopLoadingWithFailText:
// stopLoadingWithOKText:
// stopRunTask
// string
// stringByAddingPercentEscapesUsingEncoding:
// stringByAppendingPathComponent:
// stringByAppendingString:
// stringByDeletingLastPathComponent
// stringByDeletingPathExtension
// stringByPaddingToLength:withString:startingAtIndex:
// stringByRemovingPercentEncoding
// stringByReplacingMatchesInString:options:range:withTemplate:
// stringByReplacingOccurrencesOfString:withString:
// stringByTrimmingCharactersInSet:
// stringForKey:
// stringFromDate:
// stringValue
// stringWithCapacity:
// stringWithContentsOfFile:encoding:error:
// stringWithFormat:
// stringWithUTF8String:
// subdataWithRange:
// subpathsAtPath:
// substringFromIndex:
// substringToIndex:
// substringWithRange:
// subviews
// superclass
// superview
// suspend
// svgDataWithName:
// svgImageFromData:
// svgImageNamed:color:
// svgImageNamed:size:color:
// svgImageWithContentsOfFile:
// switchCellForSel:target:title:on:
// switchChange:
// syncSaveFrontUserName
// synchronize
// systemFont
// systemFontOfSize:
// systemFontOfSize:weight:
// systemLocale
// systemMessage
// tabelView
// tableView
// tableView:accessoryButtonTappedForRowWithIndexPath:
// tableView:accessoryTypeForRowWithIndexPath:
// tableView:canEditRowAtIndexPath:
// tableView:canFocusRowAtIndexPath:
// tableView:canMoveRowAtIndexPath:
// tableView:canPerformAction:forRowAtIndexPath:withSender:
// tableView:canPerformPrimaryActionForRowAtIndexPath:
// tableView:cellForRowAtIndexPath:
// tableView:commitEditingStyle:forRowAtIndexPath:
// tableView:contextMenuConfigurationForRowAtIndexPath:point:
// tableView:didBeginMultipleSelectionInteractionAtIndexPath:
// tableView:didDeselectRowAtIndexPath:
// tableView:didEndDisplayingCell:forRowAtIndexPath:
// tableView:didEndDisplayingFooterView:forSection:
// tableView:didEndDisplayingHeaderView:forSection:
// tableView:didEndEditingRowAtIndexPath:
// tableView:didHighlightRowAtIndexPath:
// tableView:didSelectRowAtIndexPath:
// tableView:didUnhighlightRowAtIndexPath:
// tableView:didUpdateFocusInContext:withAnimationCoordinator:
// tableView:editActionsForRowAtIndexPath:
// tableView:editingStyleForRowAtIndexPath:
// tableView:estimatedHeightForFooterInSection:
// tableView:estimatedHeightForHeaderInSection:
// tableView:estimatedHeightForRowAtIndexPath:
// tableView:heightForFooterInSection:
// tableView:heightForHeaderInSection:
// tableView:heightForRowAtIndexPath:
// tableView:indentationLevelForRowAtIndexPath:
// tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:
// tableView:moveRowAtIndexPath:toIndexPath:
// tableView:numberOfRowsInSection:
// tableView:performAction:forRowAtIndexPath:withSender:
// tableView:performPrimaryActionForRowAtIndexPath:
// tableView:previewForDismissingContextMenuWithConfiguration:
// tableView:previewForHighlightingContextMenuWithConfiguration:
// tableView:sectionForSectionIndexTitle:atIndex:
// tableView:selectionFollowsFocusForRowAtIndexPath:
// tableView:shouldBeginMultipleSelectionInteractionAtIndexPath:
// tableView:shouldHighlightRowAtIndexPath:
// tableView:shouldIndentWhileEditingRowAtIndexPath:
// tableView:shouldShowMenuForRowAtIndexPath:
// tableView:shouldSpringLoadRowAtIndexPath:withContext:
// tableView:shouldUpdateFocusInContext:
// tableView:targetIndexPathForMoveFromRowAtIndexPath:toProposedIndexPath:
// tableView:titleForDeleteConfirmationButtonForRowAtIndexPath:
// tableView:titleForFooterInSection:
// tableView:titleForHeaderInSection:
// tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:
// tableView:viewForFooterInSection:
// tableView:viewForHeaderInSection:
// tableView:willBeginEditingRowAtIndexPath:
// tableView:willDeselectRowAtIndexPath:
// tableView:willDisplayCell:forRowAtIndexPath:
// tableView:willDisplayContextMenuWithConfiguration:animator:
// tableView:willDisplayFooterView:forSection:
// tableView:willDisplayHeaderView:forSection:
// tableView:willEndContextMenuInteractionWithConfiguration:animator:
// tableView:willPerformPreviewActionForMenuWithConfiguration:animator:
// tableView:willSelectRowAtIndexPath:
// tableViewDidEndMultipleSelectionInteraction:
// tableViewManager
// tableViewTailColor
// tableview
// tag
// tagList
// tagsSendMessage
// tap
// taskSwitchChange:
// text
// textLabel
// textView
// textView:didBeginFormattingWithViewController:
// textView:didEndFormattingWithViewController:
// textView:editMenuForTextInRange:suggestedActions:
// textView:editMenuForTextInRanges:suggestedActions:
// textView:insertInputSuggestion:
// textView:menuConfigurationForTextItem:defaultMenu:
// textView:primaryActionForTextItem:defaultAction:
// textView:shouldChangeTextInRange:replacementText:
// textView:shouldChangeTextInRanges:replacementText:
// textView:shouldInteractWithTextAttachment:inRange:
// textView:shouldInteractWithTextAttachment:inRange:interaction:
// textView:shouldInteractWithURL:inRange:
// textView:shouldInteractWithURL:inRange:interaction:
// textView:textItemMenuWillDisplayForTextItem:animator:
// textView:textItemMenuWillEndForTextItem:animator:
// textView:willBeginFormattingWithViewController:
// textView:willDismissEditMenuWithAnimator:
// textView:willEndFormattingWithViewController:
// textView:willPresentEditMenuWithAnimator:
// textView:writingToolsIgnoredRangesInEnclosingRange:
// textViewDidBeginEditing:
// textViewDidChange:
// textViewDidChangeSelection:
// textViewDidEndEditing:
// textViewShouldBeginEditing:
// textViewShouldEndEditing:
// textViewWritingToolsDidEnd:
// textViewWritingToolsWillBegin:
// textfieldBackgroundColor
// themeMgr
// themeName
// themePath
// time
// timeIntervalSince1970
// timeLineHiddenUser
// timeLineHiddenUser:
// timeLineHiddenUsers
// timeText
// timer
// timing
// title
// titleArr
// titleLabel
// toast:
// toast:delay:
// tokenWithTime:
// toolActions
// toolBarClearColor
// toolPanelView
// toolView
// topSessions
// topViewControllerOfMainWindow
// totPackets
// tot_len
// total_usage:
// translationInView:
// tryLoadContacts
// trySendTyping:
// turboModel
// type
// uiFromScene
// uiMaxVideoDuration
// uintFromDynamicConfigForKey:
// unsignedIntValue
// unzipFileAtPath:toDestination:overwrite:password:error:
// updateBackgroundImageView:
// updateContact:
// updateContentView:tableViewFrame:
// updateContentView:tableViewFrame:isSearching:isSearchTableView:searchBarText:
// updateFavSetting
// updateForReferMsg:replyContent:
// updateItemUpdateTime:ByLocalId:
// updateMainSessionList
// updateMainSessionListNotify:
// updateNodeStatus
// updatePanelBtn
// updateTabBarBadge
// updateTitleView:
// updateVideoCurrentTime:
// updateWithContact:
// uploadSight:
// useApnsToken
// user
// userDefaults
// userInfo
// userInterfaceLayoutDirection
// userName
// username
// users
// validateAPIKey
// validateFridens
// validateTaskName:
// value
// valueForKey:
// valueForKeyPath:
// valueWithCATransform3D:
// velocityInView:
// videoAnalysisWithURL:success:failure:
// videoDownloadCdnMgrForCategory:
// videoParserWithURL:success:failure:
// videoPath
// videoQualityType
// view
// viewController
// viewControllers
// viewDidDisappear:
// viewDidLayoutSubviews
// viewDidLoad
// viewDidPop:
// viewForZoomingInScrollView:
// viewModel
// viewWillAppear:
// viewWillDisappear:
// viewWillLayoutSubviews
// voiceTime
// voiceWithLanguage:
// whiteColor
// width
// window
// writeToFile:atomically:
// writeToFile:options:error:
// zone
