package com.p001mr.elaris;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int elaris_icon_transparent_background = 0x7f010000;
        public static final int elaris_page_background = 0x7f010001;
    }

    public static final class drawable {
        public static final int ic_motto_pause_circle_outline = 0x7f020000;
        public static final int ic_motto_play_circle_outline = 0x7f020001;
        public static final int icon = 0x7f020002;
        public static final int icon_foreground = 0x7f020003;
    }

    public static final class raw {
        public static final int home_motto_audio = 0x7f030000;
    }

    public static final class string {
        public static final int app_name = 0x7f040000;
        public static final int xposed_description = 0x7f040001;
    }

    public static final class style {
        public static final int AppTheme = 0x7f050000;
    }
}
