package h.Hchat;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int xposed_scope = 0x7f010000;
    }

    public static final class drawable {
        public static final int ic_hchat_copy_link = 0x7f050006;
        public static final int ic_hchat_download_video = 0x7f050007;
        public static final int ic_launcher = 0x7f050008;
        public static final int ic_launcher_round = 0x7f050009;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f060000;
        public static final int accessibility_custom_action_0 = 0x7f060001;
        public static final int accessibility_custom_action_1 = 0x7f060002;
        public static final int accessibility_custom_action_10 = 0x7f060003;
        public static final int accessibility_custom_action_11 = 0x7f060004;
        public static final int accessibility_custom_action_12 = 0x7f060005;
        public static final int accessibility_custom_action_13 = 0x7f060006;
        public static final int accessibility_custom_action_14 = 0x7f060007;
        public static final int accessibility_custom_action_15 = 0x7f060008;
        public static final int accessibility_custom_action_16 = 0x7f060009;
        public static final int accessibility_custom_action_17 = 0x7f06000a;
        public static final int accessibility_custom_action_18 = 0x7f06000b;
        public static final int accessibility_custom_action_19 = 0x7f06000c;
        public static final int accessibility_custom_action_2 = 0x7f06000d;
        public static final int accessibility_custom_action_20 = 0x7f06000e;
        public static final int accessibility_custom_action_21 = 0x7f06000f;
        public static final int accessibility_custom_action_22 = 0x7f060010;
        public static final int accessibility_custom_action_23 = 0x7f060011;
        public static final int accessibility_custom_action_24 = 0x7f060012;
        public static final int accessibility_custom_action_25 = 0x7f060013;
        public static final int accessibility_custom_action_26 = 0x7f060014;
        public static final int accessibility_custom_action_27 = 0x7f060015;
        public static final int accessibility_custom_action_28 = 0x7f060016;
        public static final int accessibility_custom_action_29 = 0x7f060017;
        public static final int accessibility_custom_action_3 = 0x7f060018;
        public static final int accessibility_custom_action_30 = 0x7f060019;
        public static final int accessibility_custom_action_31 = 0x7f06001a;
        public static final int accessibility_custom_action_4 = 0x7f06001b;
        public static final int accessibility_custom_action_5 = 0x7f06001c;
        public static final int accessibility_custom_action_6 = 0x7f06001d;
        public static final int accessibility_custom_action_7 = 0x7f06001e;
        public static final int accessibility_custom_action_8 = 0x7f06001f;
        public static final int accessibility_custom_action_9 = 0x7f060020;
        public static final int action_container = 0x7f060021;
        public static final int action_divider = 0x7f060022;
        public static final int action_image = 0x7f060023;
        public static final int action_text = 0x7f060024;
        public static final int actions = 0x7f060025;
        public static final int adjacent = 0x7f060026;
        public static final int always = 0x7f060027;
        public static final int alwaysAllow = 0x7f060028;
        public static final int alwaysDisallow = 0x7f060029;
        public static final int androidx_compose_ui_view_compose_view_context = 0x7f06002a;
        public static final int androidx_compose_ui_view_composition_context = 0x7f06002b;
        public static final int androidx_window_activity_scope = 0x7f06002c;
        public static final int async = 0x7f06002d;
        public static final int auto_clear_focus_behavior_tag = 0x7f06002e;
        public static final int blocking = 0x7f06002f;
        public static final int bottomToTop = 0x7f060030;
        public static final int chronometer = 0x7f060031;
        public static final int compose_prefetch_scheduler = 0x7f060032;
        public static final int compose_view_saveable_id_tag = 0x7f060033;
        public static final int consume_window_insets_tag = 0x7f060034;
        public static final int dialog_button = 0x7f060035;
        public static final int draggable = 0x7f060036;
        public static final int edit_text_id = 0x7f060037;
        public static final int fixed = 0x7f060038;
        public static final int forever = 0x7f060039;
        public static final int ghost_view = 0x7f06003a;
        public static final int ghost_view_holder = 0x7f06003b;
        public static final int hchat_fake_wallet_balance_target = 0x7f06003c;
        public static final int hchat_message_bubble_original = 0x7f06003d;
        public static final int hchat_message_bubble_target = 0x7f06003e;
        public static final int hchat_message_text_color_applied = 0x7f06003f;
        public static final int hchat_message_text_color_original = 0x7f060040;
        public static final int hchat_message_text_color_value = 0x7f060041;
        public static final int hchat_settings_page_host = 0x7f060042;
        public static final int hchat_sns_anti_recall_label = 0x7f060043;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f060044;
        public static final int hide_ime_id = 0x7f060045;
        public static final int hide_in_inspector_tag = 0x7f060046;
        public static final int icon = 0x7f060047;
        public static final int icon_group = 0x7f060048;
        public static final int info = 0x7f060049;
        public static final int inspection_slot_table_set = 0x7f06004a;
        public static final int is_pooling_container_tag = 0x7f06004b;
        public static final int italic = 0x7f06004c;
        public static final int jumpCut = 0x7f06004d;
        public static final int line1 = 0x7f06004e;
        public static final int line3 = 0x7f06004f;
        public static final int locale = 0x7f060050;
        public static final int ltr = 0x7f060051;
        public static final int never = 0x7f060052;
        public static final int normal = 0x7f060053;
        public static final int notification_background = 0x7f060054;
        public static final int notification_main_column = 0x7f060055;
        public static final int notification_main_column_container = 0x7f060056;
        public static final int parent_matrix = 0x7f060057;
        public static final int pooling_container_listener_holder_tag = 0x7f060058;
        public static final int report_drawn = 0x7f060059;
        public static final int right_icon = 0x7f06005a;
        public static final int right_side = 0x7f06005b;
        public static final int rtl = 0x7f06005c;
        public static final int save_non_transition_alpha = 0x7f06005d;
        public static final int save_overlay_view = 0x7f06005e;
        public static final int systemDefault = 0x7f06005f;
        public static final int tag_accessibility_actions = 0x7f060060;
        public static final int tag_accessibility_clickable_spans = 0x7f060061;
        public static final int tag_accessibility_heading = 0x7f060062;
        public static final int tag_accessibility_pane_title = 0x7f060063;
        public static final int tag_compat_insets_dispatch = 0x7f060064;
        public static final int tag_on_apply_window_listener = 0x7f060065;
        public static final int tag_on_receive_content_listener = 0x7f060066;
        public static final int tag_on_receive_content_mime_types = 0x7f060067;
        public static final int tag_screen_reader_focusable = 0x7f060068;
        public static final int tag_state_description = 0x7f060069;
        public static final int tag_system_bar_state_monitor = 0x7f06006a;
        public static final int tag_transition_group = 0x7f06006b;
        public static final int tag_unhandled_key_event_manager = 0x7f06006c;
        public static final int tag_unhandled_key_listeners = 0x7f06006d;
        public static final int tag_window_insets_animation_callback = 0x7f06006e;
        public static final int text = 0x7f06006f;
        public static final int text2 = 0x7f060070;
        public static final int time = 0x7f060071;
        public static final int title = 0x7f060072;
        public static final int topToBottom = 0x7f060073;
        public static final int transition_clip = 0x7f060074;
        public static final int transition_current_scene = 0x7f060075;
        public static final int transition_image_transform = 0x7f060076;
        public static final int transition_layout_save = 0x7f060077;
        public static final int transition_pause_alpha = 0x7f060078;
        public static final int transition_position = 0x7f060079;
        public static final int transition_scene_layoutid_cache = 0x7f06007a;
        public static final int transition_transform = 0x7f06007b;
        public static final int view_tree_disjoint_parent = 0x7f06007c;
        public static final int view_tree_lifecycle_owner = 0x7f06007d;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f06007e;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f06007f;
        public static final int view_tree_saved_state_registry_owner = 0x7f060080;
        public static final int view_tree_view_model_store_owner = 0x7f060081;
        public static final int wrapped_composition_tag = 0x7f060082;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f090002;
        public static final int app_name = 0x7f090003;
        public static final int default_popup_window_title = 0x7f09000e;
        public static final int in_progress = 0x7f090010;
        public static final int indeterminate = 0x7f090011;
        public static final int not_selected = 0x7f090013;
        public static final int selected = 0x7f090016;
        public static final int state_empty = 0x7f090018;
        public static final int state_off = 0x7f090019;
        public static final int state_on = 0x7f09001a;
        public static final int switch_role = 0x7f09001c;
        public static final int tab = 0x7f09001d;
        public static final int template_percent = 0x7f09001e;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0a0000;
        public static final int FloatingDialogWindowTheme = 0x7f0a0001;
    }
}
