package me.yun.fkwechat;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int xposedscope = 0x7f010000;
    }

    public static final class attr {
        public static final int alpha = 0x7f020002;
        public static final int font = 0x7f02000e;
        public static final int fontProviderAuthority = 0x7f02000f;
        public static final int fontProviderCerts = 0x7f020010;
        public static final int fontProviderFallbackQuery = 0x7f020011;
        public static final int fontProviderFetchStrategy = 0x7f020012;
        public static final int fontProviderFetchTimeout = 0x7f020013;
        public static final int fontProviderPackage = 0x7f020014;
        public static final int fontProviderQuery = 0x7f020015;
        public static final int fontProviderSystemFontFamily = 0x7f020016;
        public static final int fontStyle = 0x7f020017;
        public static final int fontVariationSettings = 0x7f020018;
        public static final int fontWeight = 0x7f020019;
        public static final int lStar = 0x7f02001b;
        public static final int ttcIndex = 0x7f02002f;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f060000;
        public static final int accessibility_custom_action_0 = 0x7f060001;
        public static final int accessibility_custom_action_1 = 0x7f060002;
        public static final int accessibility_custom_action_10 = 0x7f060003;
        public static final int accessibility_custom_action_11 = 0x7f060004;
        public static final int accessibility_custom_action_12 = 0x7f060005;
        public static final int accessibility_custom_action_13 = 0x7f060006;
        public static final int accessibility_custom_action_14 = 0x7f060007;
        public static final int accessibility_custom_action_15 = 0x7f060008;
        public static final int accessibility_custom_action_16 = 0x7f060009;
        public static final int accessibility_custom_action_17 = 0x7f06000a;
        public static final int accessibility_custom_action_18 = 0x7f06000b;
        public static final int accessibility_custom_action_19 = 0x7f06000c;
        public static final int accessibility_custom_action_2 = 0x7f06000d;
        public static final int accessibility_custom_action_20 = 0x7f06000e;
        public static final int accessibility_custom_action_21 = 0x7f06000f;
        public static final int accessibility_custom_action_22 = 0x7f060010;
        public static final int accessibility_custom_action_23 = 0x7f060011;
        public static final int accessibility_custom_action_24 = 0x7f060012;
        public static final int accessibility_custom_action_25 = 0x7f060013;
        public static final int accessibility_custom_action_26 = 0x7f060014;
        public static final int accessibility_custom_action_27 = 0x7f060015;
        public static final int accessibility_custom_action_28 = 0x7f060016;
        public static final int accessibility_custom_action_29 = 0x7f060017;
        public static final int accessibility_custom_action_3 = 0x7f060018;
        public static final int accessibility_custom_action_30 = 0x7f060019;
        public static final int accessibility_custom_action_31 = 0x7f06001a;
        public static final int accessibility_custom_action_4 = 0x7f06001b;
        public static final int accessibility_custom_action_5 = 0x7f06001c;
        public static final int accessibility_custom_action_6 = 0x7f06001d;
        public static final int accessibility_custom_action_7 = 0x7f06001e;
        public static final int accessibility_custom_action_8 = 0x7f06001f;
        public static final int accessibility_custom_action_9 = 0x7f060020;
        public static final int action_container = 0x7f060021;
        public static final int action_divider = 0x7f060022;
        public static final int action_image = 0x7f060023;
        public static final int action_text = 0x7f060024;
        public static final int actions = 0x7f060025;
        public static final int adjacent = 0x7f060026;
        public static final int always = 0x7f060027;
        public static final int alwaysAllow = 0x7f060028;
        public static final int alwaysDisallow = 0x7f060029;
        public static final int androidx_compose_ui_view_composition_context = 0x7f06002a;
        public static final int androidx_window_activity_scope = 0x7f06002b;
        public static final int async = 0x7f06002c;
        public static final int auto_clear_focus_behavior_tag = 0x7f06002d;
        public static final int blocking = 0x7f06002e;
        public static final int bottomToTop = 0x7f06002f;
        public static final int chronometer = 0x7f060030;
        public static final int coil3_request_manager = 0x7f060031;
        public static final int compose_prefetch_scheduler = 0x7f060032;
        public static final int compose_view_saveable_id_tag = 0x7f060033;
        public static final int consume_window_insets_tag = 0x7f060034;
        public static final int dialog_button = 0x7f060035;
        public static final int draggable = 0x7f060036;
        public static final int edit_text_id = 0x7f060037;
        public static final int fixed = 0x7f060038;
        public static final int forever = 0x7f060039;
        public static final int ghost_view = 0x7f06003a;
        public static final int ghost_view_holder = 0x7f06003b;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f06003c;
        public static final int hide_ime_id = 0x7f06003d;
        public static final int hide_in_inspector_tag = 0x7f06003e;
        public static final int icon = 0x7f06003f;
        public static final int icon_group = 0x7f060040;
        public static final int info = 0x7f060041;
        public static final int inspection_slot_table_set = 0x7f060042;
        public static final int is_pooling_container_tag = 0x7f060043;
        public static final int italic = 0x7f060044;
        public static final int jumpCut = 0x7f060045;
        public static final int line1 = 0x7f060046;
        public static final int line3 = 0x7f060047;
        public static final int locale = 0x7f060048;
        public static final int ltr = 0x7f060049;
        public static final int never = 0x7f06004a;
        public static final int normal = 0x7f06004b;
        public static final int notification_background = 0x7f06004c;
        public static final int notification_main_column = 0x7f06004d;
        public static final int notification_main_column_container = 0x7f06004e;
        public static final int parent_matrix = 0x7f06004f;
        public static final int pooling_container_listener_holder_tag = 0x7f060050;
        public static final int report_drawn = 0x7f060051;
        public static final int right_icon = 0x7f060052;
        public static final int right_side = 0x7f060053;
        public static final int rtl = 0x7f060054;
        public static final int save_non_transition_alpha = 0x7f060055;
        public static final int save_overlay_view = 0x7f060056;
        public static final int systemDefault = 0x7f060057;
        public static final int tag_accessibility_actions = 0x7f060058;
        public static final int tag_accessibility_clickable_spans = 0x7f060059;
        public static final int tag_accessibility_heading = 0x7f06005a;
        public static final int tag_accessibility_pane_title = 0x7f06005b;
        public static final int tag_compat_insets_dispatch = 0x7f06005c;
        public static final int tag_on_apply_window_listener = 0x7f06005d;
        public static final int tag_on_receive_content_listener = 0x7f06005e;
        public static final int tag_on_receive_content_mime_types = 0x7f06005f;
        public static final int tag_screen_reader_focusable = 0x7f060060;
        public static final int tag_state_description = 0x7f060061;
        public static final int tag_system_bar_state_monitor = 0x7f060062;
        public static final int tag_transition_group = 0x7f060063;
        public static final int tag_unhandled_key_event_manager = 0x7f060064;
        public static final int tag_unhandled_key_listeners = 0x7f060065;
        public static final int tag_window_insets_animation_callback = 0x7f060066;
        public static final int text = 0x7f060067;
        public static final int text2 = 0x7f060068;
        public static final int time = 0x7f060069;
        public static final int title = 0x7f06006a;
        public static final int topToBottom = 0x7f06006b;
        public static final int transition_clip = 0x7f06006c;
        public static final int transition_current_scene = 0x7f06006d;
        public static final int transition_image_transform = 0x7f06006e;
        public static final int transition_layout_save = 0x7f06006f;
        public static final int transition_pause_alpha = 0x7f060070;
        public static final int transition_position = 0x7f060071;
        public static final int transition_scene_layoutid_cache = 0x7f060072;
        public static final int transition_transform = 0x7f060073;
        public static final int view_tree_disjoint_parent = 0x7f060074;
        public static final int view_tree_lifecycle_owner = 0x7f060075;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f060076;
        public static final int view_tree_saved_state_registry_owner = 0x7f060077;
        public static final int view_tree_view_model_store_owner = 0x7f060078;
        public static final int wrapped_composition_tag = 0x7f060079;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f090000;
    }

    public static final class string {
        public static final int androidx_compose_ui_autofill = 0x7f0a0000;
        public static final int androidx_startup = 0x7f0a0001;
        public static final int app_description = 0x7f0a0002;
        public static final int app_name = 0x7f0a0003;
        public static final int autofill = 0x7f0a0004;
        public static final int default_error_message = 0x7f0a000e;
        public static final int default_popup_window_title = 0x7f0a000f;
        public static final int in_progress = 0x7f0a0011;
        public static final int indeterminate = 0x7f0a0012;
        public static final int m3c_date_input_headline = 0x7f0a0018;
        public static final int m3c_date_input_headline_description = 0x7f0a0019;
        public static final int m3c_date_input_invalid_for_pattern = 0x7f0a001a;
        public static final int m3c_date_input_invalid_not_allowed = 0x7f0a001b;
        public static final int m3c_date_input_invalid_year_range = 0x7f0a001c;
        public static final int m3c_date_input_label = 0x7f0a001d;
        public static final int m3c_date_input_no_input_description = 0x7f0a001e;
        public static final int m3c_date_input_title = 0x7f0a001f;
        public static final int m3c_date_picker_headline = 0x7f0a0020;
        public static final int m3c_date_picker_headline_description = 0x7f0a0021;
        public static final int m3c_date_picker_navigate_to_year_description = 0x7f0a0022;
        public static final int m3c_date_picker_no_selection_description = 0x7f0a0023;
        public static final int m3c_date_picker_switch_to_calendar_mode = 0x7f0a0026;
        public static final int m3c_date_picker_switch_to_day_selection = 0x7f0a0027;
        public static final int m3c_date_picker_switch_to_input_mode = 0x7f0a0028;
        public static final int m3c_date_picker_switch_to_next_month = 0x7f0a0029;
        public static final int m3c_date_picker_switch_to_previous_month = 0x7f0a002a;
        public static final int m3c_date_picker_switch_to_year_selection = 0x7f0a002b;
        public static final int m3c_date_picker_title = 0x7f0a002c;
        public static final int m3c_date_picker_today_description = 0x7f0a002d;
        public static final int m3c_date_picker_year_picker_pane_title = 0x7f0a002e;
        public static final int m3c_date_range_picker_day_in_range = 0x7f0a0031;
        public static final int m3c_date_range_picker_end_headline = 0x7f0a0032;
        public static final int m3c_date_range_picker_start_headline = 0x7f0a0035;
        public static final int m3c_dialog = 0x7f0a0037;
        public static final int m3c_time_picker_am = 0x7f0a0042;
        public static final int m3c_time_picker_hour_24h_suffix = 0x7f0a0045;
        public static final int m3c_time_picker_hour_selection = 0x7f0a0046;
        public static final int m3c_time_picker_hour_suffix = 0x7f0a0047;
        public static final int m3c_time_picker_minute_selection = 0x7f0a004a;
        public static final int m3c_time_picker_minute_suffix = 0x7f0a004b;
        public static final int m3c_time_picker_period_toggle_description = 0x7f0a004d;
        public static final int m3c_time_picker_pm = 0x7f0a004e;
        public static final int not_selected = 0x7f0a0056;
        public static final int range_end = 0x7f0a0057;
        public static final int range_start = 0x7f0a0058;
        public static final int selected = 0x7f0a0059;
        public static final int state_empty = 0x7f0a005b;
        public static final int state_off = 0x7f0a005c;
        public static final int state_on = 0x7f0a005d;
        public static final int switch_role = 0x7f0a005f;
        public static final int tab = 0x7f0a0060;
        public static final int template_percent = 0x7f0a0061;
        public static final int tooltip_description = 0x7f0a0062;
        public static final int tooltip_label = 0x7f0a0063;
    }

    public static final class style {
        public static final int DialogWindowTheme = 0x7f0b0000;
        public static final int FloatingDialogWindowTheme = 0x7f0b0003;
        public static final int Theme_FkWeChat = 0x7f0b0009;
    }
}
