package bsh;

/* JADX INFO: compiled from: r8-map-id-410253dec230a6d44f261a3a84880494196f082735db3c71240f387861686496 */
/* JADX INFO: loaded from: classes.dex */
public interface ParserConstants {
    public static final int ABSTRACT = 11;
    public static final int ANDASSIGN = 128;
    public static final int ANDASSIGNX = 129;
    public static final int ARROW = 144;
    public static final int ASSIGN = 85;
    public static final int BANG = 90;
    public static final int BINARY_LITERAL = 65;
    public static final int BIT_AND = 108;
    public static final int BIT_ANDX = 109;
    public static final int BIT_OR = 110;
    public static final int BIT_ORX = 111;
    public static final int BOOLEAN = 12;
    public static final int BOOL_AND = 100;
    public static final int BOOL_ANDX = 101;
    public static final int BOOL_OR = 98;
    public static final int BOOL_ORX = 99;
    public static final int BREAK = 13;
    public static final int BYTE = 15;
    public static final int CASE = 16;
    public static final int CATCH = 17;
    public static final int CHAR = 18;
    public static final int CHARACTER_LITERAL = 70;
    public static final int CLASS = 14;
    public static final int COLON = 150;
    public static final int COLON_COLON = 151;
    public static final int COMMA = 83;
    public static final int CONST = 19;
    public static final int CONTINUE = 20;
    public static final int DECIMAL_LITERAL = 63;
    public static final int DECR = 103;
    public static final int DEFAULT = 0;
    public static final int DIGIT = 75;
    public static final int DO = 22;
    public static final int DOT = 84;
    public static final int DOUBLE = 23;
    public static final int ELLIPSIS = 152;
    public static final int ELSE = 24;
    public static final int ELVIS = 148;
    public static final int ENUM = 25;
    public static final int EOF = 0;
    public static final int EQ = 92;
    public static final int ESCAPE = 69;
    public static final int EXPONENT = 68;
    public static final int EXTENDS = 26;
    public static final int FALSE = 27;
    public static final int FINAL = 28;
    public static final int FINALLY = 29;
    public static final int FLOAT = 30;
    public static final int FLOATING_POINT_LITERAL = 67;
    public static final int FOR = 31;
    public static final int GE = 95;
    public static final int GEX = 96;
    public static final int GOTO = 32;
    public static final int GT = 86;
    public static final int GTX = 87;
    public static final int HASH_BANG_COMMENT = 9;
    public static final int HEX_LITERAL = 64;
    public static final int HOOK = 149;
    public static final int IDENTIFIER = 73;
    public static final int IF = 33;
    public static final int IMPLEMENTS = 34;
    public static final int IMPORT = 35;
    public static final int INCR = 102;
    public static final int INSTANCEOF = 36;
    public static final int INT = 37;
    public static final int INTEGER_LITERAL = 62;
    public static final int INTERFACE = 38;
    public static final int LBRACE = 78;
    public static final int LBRACKET = 80;
    public static final int LE = 93;
    public static final int LETTER = 74;
    public static final int LEX = 94;
    public static final int LONG = 39;
    public static final int LONG_STRING_LITERAL = 72;
    public static final int LPAREN = 76;
    public static final int LSHIFT = 118;
    public static final int LSHIFTASSIGN = 138;
    public static final int LSHIFTASSIGNX = 139;
    public static final int LSHIFTX = 119;
    public static final int LT = 88;
    public static final int LTX = 89;
    public static final int MINUS = 105;
    public static final int MINUSASSIGN = 125;
    public static final int MOD = 114;
    public static final int MODASSIGN = 134;
    public static final int MODASSIGNX = 135;
    public static final int MODX = 115;
    public static final int MULTI_LINE_COMMENT = 10;
    public static final int NATIVE = 40;
    public static final int NE = 97;
    public static final int NEW = 41;
    public static final int NONPRINTABLE = 6;
    public static final int NULL = 42;
    public static final int NULLCOALESCE = 147;
    public static final int NULLCOALESCEASSIGN = 146;
    public static final int OCTAL_LITERAL = 66;
    public static final int ORASSIGN = 130;
    public static final int ORASSIGNX = 131;
    public static final int PACKAGE = 43;
    public static final int PLUS = 104;
    public static final int PLUSASSIGN = 124;
    public static final int POWER = 116;
    public static final int POWERASSIGN = 136;
    public static final int POWERASSIGNX = 137;
    public static final int POWERX = 117;
    public static final int PRIVATE = 44;
    public static final int PROTECTED = 45;
    public static final int PUBLIC = 46;
    public static final int RBRACE = 79;
    public static final int RBRACKET = 81;
    public static final int RETURN = 47;
    public static final int RPAREN = 77;
    public static final int RSIGNEDSHIFT = 120;
    public static final int RSIGNEDSHIFTASSIGN = 140;
    public static final int RSIGNEDSHIFTASSIGNX = 141;
    public static final int RSIGNEDSHIFTX = 121;
    public static final int RUNSIGNEDSHIFT = 122;
    public static final int RUNSIGNEDSHIFTASSIGN = 142;
    public static final int RUNSIGNEDSHIFTASSIGNX = 143;
    public static final int RUNSIGNEDSHIFTX = 123;
    public static final int SEMICOLON = 82;
    public static final int SHORT = 48;
    public static final int SINGLE_LINE_COMMENT = 8;
    public static final int SLASH = 107;
    public static final int SLASHASSIGN = 127;
    public static final int SPACESHIP = 145;
    public static final int STAR = 106;
    public static final int STARASSIGN = 126;
    public static final int STATIC = 49;
    public static final int STRICTFP = 50;
    public static final int STRING_LITERAL = 71;
    public static final int SWITCH = 51;
    public static final int SYNCHRONIZED = 52;
    public static final int THROW = 54;
    public static final int THROWS = 55;
    public static final int TILDE = 91;
    public static final int TRANSIENT = 53;
    public static final int TRUE = 56;
    public static final int TRY = 57;
    public static final int TYPE_PARAMATERS = 7;
    public static final int VOID = 58;
    public static final int VOLATILE = 59;
    public static final int WHEN = 60;
    public static final int WHILE = 61;
    public static final int XOR = 112;
    public static final int XORASSIGN = 132;
    public static final int XORASSIGNX = 133;
    public static final int XORX = 113;
    public static final int _DEFAULT = 21;
    public static final java.lang.String[] tokenImage = null;

    static {
            java.lang.String r154 = "\"?.\""
            java.lang.String r155 = "\"default:\""
            java.lang.String r1 = "<EOF>"
            java.lang.String r2 = "\" \""
            java.lang.String r3 = "\"\\t\""
            java.lang.String r4 = "\"\\r\""
            java.lang.String r5 = "\"\\f\""
            java.lang.String r6 = "\"\\n\""
            java.lang.String r7 = "<NONPRINTABLE>"
            java.lang.String r8 = "<TYPE_PARAMATERS>"
            java.lang.String r9 = "<SINGLE_LINE_COMMENT>"
            java.lang.String r10 = "<HASH_BANG_COMMENT>"
            java.lang.String r11 = "<MULTI_LINE_COMMENT>"
            java.lang.String r12 = "\"abstract\""
            java.lang.String r13 = "\"boolean\""
            java.lang.String r14 = "\"break\""
            java.lang.String r15 = "\"class\""
            java.lang.String r16 = "\"byte\""
            java.lang.String r17 = "\"case\""
            java.lang.String r18 = "\"catch\""
            java.lang.String r19 = "\"char\""
            java.lang.String r20 = "\"const\""
            java.lang.String r21 = "\"continue\""
            java.lang.String r22 = "\"default\""
            java.lang.String r23 = "\"do\""
            java.lang.String r24 = "\"double\""
            java.lang.String r25 = "\"else\""
            java.lang.String r26 = "\"enum\""
            java.lang.String r27 = "\"extends\""
            java.lang.String r28 = "\"false\""
            java.lang.String r29 = "\"final\""
            java.lang.String r30 = "\"finally\""
            java.lang.String r31 = "\"float\""
            java.lang.String r32 = "\"for\""
            java.lang.String r33 = "\"goto\""
            java.lang.String r34 = "\"if\""
            java.lang.String r35 = "\"implements\""
            java.lang.String r36 = "\"import\""
            java.lang.String r37 = "\"instanceof\""
            java.lang.String r38 = "\"int\""
            java.lang.String r39 = "\"interface\""
            java.lang.String r40 = "\"long\""
            java.lang.String r41 = "\"native\""
            java.lang.String r42 = "\"new\""
            java.lang.String r43 = "\"null\""
            java.lang.String r44 = "\"package\""
            java.lang.String r45 = "\"private\""
            java.lang.String r46 = "\"protected\""
            java.lang.String r47 = "\"public\""
            java.lang.String r48 = "\"return\""
            java.lang.String r49 = "\"short\""
            java.lang.String r50 = "\"static\""
            java.lang.String r51 = "\"strictfp\""
            java.lang.String r52 = "\"switch\""
            java.lang.String r53 = "\"synchronized\""
            java.lang.String r54 = "\"transient\""
            java.lang.String r55 = "\"throw\""
            java.lang.String r56 = "\"throws\""
            java.lang.String r57 = "\"true\""
            java.lang.String r58 = "\"try\""
            java.lang.String r59 = "\"void\""
            java.lang.String r60 = "\"volatile\""
            java.lang.String r61 = "\"when\""
            java.lang.String r62 = "\"while\""
            java.lang.String r63 = "<INTEGER_LITERAL>"
            java.lang.String r64 = "<DECIMAL_LITERAL>"
            java.lang.String r65 = "<HEX_LITERAL>"
            java.lang.String r66 = "<BINARY_LITERAL>"
            java.lang.String r67 = "<OCTAL_LITERAL>"
            java.lang.String r68 = "<FLOATING_POINT_LITERAL>"
            java.lang.String r69 = "<EXPONENT>"
            java.lang.String r70 = "<ESCAPE>"
            java.lang.String r71 = "<CHARACTER_LITERAL>"
            java.lang.String r72 = "<STRING_LITERAL>"
            java.lang.String r73 = "<LONG_STRING_LITERAL>"
            java.lang.String r74 = "<IDENTIFIER>"
            java.lang.String r75 = "<LETTER>"
            java.lang.String r76 = "<DIGIT>"
            java.lang.String r77 = "\"(\""
            java.lang.String r78 = "\")\""
            java.lang.String r79 = "\"{\""
            java.lang.String r80 = "\"}\""
            java.lang.String r81 = "\"[\""
            java.lang.String r82 = "\"]\""
            java.lang.String r83 = "\";\""
            java.lang.String r84 = "\",\""
            java.lang.String r85 = "\".\""
            java.lang.String r86 = "\"=\""
            java.lang.String r87 = "\">\""
            java.lang.String r88 = "\"@gt\""
            java.lang.String r89 = "\"<\""
            java.lang.String r90 = "\"@lt\""
            java.lang.String r91 = "\"!\""
            java.lang.String r92 = "\"~\""
            java.lang.String r93 = "\"==\""
            java.lang.String r94 = "\"<=\""
            java.lang.String r95 = "\"@lteq\""
            java.lang.String r96 = "\">=\""
            java.lang.String r97 = "\"@gteq\""
            java.lang.String r98 = "\"!=\""
            java.lang.String r99 = "\"||\""
            java.lang.String r100 = "\"@or\""
            java.lang.String r101 = "\"&&\""
            java.lang.String r102 = "\"@and\""
            java.lang.String r103 = "\"++\""
            java.lang.String r104 = "\"--\""
            java.lang.String r105 = "\"+\""
            java.lang.String r106 = "\"-\""
            java.lang.String r107 = "\"*\""
            java.lang.String r108 = "\"/\""
            java.lang.String r109 = "\"&\""
            java.lang.String r110 = "\"@bitwise_and\""
            java.lang.String r111 = "\"|\""
            java.lang.String r112 = "\"@bitwise_or\""
            java.lang.String r113 = "\"^\""
            java.lang.String r114 = "\"@bitwise_xor\""
            java.lang.String r115 = "\"%\""
            java.lang.String r116 = "\"@mod\""
            java.lang.String r117 = "\"**\""
            java.lang.String r118 = "\"@pow\""
            java.lang.String r119 = "\"<<\""
            java.lang.String r120 = "\"@left_shift\""
            java.lang.String r121 = "\">>\""
            java.lang.String r122 = "\"@right_shift\""
            java.lang.String r123 = "\">>>\""
            java.lang.String r124 = "\"@right_unsigned_shift\""
            java.lang.String r125 = "\"+=\""
            java.lang.String r126 = "\"-=\""
            java.lang.String r127 = "\"*=\""
            java.lang.String r128 = "\"/=\""
            java.lang.String r129 = "\"&=\""
            java.lang.String r130 = "\"@and_assign\""
            java.lang.String r131 = "\"|=\""
            java.lang.String r132 = "\"@or_assign\""
            java.lang.String r133 = "\"^=\""
            java.lang.String r134 = "\"@xor_assign\""
            java.lang.String r135 = "\"%=\""
            java.lang.String r136 = "\"@mod_assign\""
            java.lang.String r137 = "\"**=\""
            java.lang.String r138 = "\"@pow_assign\""
            java.lang.String r139 = "\"<<=\""
            java.lang.String r140 = "\"@left_shift_assign\""
            java.lang.String r141 = "\">>=\""
            java.lang.String r142 = "\"@right_shift_assign\""
            java.lang.String r143 = "\">>>=\""
            java.lang.String r144 = "\"@right_unsigned_shift_assign\""
            java.lang.String r145 = "\"->\""
            java.lang.String r146 = "\"<=>\""
            java.lang.String r147 = "\"??=\""
            java.lang.String r148 = "\"??\""
            java.lang.String r149 = "\"?:\""
            java.lang.String r150 = "\"?\""
            java.lang.String r151 = "\":\""
            java.lang.String r152 = "\"::\""
            java.lang.String r153 = "\"...\""
            java.lang.String[] r0 = new java.lang.String[]{r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31, r32, r33, r34, r35, r36, r37, r38, r39, r40, r41, r42, r43, r44, r45, r46, r47, r48, r49, r50, r51, r52, r53, r54, r55, r56, r57, r58, r59, r60, r61, r62, r63, r64, r65, r66, r67, r68, r69, r70, r71, r72, r73, r74, r75, r76, r77, r78, r79, r80, r81, r82, r83, r84, r85, r86, r87, r88, r89, r90, r91, r92, r93, r94, r95, r96, r97, r98, r99, r100, r101, r102, r103, r104, r105, r106, r107, r108, r109, r110, r111, r112, r113, r114, r115, r116, r117, r118, r119, r120, r121, r122, r123, r124, r125, r126, r127, r128, r129, r130, r131, r132, r133, r134, r135, r136, r137, r138, r139, r140, r141, r142, r143, r144, r145, r146, r147, r148, r149, r150, r151, r152, r153, r154, r155}
            bsh.ParserConstants.tokenImage = r0
            return
    }
}
