# -*- coding: utf-8 -*-
from com.pnfsoftware.jeb.client.api import IScript
from com.pnfsoftware.jeb.core.units import INativeCodeUnit
from com.pnfsoftware.jeb.core.units.code.asm.decompiler import NativeDecompilerExporter
from java.io import File
import os
import traceback
import codecs


class JebExportWCGlass(IScript):
    def run(self, ctx):
        # Keep paths relative here. Jython 2's os.path may corrupt non-ASCII
        # characters in the Windows working-directory prefix.
        root = 'WCGlass_restored'
        outdir = os.path.join(root, '01_jeb_decompiled_c')
        if not os.path.isdir(outdir):
            os.makedirs(outdir)
        logpath = os.path.join(root, 'jeb_export_status.txt')

        def log(message):
            f = codecs.open(logpath, 'a', 'utf-8')
            f.write(unicode(message) + u'\n')
            f.close()

        try:
            log('START: JEB native analysis and C source export')
            project = ctx.getMainProject()
            log('Project: %s' % project)
            code_units = project.findUnits(INativeCodeUnit)
            log('Native code units: %d' % len(code_units))
            for index, unit in enumerate(code_units):
                log('Unit[%d]: %s / %s' % (index, unit.getName(), unit.getClass()))
                if not unit.isInitialAnalysisDone():
                    log('Performing initial analysis...')
                    unit.performInitialAnalysis()
                log('Methods=%d internal=%d classes=%d strings=%d' % (
                    len(unit.getMethods()), len(unit.getInternalMethods()),
                    len(unit.getClasses()), len(unit.getStrings())))
                decompiler = unit.getDecompiler()
                if decompiler is None:
                    log('No native decompiler returned for this unit')
                    continue
                log('Decompiler: %s' % decompiler.getClass())
                unit_out = outdir if len(code_units) == 1 else os.path.join(outdir, 'unit_%d' % index)
                exporter = NativeDecompilerExporter(decompiler)
                exporter.setOutputFolder(File(unit_out), True)
                exporter.setHeaderString('/* WCGlass.dylib restored pseudo-source generated by JEB */\n')
                exporter.setMethodTimeout(300000L)
                exporter.setTotalTimeout(43200000L)
                exporter.setDiscardDecompiledItemsAfterProcessing(True)
                ok = exporter.export()
                log('Export done: success=%s files=%s errors=%d' % (
                    ok, exporter.getGeneratedFileCount(), len(exporter.getErrors())))
                if exporter.getErrors():
                    ef = codecs.open(os.path.join(root, 'jeb_export_errors.txt'), 'w', 'utf-8')
                    for key, value in exporter.getErrors().entrySet():
                        ef.write(unicode('%s\t%s\n' % (key, value)))
                    ef.close()
            log('END: JEB export completed')
        except Exception, e:
            log('ERROR: %s' % e)
            log(traceback.format_exc())
            raise
