package defpackage;

/* JADX INFO: compiled from: r8-map-id-1fdf33e95b2c98e9913e3f754a675e277db58555c92b1678ad704849f4b90bb4 */
/* JADX INFO: loaded from: classes.dex */
public abstract class i63 {
    public static final long A;
    public static final long A0;
    public static final so0 A1;
    public static final long B;
    public static final im0 B0;
    public static final long B1;
    public static final long C;
    public static final so0 C0;
    public static final long C1;
    public static final im0 D;
    public static final long D0;
    public static final long D1;
    public static final so0 E;
    public static final long E0;
    public static final im0 E1;
    public static final long F;
    public static final long F0;
    public static final so0 F1;
    public static final long G;
    public static final im0 G0;
    public static final long G1;
    public static final long H;
    public static final so0 H0;
    public static final long H1;
    public static final im0 I;
    public static final long I0;
    public static final long I1;
    public static final so0 J;
    public static final long J0;
    public static final im0 J1;
    public static final long K;
    public static final long K0;
    public static final so0 K1;
    public static final long L;
    public static final im0 L0;
    public static final long L1;
    public static final long M;
    public static final so0 M0;
    public static final long M1;
    public static final im0 N;
    public static final long N0;
    public static final long N1;
    public static final so0 O;
    public static final long O0;
    public static final im0 O1;
    public static final long P;
    public static final long P0;
    public static final so0 P1;
    public static final long Q;
    public static final im0 Q0;
    public static final long Q1;
    public static final long R;
    public static final so0 R0;
    public static final long R1;
    public static final im0 S;
    public static final long S0;
    public static final long S1;
    public static final so0 T;
    public static final long T0;
    public static final im0 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final im0 V0;
    public static final long W;
    public static final so0 W0;
    public static final im0 X;
    public static final long X0;
    public static final so0 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final so0 a;
    public static final long a0;
    public static final im0 a1;
    public static final long b;
    public static final long b0;
    public static final so0 b1;
    public static final long c;
    public static final im0 c0;
    public static final long c1;
    public static final long d;
    public static final so0 d0;
    public static final long d1;
    public static final im0 e;
    public static final long e0;
    public static final long e1;
    public static final so0 f;
    public static final long f0;
    public static final im0 f1;
    public static final long g;
    public static final long g0;
    public static final so0 g1;
    public static final long h;
    public static final im0 h0;
    public static final long h1;
    public static final long i;
    public static final so0 i0;
    public static final long i1;
    public static final im0 j;
    public static final long j0;
    public static final long j1;
    public static final so0 k;
    public static final long k0;
    public static final im0 k1;
    public static final long l;
    public static final long l0;
    public static final so0 l1;
    public static final long m;
    public static final im0 m0;
    public static final long m1;
    public static final long n;
    public static final so0 n0;
    public static final long n1;
    public static final im0 o;
    public static final long o0;
    public static final long o1;
    public static final so0 p;
    public static final long p0;
    public static final im0 p1;
    public static final long q;
    public static final long q0;
    public static final so0 q1;
    public static final long r;
    public static final im0 r0;
    public static final long r1;
    public static final long s;
    public static final so0 s0;
    public static final long s1;
    public static final im0 t;
    public static final long t0;
    public static final long t1;
    public static final so0 u;
    public static final long u0;
    public static final im0 u1;
    public static final long v;
    public static final long v0;
    public static final so0 v1;
    public static final long w;
    public static final im0 w0;
    public static final long w1;
    public static final long x;
    public static final so0 x0;
    public static final long x1;
    public static final im0 y;
    public static final long y0;
    public static final long y1;
    public static final so0 z;
    public static final long z0;
    public static final im0 z1;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    static {
        im0 im0Var = n63.a;
        so0 so0Var = mx2.b;
        a = so0Var;
        b = rg3.C(24.0d);
        c = rg3.D(16);
        d = rg3.C(0.5d);
        im0 im0Var2 = n63.c;
        e = im0Var2;
        f = so0Var;
        g = rg3.C(20.0d);
        h = rg3.D(14);
        i = rg3.C(0.2d);
        j = im0Var2;
        k = so0Var;
        l = rg3.C(16.0d);
        m = rg3.D(12);
        n = rg3.C(0.4d);
        o = im0Var2;
        p = so0Var;
        q = rg3.C(64.0d);
        r = rg3.D(57);
        long jC = rg3.C(0.2d);
        q13[] q13VarArr = p13.b;
        long j2 = jC & 1095216660480L;
        if (j2 == 0) {
            mz0.a("Cannot perform operation for Unspecified type.");
        }
        s = rg3.I(-p13.c(jC), j2);
        t = im0Var2;
        u = so0Var;
        v = rg3.C(52.0d);
        w = rg3.D(45);
        x = rg3.C(0.0d);
        y = im0Var2;
        z = so0Var;
        A = rg3.C(44.0d);
        B = rg3.D(36);
        C = rg3.C(0.0d);
        D = im0Var2;
        E = so0Var;
        F = rg3.C(40.0d);
        G = rg3.D(32);
        H = rg3.C(0.0d);
        I = im0Var2;
        J = so0Var;
        K = rg3.C(36.0d);
        L = rg3.D(28);
        M = rg3.C(0.0d);
        N = im0Var2;
        O = so0Var;
        P = rg3.C(32.0d);
        Q = rg3.D(24);
        R = rg3.C(0.0d);
        S = im0Var2;
        T = so0Var;
        U = rg3.C(20.0d);
        V = rg3.D(14);
        W = rg3.C(0.1d);
        im0 im0Var3 = n63.b;
        X = im0Var3;
        Y = so0Var;
        Z = rg3.C(16.0d);
        a0 = rg3.D(12);
        b0 = rg3.C(0.5d);
        c0 = im0Var3;
        d0 = so0Var;
        e0 = rg3.C(16.0d);
        f0 = rg3.D(11);
        g0 = rg3.C(0.5d);
        h0 = im0Var3;
        i0 = so0Var;
        j0 = rg3.C(28.0d);
        k0 = rg3.D(22);
        l0 = rg3.C(0.0d);
        m0 = im0Var2;
        n0 = so0Var;
        o0 = rg3.C(24.0d);
        p0 = rg3.D(16);
        q0 = rg3.C(0.2d);
        r0 = im0Var3;
        s0 = so0Var;
        t0 = rg3.C(20.0d);
        u0 = rg3.D(14);
        v0 = rg3.C(0.1d);
        w0 = im0Var3;
        x0 = so0Var;
        y0 = rg3.C(24.0d);
        z0 = rg3.D(16);
        A0 = rg3.C(0.15d);
        B0 = im0Var3;
        C0 = so0Var;
        D0 = rg3.C(20.0d);
        E0 = rg3.D(14);
        F0 = rg3.C(0.25d);
        G0 = im0Var3;
        H0 = so0Var;
        I0 = rg3.C(16.0d);
        J0 = rg3.D(12);
        K0 = rg3.C(0.4d);
        L0 = im0Var3;
        M0 = so0Var;
        N0 = rg3.C(64.0d);
        O0 = rg3.D(57);
        P0 = rg3.D(0);
        Q0 = im0Var3;
        R0 = so0Var;
        S0 = rg3.C(52.0d);
        T0 = rg3.D(45);
        U0 = rg3.D(0);
        V0 = im0Var3;
        W0 = so0Var;
        X0 = rg3.C(44.0d);
        Y0 = rg3.D(36);
        Z0 = rg3.D(0);
        a1 = im0Var3;
        b1 = so0Var;
        c1 = rg3.C(40.0d);
        d1 = rg3.D(32);
        e1 = rg3.D(0);
        f1 = im0Var3;
        g1 = so0Var;
        h1 = rg3.C(36.0d);
        i1 = rg3.D(28);
        j1 = rg3.D(0);
        k1 = im0Var3;
        l1 = so0Var;
        m1 = rg3.C(32.0d);
        n1 = rg3.D(24);
        o1 = rg3.D(0);
        p1 = im0Var3;
        q1 = so0Var;
        r1 = rg3.C(20.0d);
        s1 = rg3.D(14);
        t1 = rg3.C(0.1d);
        im0 im0Var4 = n63.a;
        u1 = im0Var4;
        v1 = so0Var;
        w1 = rg3.C(16.0d);
        x1 = rg3.D(12);
        y1 = rg3.C(0.5d);
        z1 = im0Var4;
        A1 = so0Var;
        B1 = rg3.C(16.0d);
        C1 = rg3.D(11);
        D1 = rg3.C(0.5d);
        E1 = im0Var4;
        F1 = so0Var;
        G1 = rg3.C(28.0d);
        H1 = rg3.D(22);
        I1 = rg3.D(0);
        J1 = im0Var3;
        K1 = so0Var;
        L1 = rg3.C(24.0d);
        M1 = rg3.D(16);
        N1 = rg3.C(0.15d);
        O1 = im0Var4;
        P1 = so0Var;
        Q1 = rg3.C(20.0d);
        R1 = rg3.D(14);
        S1 = rg3.C(0.1d);
        T1 = im0Var4;
    }
}
