package defpackage;

/* JADX INFO: compiled from: r8-map-id-1fdf33e95b2c98e9913e3f754a675e277db58555c92b1678ad704849f4b90bb4 */
/* JADX INFO: loaded from: classes.dex */
public abstract class ku {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    static {
        long j2 = qw1.q;
        a = j2;
        b = qw1.f;
        c = qw1.d;
        d = qw1.m;
        e = qw1.H;
        long j3 = qw1.s;
        f = j3;
        g = j3;
        h = qw1.c;
        i = qw1.g;
        j = qw1.F;
        long j4 = qw1.J;
        k = j4;
        l = qw1.D;
        long j5 = qw1.G;
        m = j5;
        n = qw1.M;
        long j6 = qw1.Q;
        o = j6;
        p = qw1.K;
        long j7 = qw1.N;
        q = j7;
        r = j3;
        s = qw1.B;
        t = qw1.T;
        long j8 = qw1.X;
        u = j8;
        v = qw1.R;
        long j9 = qw1.U;
        w = j9;
        x = qw1.A;
        long j10 = qw1.y;
        y = j10;
        long j11 = qw1.I;
        z = j11;
        A = j5;
        B = j4;
        C = j11;
        D = qw1.h;
        long j12 = qw1.P;
        E = j12;
        F = j7;
        G = j6;
        H = j12;
        I = j2;
        J = qw1.o;
        K = qw1.k;
        L = qw1.l;
        M = qw1.n;
        N = qw1.i;
        O = qw1.p;
        P = j2;
        Q = j10;
        long j13 = qw1.W;
        R = j13;
        S = j9;
        T = j8;
        U = j13;
    }
}
