package defpackage;

/* JADX INFO: compiled from: r8-map-id-1fdf33e95b2c98e9913e3f754a675e277db58555c92b1678ad704849f4b90bb4 */
/* JADX INFO: loaded from: classes.dex */
public abstract class mu {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    static {
        long j2 = qw1.x;
        a = j2;
        b = qw1.e;
        c = qw1.g;
        d = qw1.v;
        long j3 = qw1.I;
        e = j3;
        f = qw1.m;
        long j4 = qw1.i;
        g = j4;
        h = qw1.b;
        i = qw1.a;
        j = qw1.E;
        long j5 = qw1.D;
        k = j5;
        l = j5;
        m = qw1.G;
        n = qw1.L;
        long j6 = qw1.K;
        o = j6;
        p = j6;
        q = qw1.N;
        r = j4;
        s = qw1.y;
        t = qw1.S;
        long j7 = qw1.R;
        u = j7;
        v = j7;
        w = qw1.U;
        x = qw1.z;
        y = qw1.B;
        z = qw1.H;
        long j8 = qw1.J;
        A = j8;
        B = j8;
        C = j3;
        D = qw1.h;
        E = qw1.O;
        long j9 = qw1.Q;
        F = j9;
        G = j9;
        H = qw1.P;
        I = j2;
        J = j2;
        K = qw1.u;
        L = qw1.t;
        M = qw1.s;
        N = qw1.w;
        O = qw1.j;
        P = qw1.r;
        Q = qw1.C;
        R = qw1.V;
        long j10 = qw1.X;
        S = j10;
        T = j10;
        U = qw1.W;
    }
}
