// 自动恢复的 Objective-C 接口骨架
#import <Foundation/Foundation.h>

@interface AVFAudioReceiver : NSObject
@end

@interface AVFFrameReceiver : NSObject
@end

@interface ArchDetect : NSObject
@end

@interface AtomicLong : NSObject
@end

@interface CallbackData : NSObject
@end

@interface ContactSelectViewDelegate : NSObject
@end

@interface FFmpegExecution : NSObject
@end

@interface GroupSelectsViewControllerDelegate : NSObject
@end

@interface MediaInformation : NSObject
@end

@interface MediaInformationParser : NSObject
@end

@interface MobileFFmpeg : NSObject
@end

@interface MobileFFmpegConfig : NSObject
@end

@interface MobileFFprobe : NSObject
@end

@interface MultiSelectContactsViewControllerDelegate : NSObject
@end

@interface NSObject : NSObject
@end

@interface SSZipArchive : NSObject
@end

@interface Statistics : NSObject
@end

@interface StreamInformation : NSObject
@end

@interface WCPureExtensionAutoDownloadSettingsController : NSObject
@end

@interface WCPureExtensionBackgroundLockAuthViewController : NSObject
@end

@interface WCPureExtensionBubbleSettingsController : NSObject
@end

@interface WCPureExtensionCssSettingsController : NSObject
@end

@interface WCPureExtensionDisableSettingsController : NSObject
@end

@interface WCPureExtensionEmojiSettingsController : NSObject
@end

@interface WCPureExtensionEnableSettingsController : NSObject
@end

@interface WCPureExtensionFriendsCheckSettingsController : NSObject
@end

@interface WCPureExtensionGroupSelectsController : NSObject
@end

@interface WCPureExtensionManager : NSObject
@end

@interface WCPureExtensionReMsgSettingsController : NSObject
@end

@interface WCPureExtensionRedEnvelopParam : NSObject
@end

@interface WCPureExtensionRedEnvelopParamPool : NSObject
@end

@interface WCPureExtensionRedEnvelopesSettingsController : NSObject
@end

@interface WCPureExtensionReveiverSettingsController : NSObject
@end

@interface WCPureExtensionSettings : NSObject
@end

@interface WCPureExtensionShortcutSettingsController : NSObject
@end

@interface WCPureExtensionVoiceSettingsController : NSObject
@end

@interface WCPureExtension_BackgRoundBlur : NSObject
@end

@interface WCPureExtension_GestureRecognizer : NSObject
@end

// 未可靠归属到具体类的 selector：
// .cxx_destruct
// AddAppMsg:MsgWrap:Data:Scene:
// AddLocalMsg:MsgWrap:
// AddLocalMsg:MsgWrap:fixTime:NewMsgArriveNotify:
// AddMsg:MsgWrap:
// AddVideoMsg:ToUsr:VideoInfo:
// Alpha0_7
// CGColor
// CGImage
// ChangeSessionUnReadCount:to:
// CheckEmoticonExistInCustomListByMd5:
// ClearUnRead:FromID:ToID:
// ClearUnRead:HelloUser:
// CreateProtobufEvent:Flag:
// DisableBQTX:
// DisableDBFXL:
// DisableDHYMSYS:
// DisableDYHKYK:
// DisableDYHLBGG:
// DisableEmoticonBoardCamera:
// DisableEmoticonBoardRecentUse:
// DisableEmoticonBoardSearch:
// DisableFoldWithPYQ:
// DisableFullVideoTapClose:
// DisableHYDTSP:
// DisableHomeSlideDelete:
// DisableJMFGX:
// DisableLLTHJG:
// DisableMeViewEmojiPure:
// DisableMeViewFavoritesPure:
// DisableMeViewKBPure:
// DisableMeViewPYQPure:
// DisableMeViewPayPure:
// DisableMeViewSPHPure:
// DisablePYP:
// DisablePYQGG:
// DisablePYQSKYK:
// DisablePYQShowSource:
// DisableQZYSMC:
// DisableQuickForward:
// DisableSYSSGN:
// DisableSettingViewCJPure:
// DisableSettingViewDSFXXGXQDPure:
// DisableSettingViewGHPure:
// DisableSettingViewGRXXSJQDPure:
// DisableSettingViewGRXXYQXPure:
// DisableSettingViewQSNPure:
// DisableVideoFrontCameraMirror:
// DisableWWanAutoDownloadMedia:
// DisableXCXQDGG:
// DisableXLXCX:
// DisableXXYQTSBZXTS:
// DisableYYNQTSBZXTS:
// DisableZJSRZT:
// EnableAllowYourSelf:
// EnableAppMsgAgain:
// EnableAutoDownloadMedia:
// EnableAutoDownloadMediaWithFile:
// EnableAutoDownloadMediaWithPhoto:
// EnableAutoDownloadMediaWithVideo:
// EnableBJDZPYQ:
// EnableBackgRoundBlur:
// EnableBlockBlockedLinks:
// EnableCAJTFSXCKJFS:
// EnableCQHSZZB:
// EnableCallDetermine:
// EnableCallkit:
// EnableCardMsgAgain:
// EnableChangeCSS:
// EnableChangeChatCSS:
// EnableChangeSteps:
// EnableDHJXDYSP:
// EnableDHLTPKJZFZPYQ:
// EnableDHNWBFC:
// EnableDHYSJKJSSJL:
// EnableEmojiMsgAgain:
// EnableFSXXH:
// EnableFavoritesVoiceForward:
// EnableFileMsgAgain:
// EnableFileToVoice:
// EnableHDXJMS:
// EnableIconCircular:
// EnableImageMsgAgain:
// EnableJBXXLDYH:
// EnableJoker:
// EnableKJHCJPTX:
// EnableKJWJZ:
// EnableKJXGBZ:
// EnableKJZFPYQTP:
// EnableMRXZYT:
// EnableMemberExitMonitoring:
// EnableNoteMsgAgain:
// EnablePYQSPJDT:
// EnablePYQSafari:
// EnablePYQZDDZ:
// EnableQJHBXXTX:
// EnableQJZZXXTX:
// EnableQuickSearchTextEmoticons:
// EnableRecordMsgAgain:
// EnableRightToLeftGesture:
// EnableSRKZWF:
// EnableSWYZJS:
// EnableSafari:
// EnableSaveEmoji:
// EnableShowDelComment:
// EnableShowWXID:
// EnableSimulateCameraScanQR:
// EnableTextMsgAgain:
// EnableTextToVoice:
// EnableTingMsgAgain:
// EnableVideoMsgAgain:
// EnableVideoToVoice:
// EnableVoiceForward:
// EnableVoiceListManager:
// EnableVoiceMsgAgain:
// EnableVoiceToFile:
// EnableXCXSPGGJS:
// EnableXXFCH:
// EnableXZWSX:
// EnableYJQKPYQ:
// EnableYJYDXX:
// EnableZDDQTOP:
// EnableZDSK:
// EnableZDSKReply:
// EnableZDSKReplyInGroup:
// EnableZDSKYYBB:
// EnableZDTYHYQQ:
// EnableZDYZJS:
// EndBlurView
// FileExist:
// ForwardMsg:ToContact:
// GenSendMsgTime
// Gesture_action
// Gesture_invoke
// Gesture_setAction:
// GetCContact
// GetChatName
// GetDataMD5:
// GetDataPath
// GetDocPath
// GetMsg:n64SvrID:
// GetMsgByCreateTime:FromID:FromCreateTime:Limit:LeftCount:
// GetPathOfAppDataByUserName:andMessageWrap:retStrPath:
// GetPathOfMesAudio:LocalID:DocPath:
// GetStrangerAttribute:AttributeName:
// GetTransferPrepayRequest:
// GetUserNamesOnSessionList
// GlobalInstance
// HasHealthKit
// IsAppMessage
// IsChatRoom:
// IsDownloadEnded
// IsImgMsg
// IsOpenImContactUserName:
// IsOpenImKeFuContactUserName:
// IsTextMsg
// IsUserInChatRoom:
// IsVideoMsg
// IsVoiceMsg
// JSONObjectWithData:options:error:
// MMGrowTextViewHeightDidChanged:
// OnClear:
// OnWCPayTransferMoneyStatusViewControllerConfirmTransfer
// OpenIMRedEnvelopesWithResponseDic:withSign:
// OpenOpenIMRedEnvelopesRequest:
// OpenRedEnvelopesRequest:
// OpenRedEnvelopesWithResponseDic:withSign:
// ParseRedPacketAutoReplyWithResponseDic:
// PresentModalViewController:animated:
// PresentModalViewController:animated:completion:
// PushSearchLogicControllerByContact:navigationController:ForMessageWrap:animated:fromeScene:highlighted:
// PushViewController:animated:
// PushViewController:animated:completion:
// ReceiverQueryOpenIMRedEnvelopesRequest:
// ReceiverQueryRedEnvelopesRequest:
// ResendVoiceMsg:MsgWrap:
// SexChange
// SexChangeTips
// Showmyqrcode:
// Showopen_Receive_Money:
// Showopen_XCX:
// Showqrcode:
// Showreceive_pay:
// StartDownloadVideo:DownloadMode:
// T#,R
// T@"<GroupSelectsViewControllerDelegate>",N,V_delegate
// T@"ContactSelectView",&,N,V_selectView
// T@"NSData",&,N,V_authImageData
// T@"NSDate",&,N,V_enterBackgroundDate
// T@"NSMutableArray",&,N,V_params
// T@"NSString",?,R,C
// T@"NSString",C,N,V_authName
// T@"NSString",R,C
// T@"UIButton",&,N,V_unlockBtn
// T@"UILabel",&,N,V_hintLabel
// T@,&,N,V_activity
// T@,&,N,V_activityHandler
// T@,&,N,V_shareFileAnnotation
// T@,&,N,V_shareFileSource
// T@,&,N,V_shareFileURL
// T@,&,N,V_shortcutItem
// T@?,C,N,SGesture_setAction:
// TB,N,V_backgroundLockVisible
// TB,N,V_fromShareAction
// TB,N,V_fromShareFileAction
// TB,N,V_fromShortcutAction
// TB,R,V_useZip64
// TQ,R
// TopSessionByName:
// URLPathAllowedCharacterSet
// URLQueryAllowedCharacterSet
// URLWithString:
// UTF8String
// UUID
// UUIDString
// UntopSessionByName:
// _activity
// _activityHandler
// _applicationIconImageForBundleIdentifier:format:scale:
// _authImageData
// _authName
// _backgroundLockVisible
// _base64RFC4648
// _channelId
// _context
// _currentCheckResult
// _dateWithMSDOSFormat:
// _delegate
// _documentPicker:didPickDocumentAtURL:
// _enterBackgroundDate
// _filenameStringWithCString:size:
// _friendCheckGCD
// _fromShareAction
// _fromShareFileAction
// _fromShortcutAction
// _gregorian
// _headImg
// _hexString
// _hintLabel
// _invalidFriends
// _isGroupSender
// _msgType
// _nativeUrl
// _nickName
// _notFriends
// _params
// _path
// _sanitizedPath
// _searchBarCancelButtonClicked:
// _sectionContentInset
// _selectView
// _sendId
// _sessionUserName
// _setSectionContentInset:
// _shareFileAnnotation
// _shareFileSource
// _shareFileURL
// _shortcutItem
// _sign
// _timingIdentifier
// _unlockBtn
// _useZip64
// _viewControllerForAncestor
// _zip
// absoluteString
// actionWithTitle:style:handler:
// activateConstraints:
// activationState
// activity
// activityHandler
// adapterWithViewController:height:
// addAction:
// addAttribute:value:range:
// addAutoDownloadGroupList:
// addBtnTitle:handler:
// addBtnTitle:target:sel:
// addButtonWithTitle:atIndex:
// addButtonWithTitle:eventAction:
// addCancelBtnTitle:target:sel:
// addCell:
// addConstraint:
// addContentsOfDirectory:keepParentDirectory:compressionLevel:password:AES:keepSymlinks:progressHandler:
// addContentsOfDirectory:keepParentDirectory:compressionLevel:password:AES:progressHandler:
// addDestructiveBtnTitle:handler:
// addGestureRecognizer:
// addInput:
// addLongPressTarget:action:
// addMessageToDB:
// addNew:
// addObject:
// addObjectsFromArray:
// addObserverForName:object:queue:usingBlock:
// addOperationWithBlock:
// addOutput:
// addResourceWithType:data:options:
// addSection:
// addSelect:
// addSticker:
// addSubview:
// addTableViewToSuperView:
// addTapAction:
// addTarget:action:
// addTarget:action:forControlEvents:
// addTextFieldWithConfigurationHandler:
// addValue:forHTTPHeaderField:
// alertControllerWithTitle:message:preferredStyle:
// allKeys
// allObjects
// allTopSessions
// alloc
// animatedDecoderOfData:cpKey:
// appInfo
// appearanceWhenContainedInInstancesOfClasses:
// appendFormat:
// appendString:
// application:continueUserActivity:restorationHandler:
// application:openURL:sourceApplication:annotation:
// applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:
// archivedDataWithRootObject:requiringSecureCoding:error:
// argumentsToString:
// array
// arrayWithArray:
// arrayWithObject:
// arrayWithObjects:count:
// assetWithURL:
// attachmentButton
// attributesOfItemAtPath:error:
// authImageData
// authName
// authVerification
// autoAddFriendReply
// autoDownloadGroupList
// autoGetHongBaoWithWrap:
// autoGetTransferWithWrap:
// autoLikeMode
// autoLikeModeAction:
// automaticReceiptText
// automaticZDSKReceiptText
// autorelease
// availableVideoCVPixelFormatTypes
// backgRoundBlurLevel
// backgroundBlurChanged:
// backgroundColor
// backgroundLockVisible
// balanceHintBtn
// bannerTitle
// bannerView
// base64EncodedStringWithOptions:
// batchOperation
// biometryType
// bitrate
// blackColor
// blurImageWithRadius:
// boolValue
// bottomAnchor
// bounds
// btnClicked:
// bubbleFolderName
// buffer
// bundleForClass:
// bundleWithPath:
// buttonModeAction:
// buttonTitleAtIndex:
// buttonWidth:
// buttonWithType:
// bytes
// cStringUsingEncoding:
// cachedCellForSpecifier:
// calculateFitSize:maxWidth:maxHeight:
// callStackSymbols
// canAddInput:
// canAddOutput:
// canEvaluatePolicy:error:
// canPlayVideo
// cancel
// cancel:
// cancelButton
// captureOutput:didOutputSampleBuffer:fromConnection:
// cellConfig
// cellEnabled
// cells
// center
// centerCellForSel:target:title:
// centerXAnchor
// centerYAnchor
// cgiCmdid
// changeFont:
// changeLanguageAndCleanAllCache
// changedCSSStr
// changedChatCSSStr
// changedSteps
// changedVoiceTime
// characterAtIndex:
// characterSetWithCharactersInString:
// childViewControllers
// class
// clearAllSection
// clearAllTimelineMsgUnreadStatus
// clearColor
// clearDatasOptions
// clearPlayList
// clearReadCountForBrand:
// close
// closeFFmpegPipe:
// code
// colorInLightMode:DarkMode:
// colorWithAlphaComponent:
// colorWithRed:green:blue:alpha:
// colorWithWhite:alpha:
// command
// comment
// compare:
// components:fromDate:
// componentsJoinedByString:
// componentsSeparatedByCharactersInSet:
// componentsSeparatedByString:
// configurationWithActions:
// conformsToProtocol:
// connectedScenes
// constraintEqualToAnchor:
// constraintEqualToAnchor:constant:
// constraintEqualToConstant:
// constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:
// contactFrontView
// containsObject:
// containsString:
// content
// contentDesc
// contentHorizontalAlignment
// contentObj
// contentOffset
// contentSize
// contentTextSize
// contentsOfDirectoryAtPath:error:
// contextualActionWithStyle:title:handler:
// continueCallAction
// copy
// copyItemAtPath:toPath:error:
// count
// countByEnumeratingWithState:objects:count:
// cpKeyForEmoticonMd5:
// createDirectoryAtPath:withIntermediateDirectories:attributes:error:
// createZipFileAtPath:withContentsOfDirectory:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:compressionLevel:password:AES:keepSymlinks:useZip64:progressHandler:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:compressionLevel:password:AES:progressHandler:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:compressionLevel:password:AES:progressHandler:keepSymlinks:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:withPassword:
// createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:withPassword:andProgressHandler:
// createZipFileAtPath:withContentsOfDirectory:withPassword:
// createZipFileAtPath:withFilesAtPaths:
// createZipFileAtPath:withFilesAtPaths:withPassword:
// createZipFileAtPath:withFilesAtPaths:withPassword:keepSymlinks:
// createZipFileAtPath:withFilesAtPaths:withPassword:progressHandler:
// createtime
// creationRequestForAsset
// creationRequestForAssetFromImage:
// curDatePicker
// currentCalendar
// currentContext
// currentDevice
// currentFrameId
// currentFrameImage
// currentHandler
// currentTitleColor
// currentTraitCollection
// data
// dataItem
// dataList
// dataOfEmoticonForMd5:needUpdateTime:ignoreWxAM:
// dataTaskWithRequest:completionHandler:
// dataUsingEncoding:
// dataWithBytes:length:
// dataWithContentsOfFile:
// dataWithContentsOfFile:options:error:
// dataWithContentsOfURL:
// date
// dateByAddingComponents:toDate:options:
// dateFromComponents:
// dateWithTimeIntervalSince1970:
// day
// dealloc
// debugDescription
// decimalNumberWithString:
// defaultCenter
// defaultDeviceWithMediaType:
// defaultManager
// defaultSection
// delegate
// deleteBackward
// deleteDataItem:
// deleteDataItemServer:
// description
// detailTextLabel
// devicesWithMediaType:
// dictionary
// dictionaryWithDecodedComponets:separator:
// dictionaryWithObject:forKey:
// dictionaryWithObjects:forKeys:count:
// didDownloadOK:
// disableBQTX
// disableDBFXL
// disableDHYMSYS
// disableDYHKYK
// disableDYHLBGG
// disableEmoticonBoardCamera
// disableEmoticonBoardRecentUse
// disableEmoticonBoardSearch
// disableFoldWithPYQ
// disableFullVideoTapClose
// disableHYDTSP
// disableHomeSlideDelete
// disableJMFGX
// disableLLTHJG
// disableMeViewEmojiPure
// disableMeViewFavoritesPure
// disableMeViewKBPure
// disableMeViewPYQPure
// disableMeViewPayPure
// disableMeViewSPHPure
// disablePYP
// disablePYQGG
// disablePYQSKYK
// disablePYQShowSource
// disableQZYSMC
// disableQuickForward
// disableRedirection
// disableSYSSGN
// disableSettingViewCJPure
// disableSettingViewDSFXXGXQDPure
// disableSettingViewGHPure
// disableSettingViewGRXXSJQDPure
// disableSettingViewGRXXYQXPure
// disableSettingViewQSNPure
// disableVideoFrontCameraMirror
// disableWWanAutoDownloadMedia
// disableXCXQDGG
// disableXLXCX
// disableXXYQTSBZXTS
// disableYYNQTSBZXTS
// disableZJSRZT
// dismissViewController:
// dismissViewControllerAnimated:completion:
// dismissWithAnimated:
// doChangeCSS
// doShareApi:bundleID:fromSysCopy:parameter:
// doVerify:
// domain
// doubleValue
// doutuAction
// downloadCDNMgr
// downloadMedia:downloadType:
// downloadMgr
// downloadMultiMsg
// downloadMultiMsg:saveToAlbum:
// draftWithVideoURL:
// drawInRect:
// duration
// dynamicLength:
// dynamicLength:forModule:
// emptyGroupSpecifier
// enableAllowYourSelf
// enableAppMsgAgain
// enableAutoDownloadMedia
// enableAutoDownloadMediaWithFile
// enableAutoDownloadMediaWithPhoto
// enableAutoDownloadMediaWithVideo
// enableBJDZPYQ
// enableBackgRoundBlur
// enableBlockBlockedLinks
// enableCAJTFSXCKJFS
// enableCQHSZZB
// enableCallDetermine
// enableCallkit
// enableCardMsgAgain
// enableChangeCSS
// enableChangeChatCSS
// enableChangeSteps
// enableDHJXDYSP
// enableDHLTPKJZFZPYQ
// enableDHNWBFC
// enableDHYSJKJSSJL
// enableEmojiMsgAgain
// enableFSXXH
// enableFavoritesVoiceForward
// enableFileMsgAgain
// enableFileToVoice
// enableFriendCheck
// enableHDXJMS
// enableIconCircular
// enableImageAddEmojiInEssay
// enableImageAddEmojiInEssay:
// enableImageAddEmojiInMsg
// enableImageAddEmojiInMsg:
// enableImageMsgAgain
// enableIsAutoRedEnvelop
// enableIsMeRedEnvelope
// enableIsPrivateChatRedEnvelope
// enableJBXXLDYH
// enableJoker
// enableKJHCJPTX
// enableKJWJZ
// enableKJXGBZ
// enableKJZFPYQTP
// enableMRXZYT
// enableMemberExitMonitoring
// enableNoteMsgAgain
// enablePYQSPJDT
// enablePYQSafari
// enablePYQZDDZ
// enableQJHBXXTX
// enableQJZZXXTX
// enableQuickSearchTextEmoticons
// enableRecordMsgAgain
// enableRedEnvelopAutoReply
// enableRedEnvelopAutoReplyInGroup
// enableRedEnvelopeDetail
// enableRedirection
// enableRightToLeftGesture
// enableSRKZWF
// enableSWYZJS
// enableSafari
// enableSaveEmoji
// enableShortcutReceive
// enableShowDelComment
// enableShowWXID
// enableShowmyqrcode
// enableShowopen_Receive_Money
// enableShowopen_XCX
// enableShowqrcode
// enableShowreceive_pay
// enableSimulateCameraScanQR
// enableTextMsgAgain
// enableTextToVoice
// enableTingMsgAgain
// enableVideoMsgAgain
// enableVideoToVoice
// enableVoiceForward
// enableVoiceListManager
// enableVoiceMsgAgain
// enableVoiceToFile
// enableXCXSPGGJS
// enableXXFCH
// enableXZWSX
// enableYJQKPYQ
// enableYJYDXX
// enableZDDQTOP
// enableZDSK
// enableZDSKReply
// enableZDSKReplyInGroup
// enableZDSKYYBB
// enableZDTYHYQQ
// enableZDYZJS
// endBlurView
// endEditing:
// enterBackgroundDate
// enumerateByteRangesUsingBlock:
// enumerateKeysAndObjectsUsingBlock:
// enumerateObjectsUsingBlock:
// enumerateObjectsWithOptions:usingBlock:
// enumeratorAtPath:
// enumeratorAtURL:includingPropertiesForKeys:options:errorHandler:
// ephemeralSessionConfiguration
// errorWithDomain:code:userInfo:
// evaluateJavaScript:completionHandler:
// evaluatePolicy:localizedReason:reply:
// exceptionWithName:reason:userInfo:
// exchangeObjectAtIndex:withObjectAtIndex:
// executablePath
// execute:
// execute:delimiter:
// executeAsync:withCallback:
// executeAsync:withCallback:andDispatchQueue:
// executeCallback::
// executeWithArguments:
// executeWithArgumentsAsync:withCallback:
// executeWithArgumentsAsync:withCallback:andDispatchQueue:
// executeWithId:andArguments:
// executionId
// exportAsynchronouslyWithCompletionHandler:
// exportFile:
// expressionButton
// extensionSharedInstance
// familyNames
// fetchAssetsWithLocalIdentifiers:options:
// fileExistOfEmoticonForMd5:
// fileExistsAtPath:
// fileExistsAtPath:isDirectory:
// fileSizeOfEmoticonForMd5:
// fileSystemRepresentation
// fileURLWithPath:
// fileURLWithPath:isDirectory:
// filteredArrayUsingPredicate:
// firstObject
// floatValue
// font
// fontDescriptorWithFontAttributes:
// fontWithDescriptor:size:
// fontWithName:size:
// footerLabel
// forceHideMenuOptionsAnimated:
// formatDescription
// forwardMessage:fromViewController:
// forwardingTargetForSelector:
// forwordImage:
// frame
// frameCount
// frameX
// from:
// from:with:
// fromShareAction
// fromShareFileAction
// fromShortcutAction
// fullUrl
// genFileAppMsgWithFileName:filePath:fileData:
// genSectionFootView:
// genSectionHeadView:
// generalPasteboard
// generateVideoThumbImage:atTime:
// gestureRecognizers
// getAllProperties
// getAllUserNamesOnSessionStorgae
// getAppBlurImage
// getAppViewControllerManager
// getArch
// getAudioFileName:LocalID:
// getAverageFrameRate
// getBarButtonWithImageName:target:action:style:accessibility:
// getBarButtonWithImageName:target:action:style:accessibility:color:
// getBarButtonWithTitle:target:action:style:
// getBitrate
// getBuildConf
// getBuildDate
// getChannelLayout
// getChatContact
// getCodec
// getCodecTimeBase
// getCommand
// getContactByName:
// getContactDisplayName
// getContactFrom:
// getContactFromDB:
// getContactList:contactType:
// getCpuArch
// getCurLanguage
// getCurUsrName
// getCurrentChatName
// getCurrentNavigationController
// getCurrentPageRelativePath
// getCurrentUserName
// getDisplayAspectRatio
// getDuration
// getExecutionId
// getExternalLibraries
// getFFmpegVersion
// getFilename
// getFormat
// getFormatVideoPath
// getFullCodec
// getHeight
// getIndex
// getLastCommandOutput
// getLastReceivedStatistics
// getLastReturnCode
// getLogData
// getLogLevel
// getLongFormat
// getMD5ByGameContent:
// getMediaInformation:
// getMediaInformation:timeout:
// getMediaInformationFromCommand:
// getMediaInformationFromCommandArguments:
// getMediaProperties
// getMsgMiddleImgData:
// getNewMainFrameViewController
// getNumberProperty:
// getPackageName
// getPathOfMsgImg:
// getProperties:
// getRealFrameRate
// getRealUserName
// getRemark
// getResourceValue:forKey:error:
// getSampleAspectRatio
// getSampleFormat
// getSampleRate
// getSelectedMsgLocalIds
// getSelectedMsgs
// getSelfContact
// getService:
// getSize
// getSpeed
// getStartTime
// getStatisticsBitrate
// getStatisticsFps
// getStatisticsFrameNumber
// getStatisticsQuality
// getStatisticsSize
// getStatisticsSpeed
// getStatisticsTime
// getStreams
// getStringForCurLanguage:
// getStringProperty:
// getTableView
// getTags
// getTime
// getTimeBase
// getTopViewController
// getType
// getValue:
// getValueOfProperty:inRuleSet:
// getVersion
// getVideoDurationForAsset:
// getVideoFps
// getVideoFrameNumber
// getVideoQuality
// getViewController
// getVisibleHeight
// getWalletEntryTitle
// getWidth
// goShareAction
// goShareFileAction
// goShortcutAction
// goToLazyInitObject
// groupSpecifierWithName:
// handleFailureInMethod:object:file:lineNumber:description:
// hasDeviceNotch
// hasPrefix:
// hasSuffix:
// hash
// height
// heightAnchor
// hideSendCaptrueViewAnimated:
// hintLabel
// hlSvgName:Size:
// hour
// iconWithTemplateImageName:
// identifier
// ignoreSignal:
// image
// imageData
// imageNamed:inBundle:compatibleWithTraitCollection:
// imageView
// imageWithContentsOfFile:
// imageWithData:
// imageWithTraitCollection:
// importFile:
// incrementAndGet
// indexOfObject:
// indexPathsForSelectedRows
// init
// init:
// init:withStreams:
// initAutoDownloadSettings
// initBubbleFolderSettings
// initData:
// initEnableSettings
// initGestureWithCallback:
// initPrivate
// initRedEnvelopesSettings
// initShortcutSettings
// initView
// initVoiceSettings
// initWithActivityItems:applicationActivities:
// initWithAsset:presetName:
// initWithBarButtonSystemItem:target:action:
// initWithBase64EncodedString:options:
// initWithBytes:length:
// initWithBytesNoCopy:length:encoding:freeWhenDone:
// initWithCalendarIdentifier:
// initWithCodeType:fromScene:
// initWithContentsController:
// initWithContentsOfFile:
// initWithContentsOfURL:
// initWithContext:
// initWithData:
// initWithData:encoding:
// initWithDataItem:
// initWithDevice:error:
// initWithDictionary:
// initWithDocumentTypes:inMode:
// initWithExecutionId:andArguments:
// initWithFormat:arguments:
// initWithFrame:
// initWithFrame:delegate:
// initWithFrame:style:
// initWithId:logLevel:data:
// initWithId:videoFrameNumber:fps:quality:size:time:bitrate:speed:
// initWithImage:
// initWithImages:contacts:
// initWithInitialValue:
// initWithItems:
// initWithLength:
// initWithMsgType:
// initWithObjects:
// initWithPath:
// initWithPath:useZip64:
// initWithRootViewController:
// initWithSightDraft:
// initWithString:
// initWithTarget:action:
// initWithTitle:action:
// initWithTitle:cancelButtonTitle:
// initWithTitle:message:
// initWithTitle:minTime:maxTime:selectTime:
// initWithTitle:style:target:action:
// initWithTitle:svgName:action:
// initWithType:action:
// initWithType:arrContacts:
// initWithType:localizedTitle:localizedSubtitle:icon:userInfo:
// initWithURL:
// initWithViewController:logicParams:
// initWithWeAppUsername:
// initialize
// inputModeChangeButton
// inputRemarkStr
// insertObject:atIndex:
// insertSection:At:
// insertString:
// instancesRespondToSelector:
// intValue
// integerValue
// interactivePopGestureRecognizer
// internalApplication:performActionForShortcutItem:completionHandler:
// invalidate
// invoke
// isActive
// isAd
// isAutoLikeUser
// isBrandContact
// isChatStatusNotifyOpen
// isChatroom
// isContactSessionTop
// isDataItemDeleted:
// isDragging
// isEditing
// isEnabled
// isEqual:
// isEqualToString:
// isExceptionFileName:
// isFileHelper
// isFilePasswordProtectedAtPath:
// isFileURL
// isFirstResponder
// isGIFFile:
// isGroupCard
// isHidden
// isHolderContact
// isHongBaoMessageForNewWCPayBizExt
// isKeyWindow
// isKindOfClass:
// isLTSBuild
// isLoaded
// isLoading
// isLocalizedContact
// isLogin
// isMMContact
// isMemberOfClass:
// isMyContact
// isNativeHongBaoMsg
// isNormalContact
// isOfficialContact:
// isOn
// isOnWWan
// isOriginSelected
// isPasswordValidForArchiveAtPath:password:error:
// isPlaying
// isProModeEnabledForScene:
// isProxy
// isRedEnvelopGroupFiter
// isRedEnvelopTextFiter
// isSearchBarActive
// isSelected
// isSelf
// isSenderFromMsgWrap:
// isSilkFile:
// isSubclassOfClass:
// isTransferMessageForNewWCPayBizExt
// isUnSafe
// isValid
// isWeixinTeamContact
// isWxAMData:
// itemArray
// jumpToCameraScanInTopViewController:
// keyWindow
// killAction:
// lastCaptureAssetURL
// lastObject
// lastPathComponent
// layer
// leadingAnchor
// leftAnchor
// leftConfig
// length
// likeFlag
// likeObject:ofUser:source:extraInfo:
// likeUsers
// lineBreakMode
// listExecutions
// listFrontView
// load
// loadCurUserInfo:
// loadingView
// localizedCaseInsensitiveCompare:
// localizedDescription
// localizedName
// localizedStringForKey:value:table:
// lock
// lockForConfiguration:
// logCallback:::
// logData
// logLevel
// logLevelToString:
// loginMode
// loginModeAction:
// longPressGesture:
// lowercaseString
// m_actionType
// m_c2cNativeUrl
// m_commentBtn
// m_contact
// m_data
// m_delegate
// m_dicMultiSelect
// m_dtVoice
// m_emoticonAddLogic
// m_extendInfoWithMsgType
// m_forwardBtn
// m_imgUrl
// m_isPlugin
// m_item
// m_lRecAmount
// m_lRecNum
// m_lTotalAmount
// m_lTotalNum
// m_lineViewTwo
// m_n64MesSvrID
// m_nsAliasName
// m_nsAppFileExt
// m_nsChatRoomMemList
// m_nsChatRoomUserName
// m_nsContent
// m_nsEncodeUserName
// m_nsFeeDesc
// m_nsFromUsr
// m_nsHeadImgUrl
// m_nsNickName
// m_nsRemark
// m_nsTicket
// m_nsTitle
// m_nsToUsr
// m_nsUsrName
// m_oWCPayInfoItem
// m_oWCRedEnvelopesDetailInfo
// m_pbRequest
// m_pbResponse
// m_sceneId
// m_tableView
// m_tipsContentLabel
// m_uiAppMsgInnerType
// m_uiCreateTime
// m_uiFriendScene
// m_uiGameType
// m_uiMesLocalID
// m_uiMessageType
// m_uiScene
// m_uiVoiceTime
// m_uiWCFlag
// mainBundle
// mainQueue
// mainScreen
// makeFileAppCommunicateData:
// maskView
// matchesInString:options:range:
// mediaList
// mediumSystemFontOfSize:
// messageLabel
// messageWrap
// minute
// modifyDataItem:notify:
// modifyUserInfo:
// monospacedDigitSystemFontOfSize:weight:
// month
// moveItemAtPath:toPath:error:
// moveToTab:showMainView:
// mutableBytes
// mutableCopy
// name
// navigationBar
// navigationBarHeightCurOri
// navigationController
// navigationItem
// needDownLoad
// new
// nextObject
// normalCellForSel:target:title:
// normalCellForSel:target:title:accessoryType:
// normalCellForSel:target:title:rightValue:accessoryType:
// normalCellForSel:target:title:rightView:
// normalCellForTitle:rightValue:
// normalStatusBarHeight
// nsTitle
// numberFromString:
// numberOfRanges
// numberWithBool:
// numberWithDouble:
// numberWithFloat:
// numberWithInt:
// numberWithInteger:
// numberWithLong:
// numberWithUnsignedInt:
// numberWithUnsignedInteger:
// numberWithUnsignedLong:
// numberWithUnsignedLongLong:
// objectAtIndex:
// objectAtIndexedSubscript:
// objectForKey:
// objectForKey:inDomain:
// objectForKeyedSubscript:
// observeValueForKeyPath:ofObject:change:context:
// onAddTTFFile
// onDone:
// onInputModeChangeButtonClicked:
// onLongPress:
// onMultiSelectContactCancelForSns
// onMultiSelectContactReturn:
// onMultiSelectContactReturnForSns:
// onMultiSelectGroupReturn:
// onMultiSelectUserReturn:
// onOriginImageCheck:
// onParticiple
// onPlaceHolder:
// onPutVoiceListManager
// onPutVoiceListManagerZIP:
// onReSend
// onRevokeMsg:
// onSearchHistory
// onSelectContact:
// onSendSignalButtonClicked:
// onTapBubbleCell:
// onTextJoker
// onToAudioFile
// onTransferJoker
// onVideoFileToVoiceWithSend
// onVideoToVoiceWithSend
// onVoiceFileToVoiceWithSend
// onVoiceForward
// onVoiceManagerButtonClicked:
// open
// openApp:taskExtInfo:onSuccess:onFailed:
// openFace2FaceReceiveMoney
// openForAppending
// openQRCodeOrWXCodeLandingPage:isShowMultiCodes:
// open_XCXIDStr
// open_XCXNameStr
// open_XCXPathStr
// origTime
// origTimeAction:
// originalContentSize
// originalSpecifiers
// pageSheetAdapter
// pageSheetConfig
// panGestureRecognizer
// params
// parseArguments:
// parseFloatFromValues:
// path
// pathExtension
// pathForData
// pathForSightData
// payloadSizeForArchiveAtPath:error:
// performChanges:completionHandler:
// performSelector:
// performSelector:withObject:
// performSelector:withObject:afterDelay:
// performSelector:withObject:withObject:
// performWithoutAnimation:
// persistentDomainForName:
// placeHolderList
// playAtTime:
// playButtonTapped:
// popToRootViewControllerAnimated:
// popViewControllerAnimated:
// popoverPresentationController
// preStartSilentDownloadFile:svrid:
// predicateWithBlock:
// predicateWithFormat:
// preferenceSpecifierNamed:target:set:get:detail:cell:edit:
// preparePlayNotNotify
// preparePlayWithFile:
// preparePlayWithFile:sync:
// presentViewController:animated:completion:
// presentedViewController
// properties
// pushSearchControllerWithCompletion:
// raise:format:arguments:
// rangeAtIndex:
// rangeOfString:
// rangeOfString:options:
// readPreferenceValue:
// reason
// recordButton
// redEnvelopAutoReply:
// redEnvelopAutoReplyInGroup:
// redEnvelopAutoReplyStr
// redEnvelopDelay
// redEnvelopDelayTime
// redEnvelopTextFilter
// refreshLanguage:
// refreshLocalFonts
// registerControllerWithTitle:version:controller:
// registerImage:withTraitCollection:
// registerNewFFmpegPipe
// regularExpressionWithPattern:options:error:
// release
// reloadActionSheet:
// reloadData
// reloadInnerView
// reloadSpecifiers
// reloadTableData
// removeFromSuperview
// removeItemAtPath:error:
// removeItemAtURL:error:
// removeLastObject
// removeObject:
// removeObjectAtIndex:
// removeObjectForKey:
// removePersistentDomainForName:
// removeSpaceAndNewline
// renderInContext:
// replaceObjectAtIndex:withObject:
// reqText
// reqUrl
// requestImageForAsset:targetSize:contentMode:options:resultHandler:
// requestWithURL:
// requireGestureRecognizerToFail:
// reset
// resetRightBarItem
// resetStatistics
// resetTextWidth
// respondsToSelector:
// resume
// retText
// retain
// retainCount
// returnToOriginalMsg:
// rightAnchor
// rightBarButtonItems
// rightBarButtonWithSelectCount:
// rightToLeft_UIScreenEdgePanGestureRecognizer
// rootViewController
// rowActionWithStyle:title:handler:
// safeAreaLayoutGuide
// saveEmoticonToEmoticonDirForMd5:data:isCleanable:
// scale
// scaleToFillSize:
// scanHexInt:
// scannerWithString:
// scheduledTimerWithTimeInterval:repeats:block:
// screenEdgePanGestureRecognizer
// screenHeightCurOri
// screenWidthCurOri
// scrollViewInteractivePanGesture
// searchBar
// searchController
// searcher
// second
// sectionInfoHeader:
// sectionInfoHeader:Footer:
// sections
// seekToNextFrame
// selectView
// selectedSegmentIndex
// selectedViewController
// self
// sendButtonTapped:
// sendSubviewToBack:
// sendVideoJsEvent:param:
// sessionWithConfiguration:
// setAccessibilityLabel:
// setAccessibilityTraits:
// setAccessoryView:
// setAction:
// setActive:
// setActive:animated:completion:
// setActivity:
// setActivityHandler:
// setActivityIndicatorViewStyle:
// setAdjustsFontSizeToFitWidth:
// setAlignment:
// setAllowsFloats:
// setAllowsMultipleSelection:
// setAllowsMultipleSelectionDuringEditing:
// setAlpha:
// setAlwaysDiscardsLateVideoFrames:
// setAppData:
// setAppID:
// setAppName:
// setAttachementID:
// setAttributedText:
// setAttributes:ofItemAtPath:error:
// setAuthImageData:
// setAuthName:
// setAutoAddFriendReply:
// setAutoDownloadGroupList:
// setAutoLikeMode:
// setAutoRotatePortraitAtPresent:
// setAutomaticZDSKReceiptText:
// setAutoresizingMask:
// setBForbidProgressBarAutoHidden:
// setBNeedAnimation:
// setBShowLocation:
// setBUsePanCancelGesture:
// setBackgRoundBlurLevel:
// setBackgroundColor:
// setBackgroundImage:
// setBackgroundLockVisible:
// setBannerTitle:
// setBannerView:
// setBaselineAdjustment:
// setBorderStyle:
// setBubbleFolderName:
// setBundleID:
// setCancelButtonDidClickBlock:
// setCellEnabled:
// setCellMode:
// setCenter:
// setChangedCSSStr:
// setChangedChatCSSStr:
// setChangedSteps:
// setChangedVoiceTime:
// setClientMsgId:
// setClipsToBounds:
// setCodeDecodedString:
// setCodeTypeName:
// setCodeVersion:
// setCommentID:
// setCompletionWithItemsHandler:
// setConfirmCallBack:
// setContact:remark:
// setContact:sessionTop:sync:
// setContent:
// setContentHorizontalAlignment:
// setContentInset:
// setContentMode:
// setContentOffset:
// setCornerRadius:
// setCount:
// setCreateTime:
// setCurLanguage:shouldChangeMainFrame:
// setCustomView:
// setDateFormat:
// setDatePickerMode:
// setDateStyle:
// setDay:
// setDelegate:
// setDetents:
// setDimsBackgroundDuringPresentation:
// setDisable:
// setDisableBQTX:
// setDisableDBFXL:
// setDisableDHYMSYS:
// setDisableDYHKYK:
// setDisableDYHLBGG:
// setDisableEmoticonBoardCamera:
// setDisableEmoticonBoardRecentUse:
// setDisableEmoticonBoardSearch:
// setDisableFoldWithPYQ:
// setDisableFullVideoTapClose:
// setDisableHYDTSP:
// setDisableHomeSlideDelete:
// setDisableJMFGX:
// setDisableLLTHJG:
// setDisableMeViewEmojiPure:
// setDisableMeViewFavoritesPure:
// setDisableMeViewKBPure:
// setDisableMeViewPYQPure:
// setDisableMeViewPayPure:
// setDisableMeViewSPHPure:
// setDisablePYP:
// setDisablePYQGG:
// setDisablePYQSKYK:
// setDisablePYQShowSource:
// setDisableQZYSMC:
// setDisableQuickForward:
// setDisableSYSSGN:
// setDisableSettingViewCJPure:
// setDisableSettingViewDSFXXGXQDPure:
// setDisableSettingViewGHPure:
// setDisableSettingViewGRXXSJQDPure:
// setDisableSettingViewGRXXYQXPure:
// setDisableSettingViewQSNPure:
// setDisableVideoFrontCameraMirror:
// setDisableWWanAutoDownloadMedia:
// setDisableXCXQDGG:
// setDisableXLXCX:
// setDisableXXYQTSBZXTS:
// setDisableYYNQTSBZXTS:
// setDisableZJSRZT:
// setDisabled:
// setEdges:
// setEditing:animated:
// setEditingStyle:
// setEmojiInfoObj:
// setEnableAllowYourSelf:
// setEnableAppMsgAgain:
// setEnableAutoDownloadMedia:
// setEnableAutoDownloadMediaWithFile:
// setEnableAutoDownloadMediaWithPhoto:
// setEnableAutoDownloadMediaWithVideo:
// setEnableBJDZPYQ:
// setEnableBackgRoundBlur:
// setEnableBlockBlockedLinks:
// setEnableCAJTFSXCKJFS:
// setEnableCQHSZZB:
// setEnableCallDetermine:
// setEnableCallkit:
// setEnableCardMsgAgain:
// setEnableChangeCSS:
// setEnableChangeChatCSS:
// setEnableChangeSteps:
// setEnableDHJXDYSP:
// setEnableDHLTPKJZFZPYQ:
// setEnableDHNWBFC:
// setEnableDHYSJKJSSJL:
// setEnableDragToClose:
// setEnableEdgeSlideToClose:
// setEnableEmojiMsgAgain:
// setEnableFSXXH:
// setEnableFavoritesVoiceForward:
// setEnableFileMsgAgain:
// setEnableFileToVoice:
// setEnableFriendCheck:
// setEnableHDXJMS:
// setEnableIconCircular:
// setEnableImageAddEmojiInEssay:
// setEnableImageAddEmojiInMsg:
// setEnableImageMsgAgain:
// setEnableIsAutoRedEnvelop:
// setEnableIsMeRedEnvelope:
// setEnableIsPrivateChatRedEnvelope:
// setEnableJBXXLDYH:
// setEnableJoker:
// setEnableKJHCJPTX:
// setEnableKJWJZ:
// setEnableKJXGBZ:
// setEnableKJZFPYQTP:
// setEnableMRXZYT:
// setEnableMemberExitMonitoring:
// setEnableMsgIconCircular:
// setEnableNoteMsgAgain:
// setEnablePYQSPJDT:
// setEnablePYQSafari:
// setEnablePYQZDDZ:
// setEnableQJHBXXTX:
// setEnableQJZZXXTX:
// setEnableQuickSearchTextEmoticons:
// setEnableRecordMsgAgain:
// setEnableRedEnvelopAutoReply:
// setEnableRedEnvelopAutoReplyInGroup:
// setEnableRedEnvelopeDetail:
// setEnableRightToLeftGesture:
// setEnableSRKZWF:
// setEnableSWYZJS:
// setEnableSafari:
// setEnableSaveEmoji:
// setEnableShortcutReceive:
// setEnableShowDelComment:
// setEnableShowWXID:
// setEnableShowmyqrcode:
// setEnableShowopen_Receive_Money:
// setEnableShowopen_XCX:
// setEnableShowqrcode:
// setEnableShowreceive_pay:
// setEnableSimulateCameraScanQR:
// setEnableTextMsgAgain:
// setEnableTextToVoice:
// setEnableTingMsgAgain:
// setEnableVideoMsgAgain:
// setEnableVideoToVoice:
// setEnableVoiceForward:
// setEnableVoiceListManager:
// setEnableVoiceMsgAgain:
// setEnableVoiceToFile:
// setEnableXCXSPGGJS:
// setEnableXXFCH:
// setEnableXZWSX:
// setEnableYJQKPYQ:
// setEnableYJYDXX:
// setEnableZDDQTOP:
// setEnableZDSK:
// setEnableZDSKReply:
// setEnableZDSKReplyInGroup:
// setEnableZDSKYYBB:
// setEnableZDTYHYQQ:
// setEnableZDYZJS:
// setEnabled:
// setEnterBackgroundDate:
// setFileSize:
// setFileType:
// setFont:
// setFontDirectory:with:
// setFontconfigConfigurationPath:
// setFooterLabel:
// setFooterView:
// setFrame:
// setFrameX:
// setFromShareAction:
// setFromShareFileAction:
// setFromShortcutAction:
// setFullUrl:
// setHeaderView:
// setHeight:
// setHidden:
// setHiddenBottomTool:
// setHidesNavigationBarDuringPresentation:
// setHidesSearchBarWhenScrolling:
// setHidesWhenStopped:
// setHintLabel:
// setHour:
// setIconImage:
// setIconImg:
// setImage:
// setImage:forState:
// setImage:isLongOriginImage:
// setImageTransDataJsonStr:
// setInitAutoDownloadSettings:
// setInitBubbleFolderSettings:
// setInitEnableSettings:
// setInitRedEnvelopesSettings:
// setInitShortcutSettings:
// setInitVoiceSettings:
// setIsAccessibilityElement:
// setIsAllowTapBgMaskToClose:
// setIsAutoLikeUser:
// setIsRedEnvelopGroupFiter:
// setIsRedEnvelopTextFiter:
// setIsUnSafe:
// setItems:
// setLeftBarButtonItem:
// setLikeCount:
// setLikeUsers:
// setLineBreakMode:
// setLineSpacing:
// setLogDelegate:
// setLogLevel:
// setLoginMode:
// setM_actionType:
// setM_bFromWCList:
// setM_bIsTop:
// setM_bMultiSelect:
// setM_bNew:
// setM_bShowContactTag:
// setM_bShowHistoryGroup:
// setM_bShowRadarCreateRoom:
// setM_bShowSearchByName:
// setM_bShowSearchByTime:
// setM_commonSearchScene:
// setM_delegate:
// setM_dicIgnoreContact:
// setM_dicMultiSelect:
// setM_dtVoice:
// setM_eMsgSearchHelperScene:
// setM_emoticonAddLogic:
// setM_extendInfoWithMsgType:
// setM_image:
// setM_n64MesSvrID:
// setM_nsChatRoomUserName:
// setM_nsCity:
// setM_nsContent:
// setM_nsControlTransationID:
// setM_nsCountry:
// setM_nsCurrentUserName:
// setM_nsEmoticonMD5:
// setM_nsFeeDesc:
// setM_nsFromUsr:
// setM_nsID:
// setM_nsImageName:
// setM_nsPagePath:
// setM_nsProducetDesc:
// setM_nsProvince:
// setM_nsReceiverUserName:
// setM_nsTicket:
// setM_nsTitle:
// setM_nsTitleID:
// setM_nsToUsr:
// setM_nsTranferMoneyString:
// setM_nsTransferID:
// setM_nsUsrName:
// setM_oSelectedMessageWrap:
// setM_oVerifyContact:
// setM_pay_msg_type:
// setM_pbRequest:
// setM_scene:
// setM_transferScene:
// setM_uiCgi:
// setM_uiCreateTime:
// setM_uiEffectiveDate:
// setM_uiFeeType:
// setM_uiGameContent:
// setM_uiGroupScene:
// setM_uiMesLocalID:
// setM_uiPayChannel:
// setM_uiPayScene:
// setM_uiScene:
// setM_uiSex:
// setM_uiStatus:
// setM_uiTotalFee:
// setM_uiTransferInvalidTime:
// setM_uiType:
// setM_uiVideoSource:
// setM_uiVoiceEndFlag:
// setM_uiVoiceFormat:
// setM_uiVoiceTime:
// setM_uiWCFlag:
// setM_viewcontrllerTitle:
// setMasksToBounds:
// setMaxConcurrentOperationCount:
// setMaximumDate:
// setMaximumTrackTintColor:
// setMaximumValue:
// setMd5:
// setMenuItemType:
// setMinimumPressDuration:
// setMinimumTrackTintColor:
// setMinimumValue:
// setMinute:
// setModalPresentationStyle:
// setMonth:
// setName:
// setNavBarBackgroundColor:
// setNavLeftStyle:
// setNickname:
// setNsTitle:
// setNsTransferMoney:
// setNumberOfLines:
// setNumberOfTouchesRequired:
// setOImage:
// setObject:forKey:
// setObject:forKey:inDomain:
// setObject:forKeyedSubscript:
// setObscuresBackgroundDuringPresentation:
// setOnTintColor:
// setOpen_XCXIDStr:
// setOpen_XCXNameStr:
// setOpen_XCXPathStr:
// setOrigTime:
// setOriginalSpecifiers:
// setOutputFileType:
// setOutputURL:
// setPageSheetGestureRecognizerDelegate:
// setParams:
// setPersistentDomain:forName:
// setPitchMultiplier:
// setPlaceHolder:
// setPlaceHolderList:
// setPlaceholder:
// setPlaceorderReserves:
// setPreferenceValue:specifier:
// setPreferredCornerRadius:
// setPrefersEdgeAttachedInCompactHeight:
// setPrefersScrollingExpandsWhenScrolledToEdge:
// setProperty:forKey:
// setRate:
// setRedEnvelopAutoReplyStr:
// setRedEnvelopDelayTime:
// setRequestKeyWindow:
// setRightBarButtonItem:
// setRightBarButtonItems:
// setSampleBufferDelegate:queue:
// setSearchController:
// setSearchResultsUpdater:
// setSearchText:
// setSecond:
// setSelAction:
// setSelectView:
// setSelectedSegmentIndex:
// setSelectionStyle:
// setShadowImage:forToolbarPosition:
// setShakeToTimeLineMode:
// setShareFileAnnotation:
// setShareFileSource:
// setShareFileURL:
// setShortcutItem:
// setShortcutItems:
// setShouldReverseTranslation:
// setShouldShowFileExtensions:
// setShowVoiceListManagerButtonMode:
// setSize:
// setSource:
// setSourceView:
// setSpecifiers:
// setStatisticsDelegate:
// setString:
// setSynchronous:
// setTableFooterView:
// setTableHeaderView:
// setTag:
// setText:
// setTextAlignment:
// setTextColor:
// setTextFieldDefaultText:
// setTextStyle:
// setThumb_path:
// setTimeFormat:
// setTimeMode:
// setTimeStyle:
// setTintColor:
// setTitle:
// setTitle:forState:
// setTitleColor:forState:
// setTitleView:
// setToUserName:
// setTranslatesAutoresizingMaskIntoConstraints:
// setTranslucent:
// setType:
// setUnlockBtn:
// setUploadImgMd5:
// setUploadInfoObj:
// setUserInfo:
// setUserInteractionEnabled:
// setUsername:
// setValue:
// setValue:forKey:
// setValues:titles:
// setVersion:
// setVideoSettings:
// setVideo_path:
// setVideo_time:
// setWcOrigin:
// setWidth:
// setYear:
// setYoType:
// setZddqTOPModeNSInteger:
// settingReceiveSelfRedEnvelop:
// setupForShortcut
// shakeToTimeLineMode
// shakeToTimeLineModeAction:
// shareFileAnnotation
// shareFileSource
// shareFileURL
// sharedApplication
// sharedInstance
// sharedPhotoLibrary
// sheetPresentationController
// shortValue
// shortcutItem
// shortcutItems
// show
// showAutoDownloadGroupList
// showAutoUserList
// showBlackList
// showChangedAddFriendReply
// showChangedAutoReplyStr
// showChangedCSSInput
// showChangedChatCSSInput
// showChangedStepInput
// showChangedVoiceTime
// showChangedWeAppID
// showChangedWeAppName
// showChangedWeAppPath
// showCheckFriendsSettings
// showCheckUnContactedFriendsSettings
// showDoneToastWithText:
// showErrorToastWithText:
// showFriendsCheckSettingsController
// showInView:
// showSearchEmoticonViewController:
// showTextFieldWithMaxLen:
// showVoiceListManagerButtonMode
// showWithAnimated:
// size
// sizeThatFits:
// skipDescendants
// sliderLabel
// sortUsingComparator:
// sortUsingSelector:
// speakUtterance:
// specifier
// specifierAtIndexPath:
// speechUtteranceWithString:
// speed
// standardUserDefaults
// standardizedURL
// startAccessingSecurityScopedResource
// startAddEmoticonWithWrap:
// startAnimating
// startBlurView
// startDownloadFavoritesItem:IsPriority:
// startHeight
// startImageUploadAndDetect:
// startLoading
// startLoadingNonBlock
// startLoadingWithText:
// startRunning
// startTime
// state
// statisticsBitrate
// statisticsCallback:
// statisticsFps
// statisticsFrameNumber
// statisticsQuality
// statisticsSize
// statisticsSpeed
// statisticsTime
// status
// stepperLabel
// stop
// stopAccessingSecurityScopedResource
// stopLoading
// stopLoadingWithOKText:
// stopRunning
// streamArray
// string
// stringByAddingPercentEncodingWithAllowedCharacters:
// stringByAppendingPathComponent:
// stringByAppendingPathExtension:
// stringByAppendingString:
// stringByDeletingLastPathComponent
// stringByDeletingPathExtension
// stringByRemovingPercentEncoding
// stringByReplacingOccurrencesOfString:withString:
// stringByReplacingSpecialCharactor
// stringByTrimmingCharactersInSet:
// stringEncodingForData:encodingOptions:convertedString:usedLossyConversion:
// stringForKey:
// stringFromDate:
// stringValue
// stringWithCString:encoding:
// stringWithCapacity:
// stringWithFormat:
// stringWithString:
// stringWithUTF8String:
// substringFromIndex:
// substringToIndex:
// substringWithRange:
// subviews
// superclass
// superview
// suspend
// svgImageNamed:size:color:
// svgName:Size:
// switchCellForSel:target:title:on:
// switchPrivateRedEnvelop:
// switchRedEnvelop:
// switchRedEnvelopeDetails:
// synchronize
// systemFontOfSize:
// table
// tableHeaderView
// tableView
// tableViewMgr
// tableViewTailColor
// tag
// tapCellWithSpecifier:
// terminateWithSuccess
// text
// textFields
// textView
// tid
// time
// timeFormat
// timeFormatAction:
// timeIntervalSince1970
// timeMode
// timeModeAction:
// timeoutNumber
// tintColor
// tipsForUse:
// tipsMoneyMsgWithWrap:
// title
// titleLabel
// toast
// toolPanelView
// toolView
// topAnchor
// topMostController
// topSessions
// trailingAnchor
// traitCollectionWithDisplayScale:
// traitCollectionWithTraitsFromCollections:
// traitCollectionWithUserInterfaceStyle:
// translationInView:
// type
// unLikeObject:ofUser:extraInfo:
// unarchivedObjectOfClass:fromData:error:
// unlock
// unlockBtn
// unlockForConfiguration
// unsignedIntValue
// unsignedLongLongValue
// unsignedLongValue
// unzipEntityName:fromFilePath:error:
// unzipFileAtPath:toDestination:
// unzipFileAtPath:toDestination:delegate:
// unzipFileAtPath:toDestination:overwrite:password:error:
// unzipFileAtPath:toDestination:overwrite:password:error:delegate:
// unzipFileAtPath:toDestination:overwrite:password:progressHandler:completionHandler:
// unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:
// unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:
// unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:
// unzipFileAtPath:toDestination:progressHandler:completionHandler:
// update:
// updateData:
// updateHomePageTail:
// updateLayouts
// updateNumber:
// updateSearchResultsWithText:
// updateTitleLabel
// updateUserProfile
// uppercaseString
// useZip64
// userInterfaceIdiom
// username
// value
// valueForKey:
// valueForKeyPath:
// valueWithBytes:objCType:
// videoFps
// videoFrameNumber
// videoPath
// videoQuality
// view
// viewControllers
// viewDidAppear:
// viewDidLoad
// viewModel
// viewWillAppear:
// visibleHeight:
// visibleViewController
// webviewController
// whiteColor
// whitespaceAndNewlineCharacterSet
// width
// widthAnchor
// windows
// writeData:filename:compressionLevel:password:AES:
// writeData:filename:withPassword:
// writeFile:withPassword:
// writeFileAtPath:withFileName:compressionLevel:password:AES:
// writeFileAtPath:withFileName:withPassword:
// writeFolderAtPath:withFolderName:withPassword:
// writeSymlinkFileAtPath:withFileName:compressionLevel:password:AES:
// writeToFile:atomically:
// writeToFile:atomically:encoding:error:
// xmlForMessageWrapContent
// year
// zddqTOPModeNSInteger
// zipArchiveDidUnzipArchiveAtPath:zipInfo:unzippedPath:
// zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:fileInfo:
// zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:unzippedFilePath:
// zipArchiveProgressEvent:total:
// zipArchiveShouldUnzipFileAtIndex:totalFiles:archivePath:fileInfo:
// zipArchiveWillUnzipArchiveAtPath:zipInfo:
// zipArchiveWillUnzipFileAtIndex:totalFiles:archivePath:fileInfo:
// zipInfo:setAttributesOfItemAtPath:
// zipInfo:setDate:
// zone
