// 自动恢复的 Objective-C 接口骨架
#import <Foundation/Foundation.h>

@interface $$ : NSObject
@end

@interface AABCustomDashStyleEditorViewController : NSObject
@end

@interface AABCustomDashStyleHelpViewController : NSObject
@end

@interface AABCustomDashStyleListViewController : NSObject
@end

@interface AABDateTimeCustomEditorViewController : NSObject
@end

@interface AVAudioPlayerDelegate : NSObject
@end

@interface Appearance : NSObject
@end

@interface BannerNotifyBeautifyViewController : NSObject
@end

@interface CAAnimationDelegate : NSObject
@end

@interface CRParallaxLighting : NSObject
@end

@interface CadisCardImageManagerViewController : NSObject
@end

@interface CadisCardImagePickerViewController : NSObject
@end

@interface CadisContactPickerViewController : NSObject
@end

@interface CadisCustomStyleEditorViewController : NSObject
@end

@interface CadisCustomStyleListViewController : NSObject
@end

@interface CadisHTMLAudioStoreMessageHandler : NSObject
@end

@interface CadisHTMLCalendarHapticMessageHandler : NSObject
@end

@interface CadisHTMLCalendarTapMessageHandler : NSObject
@end

@interface CadisHTMLFilePickerMessageHandler : NSObject
@end

@interface CadisHTMLLyricsMessageHandler : NSObject
@end

@interface CadisHTMLNavigationDelegate : NSObject
@end

@interface CadisHTMLUIDelegate : NSObject
@end

@interface CadisImagePickerDelegate : NSObject
@end

@interface CadisMusicSchemeHandler : NSObject
@end

@interface CadisOpenPanelDelegate : NSObject
@end

@interface CadisPHPickerDelegate : NSObject
@end

@interface CadisSettingsViewController : NSObject
@end

@interface GrayTestSettingViewController : NSObject
@end

@interface GroupOrder : NSObject
@end

@interface Members : NSObject
@end

@interface ModalDismiss : NSObject
@end

@interface NSObject : NSObject
@end

@interface NSURLSessionDelegate : NSObject
@end

@interface OBF_AIChatSettingViewController : NSObject
@end

@interface PHPickerViewControllerDelegate : NSObject
@end

@interface PersonalOBF_CoversSettingViewController : NSObject
@end

@interface SHTMOuterGlowOverlayView : NSObject
@end

@interface UIBarPositioningDelegate : NSObject
@end

@interface UICollectionViewDataSource : NSObject
@end

@interface UICollectionViewDelegate : NSObject
@end

@interface UICollectionViewDelegateFlowLayout : NSObject
@end

@interface UIColorPickerViewControllerDelegate : NSObject
@end

@interface UIDocumentPickerDelegate : NSObject
@end

@interface UIGestureRecognizerDelegate : NSObject
@end

@interface UIImagePickerControllerDelegate : NSObject
@end

@interface UINavigationControllerDelegate : NSObject
@end

@interface UIScrollViewDelegate : NSObject
@end

@interface UISearchBarDelegate : NSObject
@end

@interface UITableViewDataSource : NSObject
@end

@interface UITableViewDelegate : NSObject
@end

@interface UITextFieldDelegate : NSObject
@end

@interface UITextViewDelegate : NSObject
@end

@interface UIViewControllerAnimatedTransitioning : NSObject
@end

@interface WKNavigationDelegate : NSObject
@end

@interface WKScriptMessageHandler : NSObject
@end

@interface WKUIDelegate : NSObject
@end

@interface WKURLSchemeHandler : NSObject
@end

@interface WeChatPluginHelperV2 : NSObject
@end

@interface XOSLoader : NSObject
@end

@interface XZYAvatarAboveBubbleSettingsViewController : NSObject
@end

@interface XZYBubblePetAnimationDelegate : NSObject
@end

@interface XZYCLGBadgeLabel : NSObject
@end

@interface XZYCLGCustomGroupEditorViewController : NSObject
@end

@interface XZYCLGDividerAppearanceViewController : NSObject
@end

@interface XZYCLGDividerGestureTarget : NSObject
@end

@interface XZYCLGEntry : NSObject
@end

@interface XZYCLGGroupOrderViewController : NSObject
@end

@interface XZYCLGPlan : NSObject
@end

@interface XZYCLGSessionPickerViewController : NSObject
@end

@interface XZYCLGSideRailAppearanceViewController : NSObject
@end

@interface XZYCLGSideRailButton : NSObject
@end

@interface XZYCLGSideRailView : NSObject
@end

@interface XZYCLGUnreadBadge : NSObject
@end

@interface XZYChatListGroupingSettingsViewController : NSObject
@end

@interface XZYColorPickerViewController : NSObject
@end

@interface XZYDLBubbleView : NSObject
@end

@interface XZYDesktopLyricsSettingsViewController : NSObject
@end

@interface XZYDockHTMLBridge : NSObject
@end

@interface XZYDockTapTarget : NSObject
@end

@interface XZYFvURLSessionDelegate : NSObject
@end

@interface XZYHSBGradientView : NSObject
@end

@interface XZYHighRefreshDriver : NSObject
@end

@interface XZYHighRefreshFPSView : NSObject
@end

@interface XZYHomeDockButton : NSObject
@end

@interface XZYHomeDockConcaveContainer : NSObject
@end

@interface XZYHomeDockCustomStyleEditorViewController : NSObject
@end

@interface XZYHomeDockCustomStyleListController : NSObject
@end

@interface XZYHomeDockFloatingSpreadPopup : NSObject
@end

@interface XZYHomeDockLongPressTarget : NSObject
@end

@interface XZYHomeDockPanSelectTarget : NSObject
@end

@interface XZYHomeDockPopupBg : NSObject
@end

@interface XZYHomeDockSwipePopup : NSObject
@end

@interface XZYHomeNPPickerVC : NSObject
@end

@interface XZYHueStripView : NSObject
@end

@interface XZYMesReferRoundedSettingsViewController : NSObject
@end

@interface XZYPushAnimator : NSObject
@end

@interface XZYWeakObjectBox : NSObject
@end

@interface _0x11806c41 : NSObject
@end

@interface _0x13e34bd4 : NSObject
@end

@interface _0x2f19de29 : NSObject
@end

// 未可靠归属到具体类的 selector：
// .cxx_destruct
// AddLocalMsg:MsgWrap:
// AddMsg:MsgWrap:
// AsyncOnAddMsg:MsgWrap:
// CGColor
// CGImage
// CGPath
// CGPointValue
// CGRectValue
// GetContact
// GetMessageFromImage:
// JSONObjectWithData:options:error:
// PushOtherBaseMsgControllerByContact:navigationController:animated:
// PushViewController:animated:
// ResendVoiceMsg:MsgWrap:
// ScrollToBottomAnimated:
// SearchBarBecomeUnActive
// ShowPageSheetLogicControllerByContact:pageSheetDelegate:fromViewController:animated:
// T#,R
// T@"AVAudioPlayer",&,N,V_audioPlayer
// T@"NSArray",C,N,V_allSessionEntries
// T@"NSArray",C,N,V_allSessions
// T@"NSArray",C,N,V_dividerEntries
// T@"NSArray",C,N,V_entries
// T@"NSArray",C,N,V_filteredSessions
// T@"NSArray",C,N,V_orderedButtons
// T@"NSDictionary",C,N,V_availableTags
// T@"NSLayoutConstraint",&,N,V_previewChevronTrailing
// T@"NSLayoutConstraint",&,N,V_previewLeading
// T@"NSMutableArray",&,N,V_allContacts
// T@"NSMutableArray",&,N,V_bgSoundList
// T@"NSMutableArray",&,N,V_cardImages
// T@"NSMutableArray",&,N,V_categoryNames
// T@"NSMutableArray",&,N,V_coverImages
// T@"NSMutableArray",&,N,V_favoriteColors
// T@"NSMutableArray",&,N,V_filteredContacts
// T@"NSMutableArray",&,N,V_gids
// T@"NSMutableArray",&,N,V_imageNames
// T@"NSMutableArray",&,N,V_images
// T@"NSMutableArray",&,N,V_nameplateImages
// T@"NSMutableArray",&,N,V_personalCoverImages
// T@"NSMutableArray",&,N,V_searchResults
// T@"NSMutableArray",&,N,V_selectedOrder
// T@"NSMutableArray",&,N,V_voiceList
// T@"NSMutableDictionary",&,N,V_contactCoverMappings
// T@"NSMutableDictionary",&,N,V_voiceCategories
// T@"NSMutableDictionary",&,N,V_wxidToGid
// T@"NSMutableDictionary",&,N,V_wxidToOrigIndexPath
// T@"NSMutableDictionary",&,N,V_wxidToUnreadContribution
// T@"NSMutableDictionary",&,N,V_wxidToVisualRow
// T@"NSMutableSet",&,N,V_selected
// T@"NSString",&,N,V_currentCategory
// T@"NSString",&,N,V_customApiUrl
// T@"NSString",&,N,V_messagePrefix
// T@"NSString",&,N,V_messageSuffix
// T@"NSString",&,N,V_previewingVoiceId
// T@"NSString",&,N,V_selectedBgSound
// T@"NSString",&,N,V_selectedCoverName
// T@"NSString",&,N,V_selectedNameplateName
// T@"NSString",&,N,V_selectedStyleName
// T@"NSString",&,N,V_selectedVoice
// T@"NSString",&,N,V_selectedVoiceName
// T@"NSString",&,N,V_styleName
// T@"NSString",&,N,V_styleType
// T@"NSString",&,N,V_systemPrompt
// T@"NSString",&,N,V_triggerPrefix
// T@"NSString",?,R,C
// T@"NSString",C,N,V_configurationSignature
// T@"NSString",C,N,V_currentSelected
// T@"NSString",C,N,V_darkColorHex
// T@"NSString",C,N,V_editingDarkHex
// T@"NSString",C,N,V_editingLightHex
// T@"NSString",C,N,V_groupId
// T@"NSString",C,N,V_groupName
// T@"NSString",C,N,V_lightColorHex
// T@"NSString",C,N,V_pendingIconGroupId
// T@"NSString",C,N,V_pickerTitle
// T@"NSString",C,N,V_searchTextLower
// T@"NSString",C,N,V_tagFilter
// T@"NSString",C,N,V_targetNickName
// T@"NSString",C,N,V_targetUserName
// T@"NSString",C,N,V_userName
// T@"NSString",C,N,V_xzy_actionId
// T@"NSString",R,C
// T@"UIActivityIndicatorView",&,N,V_loadingIndicator
// T@"UIBarButtonItem",&,N,V_previewButtonItem
// T@"UIButton",&,N,V_tagFilterButton
// T@"UICollectionView",&,N,V_collectionView
// T@"UIColor",&,N,V_glowColor
// T@"UIImageView",&,N,V_iconView
// T@"UIImageView",&,N,V_previewChevron
// T@"UILabel",&,N,V_aValueLabel
// T@"UILabel",&,N,V_apiHintLabel
// T@"UILabel",&,N,V_bValueLabel
// T@"UILabel",&,N,V_chevronValueLabel
// T@"UILabel",&,N,V_countLabel
// T@"UILabel",&,N,V_fallbackLabel
// T@"UILabel",&,N,V_fontValueLabel
// T@"UILabel",&,N,V_gValueLabel
// T@"UILabel",&,N,V_hintLabel
// T@"UILabel",&,N,V_offsetValueLabel
// T@"UILabel",&,N,V_previewErrLabel
// T@"UILabel",&,N,V_previewLabel
// T@"UILabel",&,N,V_rValueLabel
// T@"UILabel",&,N,V_sizeValueLabel
// T@"UILabel",&,N,V_titleLabel
// T@"UILabel",&,N,V_titleSizeValueLabel
// T@"UIScrollView",&,N,V_categoryScrollView
// T@"UIScrollView",&,N,V_scrollView
// T@"UISearchBar",&,N,V_searchBar
// T@"UISegmentedControl",&,N,V_modeSegment
// T@"UISegmentedControl",&,N,V_segmentControl
// T@"UISegmentedControl",&,N,V_typeSegment
// T@"UISlider",&,N,V_aSlider
// T@"UISlider",&,N,V_bSlider
// T@"UISlider",&,N,V_chevronSlider
// T@"UISlider",&,N,V_fontSlider
// T@"UISlider",&,N,V_gSlider
// T@"UISlider",&,N,V_offsetSlider
// T@"UISlider",&,N,V_rSlider
// T@"UISlider",&,N,V_sizeSlider
// T@"UISlider",&,N,V_titleSizeSlider
// T@"UISwitch",&,N,V_chevronSwitch
// T@"UISwitch",&,N,V_mainSwitch
// T@"UITabBar",W,N,V_tabBar
// T@"UITabBar",W,N,V_xzy_tabBar
// T@"UITableView",&,N,V_tableView
// T@"UITableView",W,N,V_mainTableView
// T@"UITextField",&,N,V_hexField
// T@"UITextView",&,N,V_codeView
// T@"UITextView",&,N,V_contentView
// T@"UIView",&,N,V_headerView
// T@"UIView",&,N,V_hexPreview
// T@"UIView",&,N,V_indicator
// T@"UIView",&,N,V_presetContainer
// T@"UIView",&,N,V_previewContainer
// T@"UIView",&,N,V_previewStrip
// T@"UIView",W,N,V_petView
// T@"UIView",W,N,V_targetView
// T@"WKWebView",W,N,V_webView
// T@"XZYCLGEntry",&,N,V_entry
// T@"XZYCLGSideRailButton",&,N,V_previewButton
// T@"XZYCLGUnreadBadge",&,N,V_badge
// T@"XZYHSBGradientView",&,N,V_hsbView
// T@"XZYHueStripView",&,N,V_hueStrip
// T@,W,N,V_hostVC
// T@,W,N,V_value
// T@?,C,N,V_completion
// T@?,C,N,V_completionHandler
// T@?,C,N,V_handler
// T@?,C,N,V_onChanged
// T@?,C,N,V_onClear
// T@?,C,N,V_onColorChanged
// T@?,C,N,V_onDone
// T@?,C,N,V_onHueChanged
// T@?,C,N,V_onSave
// T@?,C,N,V_onSelect
// T@?,C,N,V_onTap
// T@?,C,N,V_onVoiceSelected
// TB,N,V_allFriendsEnabled
// TB,N,V_currentChevronHidden
// TB,N,V_customApiEnabled
// TB,N,V_fired
// TB,N,V_groupNoAtEnabled
// TB,N,V_hasPreviewed
// TB,N,V_isBrandServiceHolder
// TB,N,V_isDarkMode
// TB,N,V_isDivider
// TB,N,V_isFolded
// TB,N,V_isLoading
// TB,N,V_isPeerMode
// TB,N,V_isPush
// TB,N,V_isSearching
// TB,N,V_isSessionsSection
// TB,N,V_lastPreviewValid
// TB,N,V_pendingSideRailIcon
// TB,N,V_previewMode
// TB,N,V_updatingFromCode
// TI,N,V_settingsVersion
// TQ,R
// Td,N,V_bgVolume
// Td,N,V_brightness
// Td,N,V_currentA
// Td,N,V_currentB
// Td,N,V_currentChevronOffset
// Td,N,V_currentFontSize
// Td,N,V_currentG
// Td,N,V_currentIconSize
// Td,N,V_currentOffset
// Td,N,V_currentR
// Td,N,V_currentTitleSize
// Td,N,V_glowRadius
// Td,N,V_hue
// Td,N,V_iconSize
// Td,N,V_imageSize
// Td,N,V_lastPreviewAt
// Td,N,V_saturation
// Td,N,V_speechRate
// Td,N,V_titleFontSize
// Td,N,V_volume
// Tq,N,V_editIndex
// Tq,N,V_filterMode
// Tq,N,V_groupCount
// Tq,N,V_lineType
// Tq,N,V_origRow
// Tq,N,V_origRowCount
// Tq,N,V_origSection
// Tq,N,V_typeFilter
// Tq,N,V_unreadCount
// Tq,N,V_xzy_tabIndex
// UIEdgeInsetsValue
// URL
// URLAssetWithURL:options:
// URLPathAllowedCharacterSet
// URLQueryAllowedCharacterSet
// URLSession:didBecomeInvalidWithError:
// URLSession:didReceiveChallenge:completionHandler:
// URLSessionDidFinishEventsForBackgroundURLSession:
// URLWithString:
// UUID
// UUIDString
// _aSlider
// _aValueLabel
// _allContacts
// _allFriendsEnabled
// _allSessionEntries
// _allSessions
// _apiHintLabel
// _audioPlayer
// _availableTags
// _bSlider
// _bValueLabel
// _badge
// _bgImageView
// _bgSoundList
// _bgVolume
// _brightness
// _cachedButtons
// _capsule
// _cardImages
// _categoryNames
// _categoryScrollView
// _chevronSlider
// _chevronSwitch
// _chevronValueLabel
// _clockTimer
// _codeView
// _collectionView
// _completion
// _completionHandler
// _configurationSignature
// _contactCoverMappings
// _contentView
// _countLabel
// _coverImages
// _currentA
// _currentB
// _currentCategory
// _currentChevronHidden
// _currentChevronOffset
// _currentFontSize
// _currentG
// _currentIconSize
// _currentOffset
// _currentR
// _currentSelected
// _currentText
// _currentTitleSize
// _customApiEnabled
// _customApiUrl
// _darkColorHex
// _dividerEntries
// _editIndex
// _editingDarkHex
// _editingLightHex
// _entries
// _entry
// _fallbackLabel
// _favoriteColors
// _filterMode
// _filteredContacts
// _filteredSessions
// _fired
// _fontSlider
// _fontValueLabel
// _gSlider
// _gValueLabel
// _gids
// _glowColor
// _glowRadius
// _groupCount
// _groupId
// _groupName
// _groupNoAtEnabled
// _handler
// _hasPreviewed
// _headerView
// _hexField
// _hexPreview
// _hintLabel
// _hostVC
// _hsbView
// _hue
// _hueStrip
// _iconSize
// _iconView
// _imageNames
// _imageSize
// _imageWithCGSVGDocument:
// _images
// _indicator
// _isBrandServiceHolder
// _isDarkMode
// _isDivider
// _isFolded
// _isLoading
// _isPeerMode
// _isPush
// _isSearching
// _isSessionsSection
// _isSwiping
// _lastPanTab
// _lastPreviewAt
// _lastPreviewValid
// _lightColorHex
// _lineType
// _loadingIndicator
// _mainSwitch
// _mainTableView
// _messagePrefix
// _messageSuffix
// _modeSegment
// _nameplateImages
// _offsetSlider
// _offsetValueLabel
// _onChanged
// _onClear
// _onColorChanged
// _onDone
// _onHueChanged
// _onSave
// _onSelect
// _onTap
// _onVoiceSelected
// _orderedButtons
// _origRow
// _origRowCount
// _origSection
// _originalSelectedIndex
// _otherLine1Field
// _otherLine2Field
// _otherPreview1Label
// _otherPreview2Label
// _pendingIconGroupId
// _pendingSideRailIcon
// _personalCoverImages
// _petView
// _pickerTitle
// _presetContainer
// _previewButton
// _previewButtonItem
// _previewChevron
// _previewChevronTrailing
// _previewContainer
// _previewErrLabel
// _previewLabel
// _previewLeading
// _previewMode
// _previewStrip
// _previewingVoiceId
// _rSlider
// _rValueLabel
// _realPlayWithMusicInfo:musicDataUrl:cacheUrl:cacheId:
// _renderMode
// _saturation
// _scrollView
// _searchBar
// _searchResults
// _searchTextLower
// _segmentControl
// _selected
// _selectedBgSound
// _selectedCoverName
// _selectedNameplateName
// _selectedOrder
// _selectedStyleName
// _selectedVoice
// _selectedVoiceName
// _selfLine1Field
// _selfLine2Field
// _selfPreview1Label
// _selfPreview2Label
// _settingsVersion
// _sizeSlider
// _sizeValueLabel
// _speechRate
// _styleName
// _styleType
// _swipeSelectedIndex
// _swipeSelectedRow
// _systemPrompt
// _tabBar
// _tableView
// _tagFilter
// _tagFilterButton
// _targetNickName
// _targetUserName
// _targetView
// _titleFontSize
// _titleLabel
// _titleSizeSlider
// _titleSizeValueLabel
// _triggerPrefix
// _tryUpgradeTheme
// _typeFilter
// _typeSegment
// _unreadCount
// _updatingFromCode
// _userName
// _value
// _voiceCategories
// _voiceList
// _volume
// _webView
// _wxidToGid
// _wxidToOrigIndexPath
// _wxidToUnreadContribution
// _wxidToVisualRow
// _xzy_actionId
// _xzy_tabBar
// _xzy_tabIndex
// aSlider
// aValueLabel
// aabEditor_alert:msg:
// aabEditor_clearPreview
// aabEditor_enterPreviewUI
// aabEditor_exitPreview
// aabEditor_keyboardWillHide:
// aabEditor_keyboardWillShow:
// aabEditor_preview
// aabEditor_save
// aabEditor_showHelp
// aabEditor_showTemplates
// aabHelp_apiReferenceText
// aabHelp_copyAll
// aabHelp_guideLineReferenceText
// aabList_addNew
// aabShowOptionPickerForRow:title:count:currentStyleKey:nameResolver:
// accessibilityIdentifier
// accessibilityLabel
// actionWithTitle:style:handler:
// actions
// activateConstraints:
// activationState
// addAction:
// addAction:name:icon:
// addAnimation:forKey:
// addArrangedSubview:
// addAttribute:value:range:
// addCell:
// addCharactersInString:
// addCoverImage
// addCurveToPoint:controlPoint1:controlPoint2:
// addCustomSwitches
// addEntriesFromDictionary:
// addFavoriteColorTapped
// addGestureRecognizer:
// addIndex:
// addInteraction:
// addLayoutManager:
// addLineToPoint:
// addMsgMergeReverseControl:toSection:tableViewInfo:
// addNameplateImage
// addNotificationObserver
// addObject:
// addObjectsFromArray:
// addObserver:selector:name:object:
// addObserverForName:object:queue:usingBlock:
// addOuterGlowOverlay
// addPersonalCoverImage
// addQuadCurveToPoint:controlPoint:
// addRotationAnimation
// addScriptMessageHandler:name:
// addSection:
// addSnowAnimation
// addSublayer:
// addSubview:
// addTarget:action:
// addTarget:action:forControlEvents:
// addTextContainer:
// addTextFieldWithConfigurationHandler:
// addTimer:forMode:
// addToRunLoop:forMode:
// addUserScript:
// administrativeArea
// aesEncrypt:key:
// aiCustomPromptSwitchChanged:
// aiInfoDisclosureForSection:row:
// aiInfoSwitchForSection:row:withSwitch:
// aiNoAtSwitchChanged:
// aiSvgInfoButtonForSection:row:
// aiSwitchChanged:
// ai_handleAIChat
// alertControllerWithTitle:message:preferredStyle:
// allContacts
// allFriendsEnabled
// allHTTPHeaderFields
// allKeys
// allObjects
// allSessionEntries
// allSessions
// allValues
// alpha
// alphanumericCharacterSet
// animateGlowBall:inBounds:
// animateTransition:
// animateWithDuration:animations:
// animateWithDuration:animations:completion:
// animateWithDuration:delay:options:animations:completion:
// animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:
// animatedImageWithImages:duration:
// animation
// animationDidStart:
// animationDidStop:finished:
// animationEnded:
// animationForKey:
// animationImages
// animationWithKeyPath:
// anyObject
// apiHintLabel
// appendAttributedString:
// appendFormat:
// appendPath:
// appendString:
// applicationDidBecomeActive:
// applicationDidFinishLaunching:
// applicationState
// applicationWillResignActive:
// applyAvatarCornerRadiusFromCell
// applyBorderAndCornerRadiusWithScaleX:scaleY:
// applyCardToCalendar:cardDir:presenter:
// applyContentColorIfNeeded
// applyCustomBackgroundColor
// applyFilter
// applyFloatingAnimationToView:delay:
// applyImageBackground
// applyNicknameColorIfNeeded
// applySidePosition:
// applySideRailLeftXOffset:rightXOffset:
// applySideScope:
// applyStickyOffSpacing:
// applyStickyTopSpacing:
// applyTransform:
// applyVideoBackground
// archivedDataWithRootObject:requiringSecureCoding:error:
// arrMenuItems
// array
// arrayForKey:
// arrayWithArray:
// arrayWithCapacity:
// arrayWithObject:
// arrayWithObjects:
// arrayWithObjects:count:
// attitude
// attributedText
// attributesOfItemAtPath:error:
// audioPlayer
// audioPlayerBeginInterruption:
// audioPlayerDecodeErrorDidOccur:error:
// audioPlayerDidFinishPlaying:successfully:
// audioPlayerEndInterruption:
// audioPlayerEndInterruption:withFlags:
// audioPlayerEndInterruption:withOptions:
// authenticationMethod
// authorizationStatusForAccessLevel:
// autorelease
// autoresizingMask
// availableTags
// avatarRotationSwitchChanged:
// bSlider
// bValueLabel
// backgroundColor
// backgroundColorButtonTapped:
// backgroundColorSwitchChanged:
// badge
// badgeLabel
// badgeValue
// bannerHeightButtonTapped:
// bannerHeightSwitchChanged:
// bannerSvgInfoButton
// bannerWidthButtonTapped:
// bannerWidthSwitchChanged:
// base64EncodedStringWithOptions:
// becomeFirstResponder
// begin
// beginEditing
// beginUpdates
// bezierPath
// bezierPathWithArcCenter:radius:startAngle:endAngle:clockwise:
// bezierPathWithCGPath:
// bezierPathWithOvalInRect:
// bezierPathWithRect:
// bezierPathWithRoundedRect:byRoundingCorners:cornerRadii:
// bezierPathWithRoundedRect:cornerRadius:
// bgBubbleInfo
// bgSoundList
// bgVolume
// blackColor
// blockOperationWithBlock:
// blueColor
// body
// boldSystemFontOfSize:
// boolForKey:
// boolValue
// borderColor
// borderColorButtonTapped:
// borderColorSwitchChanged:
// borderImageHeightOffsetButtonTapped:
// borderImageWidthOffsetButtonTapped:
// borderImageXOffsetButtonTapped:
// borderImageYOffsetButtonTapped:
// borderWidth
// borderWidthButtonTapped:
// borderWidthSwitchChanged:
// bottomAnchor
// boundingRectWithSize:options:attributes:context:
// bounds
// brightness
// bringSubviewToFront:
// bubbleCropSwitchChanged:
// bubbleEnableSwitchChanged:
// bubbleExtendAutoSwitchChanged:
// bubbleName
// bubblePetAutoAnimSwitchChanged:
// bubblePetStartFromFrontSwitchChanged:
// bubblePetSwitchChanged:
// bubbleShadowBreathSwitchChanged:
// bubbleShadowEnableSwitchChanged:
// buildUI
// buttonWithType:
// bytes
// cStringUsingEncoding:
// cadisInfoDisclosureForSection:row:
// cadisInfoSwitchForSection:row:withSwitch:
// cadisSvgInfoButtonForSection:row:
// cadis_appDidBecomeActive
// cadis_appDidEnterBackground
// cadis_calendarNextMonth
// cadis_calendarPrevMonth
// cadis_calendarTapped
// cadis_contactTapped:
// cadis_dismissCalendarPopup:
// cadis_headerNeedsRebuild
// cadis_htmlCalendarNeedsVisualCheck:
// cadis_htmlCalendarTapped:
// cadis_onlineStatusUpdated
// cadis_rebuildCalendarCard
// cadis_recoverHTMLCalendarIfNeeded
// cadis_refreshHomeHeaderAfterCalendarStyleChange
// cadis_reloadHeaderSectionForHTMLRecovery
// cadis_showCalendarPopup
// cadis_switchCalendarStyle
// cadis_toggleCalendarHoliday
// cadis_toggleMondayFirst
// cadis_toggleXiuBan
// cadis_weatherBadgeTapped
// cadis_weatherUpdated
// calendarSelectedColorPreview
// calendarWithIdentifier:
// canLoadObjectsOfClass:
// canShowReplyMessage
// cancel
// cancelPreviousPerformRequestsWithTarget:
// cancelPreviousPerformRequestsWithTarget:selector:object:
// cancelSearch
// cancelTapped
// capInsets
// capabilitiesForHardware
// cardBgColorPreview
// cardImages
// caseInsensitiveCompare:
// categoryButtonTapped:
// categoryNames
// categoryScrollView
// cellForItemAtIndexPath:
// cellForRowAtIndexPath:
// cellView
// center
// centerXAnchor
// centerYAnchor
// characterAtIndex:
// characterIsMember:
// characterRangeForGlyphRange:actualGlyphRange:
// characterSetWithCharactersInString:
// checkAuthorizationWithGroupIDs:
// checkBubbleAuthorizationWithGroupIDs:
// checkFollowStatusRecursively:maxAttempts:waitingAlert:defaults:
// checkVisibleNodeViews
// chevronSlider
// chevronSwitch
// chevronValueLabel
// childViewControllers
// class
// cleanupAllResources
// cleanupOrphanedBubbles:
// cleanupOrphanedCards:
// clearChatHistory
// clearColor
// clearImageCache
// clearImageSelection
// clearPathCode:
// clearSessionCache
// clearVideoSelection
// clipsToBounds
// closeFile
// closePath
// codeView
// collectionView
// collectionView:canEditItemAtIndexPath:
// collectionView:canFocusItemAtIndexPath:
// collectionView:canMoveItemAtIndexPath:
// collectionView:canPerformAction:forItemAtIndexPath:withSender:
// collectionView:canPerformPrimaryActionForItemAtIndexPath:
// collectionView:cellForItemAtIndexPath:
// collectionView:contextMenuConfiguration:dismissalPreviewForItemAtIndexPath:
// collectionView:contextMenuConfiguration:highlightPreviewForItemAtIndexPath:
// collectionView:contextMenuConfigurationForItemAtIndexPath:point:
// collectionView:contextMenuConfigurationForItemsAtIndexPaths:point:
// collectionView:didBeginMultipleSelectionInteractionAtIndexPath:
// collectionView:didDeselectItemAtIndexPath:
// collectionView:didEndDisplayingCell:forItemAtIndexPath:
// collectionView:didEndDisplayingSupplementaryView:forElementOfKind:atIndexPath:
// collectionView:didHighlightItemAtIndexPath:
// collectionView:didSelectItemAtIndexPath:
// collectionView:didUnhighlightItemAtIndexPath:
// collectionView:didUpdateFocusInContext:withAnimationCoordinator:
// collectionView:indexPathForIndexTitle:atIndex:
// collectionView:layout:insetForSectionAtIndex:
// collectionView:layout:minimumInteritemSpacingForSectionAtIndex:
// collectionView:layout:minimumLineSpacingForSectionAtIndex:
// collectionView:layout:referenceSizeForFooterInSection:
// collectionView:layout:referenceSizeForHeaderInSection:
// collectionView:layout:sizeForItemAtIndexPath:
// collectionView:moveItemAtIndexPath:toIndexPath:
// collectionView:numberOfItemsInSection:
// collectionView:performAction:forItemAtIndexPath:withSender:
// collectionView:performPrimaryActionForItemAtIndexPath:
// collectionView:previewForDismissingContextMenuWithConfiguration:
// collectionView:previewForHighlightingContextMenuWithConfiguration:
// collectionView:sceneActivationConfigurationForItemAtIndexPath:point:
// collectionView:selectionFollowsFocusForItemAtIndexPath:
// collectionView:shouldBeginMultipleSelectionInteractionAtIndexPath:
// collectionView:shouldDeselectItemAtIndexPath:
// collectionView:shouldHighlightItemAtIndexPath:
// collectionView:shouldSelectItemAtIndexPath:
// collectionView:shouldShowMenuForItemAtIndexPath:
// collectionView:shouldSpringLoadItemAtIndexPath:withContext:
// collectionView:shouldUpdateFocusInContext:
// collectionView:targetContentOffsetForProposedContentOffset:
// collectionView:targetIndexPathForMoveFromItemAtIndexPath:toProposedIndexPath:
// collectionView:targetIndexPathForMoveOfItemFromOriginalIndexPath:atCurrentIndexPath:toProposedIndexPath:
// collectionView:transitionLayoutForOldLayout:newLayout:
// collectionView:viewForSupplementaryElementOfKind:atIndexPath:
// collectionView:willDisplayCell:forItemAtIndexPath:
// collectionView:willDisplayContextMenuWithConfiguration:animator:
// collectionView:willDisplaySupplementaryView:forElementKind:atIndexPath:
// collectionView:willEndContextMenuInteractionWithConfiguration:animator:
// collectionView:willPerformPreviewActionForMenuWithConfiguration:animator:
// collectionViewDidEndMultipleSelectionInteraction:
// colorFromHex:
// colorPickerViewController:didSelectColor:continuously:
// colorPickerViewControllerDidFinish:
// colorPickerViewControllerDidSelectColor:
// colorPreviewForKey:defaultColor:
// colorSchemeColorFromHex:
// colorSchemeDisableConfigJsonSwitchChanged:
// colorSchemeMessageSwitchChanged:
// colorSchemeNicknameSwitchChanged:
// colorSchemeRedPacketSwitchChanged:
// colorSchemeReloadSection:
// colorWithAlphaComponent:
// colorWithCGColor:
// colorWithDynamicProvider:
// colorWithHue:saturation:brightness:alpha:
// colorWithRed:green:blue:alpha:
// colorWithWhite:alpha:
// colors
// commit
// commonKey
// commonMetadata
// compare:
// compare:options:
// completeTransition:
// completion
// completionHandler
// component:fromDate:
// components:fromDate:
// components:fromDate:toDate:options:
// componentsJoinedByString:
// componentsSeparatedByCharactersInSet:
// componentsSeparatedByString:
// concaveButtons
// configurationSignature
// configurationWithPointSize:weight:
// configureWithEntries:hostVC:
// configureWithEntry:
// configureWithMediaGroup:index:
// configureWithOpaqueBackground
// confirmDelete
// confirmTapped
// conformsToProtocol:
// conformsToType:
// connectedScenes
// constraintEqualToAnchor:
// constraintEqualToAnchor:constant:
// constraintEqualToConstant:
// constraintGreaterThanOrEqualToAnchor:constant:
// constraintGreaterThanOrEqualToConstant:
// constraintLessThanOrEqualToAnchor:
// constraintLessThanOrEqualToAnchor:constant:
// contactCoverMappings
// containerView
// containsObject:
// containsString:
// contentCharLimitButtonTapped:
// contentColorButtonTapped:
// contentColorSwitchChanged:
// contentInset
// contentMode
// contentOffset
// contentSize
// contentText
// contentView
// contentXOffsetButtonTapped:
// contentYOffsetButtonTapped:
// contentsOfDirectoryAtPath:error:
// continueFinishAnimation
// controlCharacterSet
// convertPoint:fromView:
// convertPoint:toView:
// convertRect:fromView:
// convertRect:toView:
// convertTextToSpeech:completion:
// convertTime:fromLayer:
// copy
// copyImageToDocuments:
// copyItemAtURL:toURL:error:
// copyVideoToDocuments:
// copyWxidToClipboard:
// cornerRadius
// cornerRadiusSwitchChanged:
// count
// countByEnumeratingWithState:objects:count:
// countForObject:
// countLabel
// countOfBytesExpectedToReceive
// countOfBytesReceived
// coverImageView
// coverImages
// cr_disableParallaxLighting
// cr_enableParallaxLighting
// cr_enableParallaxLightingWithDepth:lightAlpha:
// cr_enableParallaxLightingWithDepth:lightAlpha:lightColor:ringWidth:
// createAdvancedPlayerWithPattern:error:
// createAnimatedImageFromGIFData:
// createAnimatedImageFromWebPData:
// createDirectoryAtPath:withIntermediateDirectories:attributes:error:
// createPlayerWithPattern:error:
// createSliderWithColor:tag:
// createValueLabel
// credentialForTrust:
// csEditor_applyTemplateType:
// csEditor_exitPreview
// csEditor_keyboardWillHide:
// csEditor_keyboardWillShow:
// csEditor_preview
// csEditor_runDeferredTypeDetection
// csEditor_save
// csEditor_showHelp
// csEditor_showTemplates
// csEditor_updateHintText
// csList_addNew
// cs_presentCardConfigEditorForIndex:
// currentA
// currentB
// currentCalendar
// currentCategory
// currentChevronHidden
// currentChevronOffset
// currentContext
// currentDevice
// currentFontSize
// currentG
// currentIconSize
// currentItem
// currentLocale
// currentOffset
// currentR
// currentRunLoop
// currentSelected
// currentTitleSize
// currentTraitCollection
// customApiEnabled
// customApiUrl
// darkColorHex
// darkGrayColor
// data
// dataSource
// dataTaskWithRequest:completionHandler:
// dataTaskWithURL:completionHandler:
// dataUsingEncoding:
// dataWithBytes:length:
// dataWithBytesNoCopy:length:
// dataWithContentsOfFile:
// dataWithContentsOfURL:
// dataWithContentsOfURL:options:error:
// dataWithJSONObject:options:error:
// dataWithLength:
// date
// dateByAddingUnit:value:toDate:options:
// dateFormatFromTemplate:options:locale:
// dateFromComponents:
// dateWithTimeIntervalSince1970:
// dateWithTimeIntervalSinceNow:
// day
// dealloc
// debugDescription
// decimalDigitCharacterSet
// defaultCenter
// defaultDataStore
// defaultManager
// defaultSection
// defaultSessionConfiguration
// delegate
// deleteBackward
// deleteBubbleWithUUID:bubbleName:isCard:downloadVC:collectionView:
// deleteImage:currentCover:selfWxId:
// deletePersonalImage:currentCover:selfWxId:
// deleteRowsAtIndexPaths:withRowAnimation:
// deleteSections:withRowAnimation:
// deleteSessionCell:atSection:withUser:
// deleteSessionCellAtIndexes:
// dequeueReusableCellWithIdentifier:
// dequeueReusableCellWithReuseIdentifier:forIndexPath:
// dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:
// description
// deselectRowAtIndexPath:animated:
// detailTextLabel
// dictionary
// dictionaryForKey:
// dictionaryRepresentation
// dictionaryWithCapacity:
// dictionaryWithContentsOfFile:
// dictionaryWithObjects:forKeys:count:
// didFailWithError:
// didFinish
// didMoveToSuperview
// didMoveToWindow
// didReceiveData:
// didReceiveResponse:
// didSetDynamicYYImage
// dismissKeyboard
// dismissModal
// dismissModalViewControllerAnimated:
// dismissSubPackageSheet:
// dismissViewControllerAnimated:completion:
// displayLinkTick:
// displayLinkWithTarget:selector:
// dividerEntries
// doGlobalSearchPrepareWork
// dockEditor_exitPreview
// dockEditor_keyboardWillHide:
// dockEditor_keyboardWillShow:
// dockEditor_preview
// dockEditor_save
// dockEditor_showHelp
// dockEditor_showTemplates
// dockEditor_updateHintText
// dockList_addNew
// dockList_liftTextForStyle:
// dockList_overflowTextForStyle:
// documentPicker:didPickDocumentAtURL:
// documentPicker:didPickDocumentsAtURLs:
// documentPickerWasCancelled:
// donePicking
// doubleForKey:
// doubleValue
// downloadBubbleFile:bubbleName:button:isCard:
// downloadBubbleFromData:
// downloadBubbleTapped:
// downloadCenterSegmentChanged:
// downloadTaskWithURL:completionHandler:
// downloadThumbImageIfNeed
// drawInRect:
// drawRect:
// drawTextInRect:
// drawerActions
// dropInteraction:canHandleSession:
// dropInteraction:performDrop:
// dropInteraction:sessionDidUpdate:
// duration
// editBgColor
// editBorderColor
// editBorderWidth
// editIndex
// editRadius
// editTextColorOther
// editTextColorSelf
// editingDarkHex
// editingLightHex
// editingStyle
// effect
// effectWithStyle:
// emitterCell
// emitterCells
// encodeData:
// endEditing
// endEditing:
// endUpdates
// ensureLayoutForTextContainer:
// ensureVideoPlayback
// entries
// entry
// enumerateIndexesUsingBlock:
// enumerateObjectsUsingBlock:
// enumerateSubstringsInRange:options:usingBlock:
// ephemeralSessionConfiguration
// errorWithDomain:code:userInfo:
// escapedPatternForString:
// evaluateJavaScript:completionHandler:
// evaluateScript:
// exception
// exchangeObjectAtIndex:withObjectAtIndex:
// extraInfo
// fallbackLabel
// favoriteColors
// fetchAuthGroupIDsFromAPI:
// fetchBubbleAuthGroupIDsFromAPI:
// fetchUserBubblesForDownloadCenter:
// fileExistsAtPath:
// fileExistsAtPath:isDirectory:
// fileHandleForReadingAtPath:
// fileURLWithPath:
// filenameForIndex:
// fill
// filterMode
// filterSubPackageName:
// filteredArrayUsingPredicate:
// filteredContacts
// filteredSessions
// finalFrameForViewController:
// finishWithURLs:
// fireDate
// fired
// firstMatchInString:options:range:
// firstObject
// floatForKey:
// floatValue
// followMyOfficalAccount
// font
// fontDescriptor
// fontDescriptorWithSymbolicTraits:
// fontSlider
// fontValueLabel
// fontWithDescriptor:size:
// fontWithName:size:
// fontWithSize:
// frame
// functionWithName:
// gSlider
// gValueLabel
// generalPasteboard
// gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:
// gestureRecognizer:shouldReceiveEvent:
// gestureRecognizer:shouldReceivePress:
// gestureRecognizer:shouldReceiveTouch:
// gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:
// gestureRecognizer:shouldRequireFailureOfGestureRecognizer:
// gestureRecognizerShouldBegin:
// gestureRecognizers
// getAllBubbleFolders
// getAllCells
// getAllContactUserName
// getAllCoverImages
// getAllPersonalCoverImages
// getAllSections
// getAllVoiceCustomPrefixes
// getArrMessageNodeData
// getBrandContact:
// getBubbleDirectory
// getBubbleFolderPathForName:
// getBubbleImage:
// getBubbleImage:isDarkMode:
// getBubbleImage:isDarkMode:useCache:
// getBytes:length:
// getContactByName:
// getContactList:contactType:
// getContentView
// getCoverImageDisplaySize
// getCoverResDirectory
// getCurrentCoverImagePath
// getCurrentMessageWrap
// getCurrentPeerCoverImagePath
// getCurrentPersonalCoverImagePath
// getCurrentTimeString
// getCurrentUserName
// getCustomPrefixForVoice:
// getGlobalCoverDirectory
// getGlobalCoverPath
// getGroupMember:ofGroup:
// getHeadImage:
// getHeadImageView
// getHue:saturation:brightness:alpha:
// getNameplateDirectory
// getPeerCoverPath
// getPersonalCoverDirectory
// getPersonalCoverPath
// getRandomImageFromDocuments
// getRandomVideoFromDocuments
// getRed:green:blue:alpha:
// getReturnValue:
// getSafePresenter
// getSelectContent
// getSelfContact
// getSelfWxId
// getService:
// getTableView
// getWhite:alpha:
// gids
// glowColor
// glowColorButtonTapped:
// glowColorSwitchChanged:
// glowRadius
// glyphRangeForTextContainer:
// grayColor
// grayInfoSwitchForSection:row:withSwitch:
// graySvgInfoButtonForSection:row:
// greenColor
// groupCount
// groupId
// groupName
// groupNoAtEnabled
// handleBubbleLongPress:
// handleBubbleSwipeLeft:
// handleBubbleSwipeRight:
// handleDeleteButtonTapped:
// handleGesture:
// handleLongPress:
// handlePan:
// handleTap:
// handler
// hasDifferentColorAppearanceComparedToTraitCollection:
// hasItemConformingToTypeIdentifier:
// hasPrefix:
// hasPreviewed
// hasSuffix:
// hash
// hashTableWithOptions:
// headerRegisterWxid:
// headerTogglePlugin:
// headerView
// headerViewForSection:
// heightAnchor
// hexField
// hexFieldChanged:
// hexFromR:g:b:a:
// hexPreview
// hideDeleteButtonForCell:
// highRefreshFPSSwitchChanged:
// highRefreshSwitchChanged:
// highlightIndex:
// highlightRow:
// highlightedImage
// hintLabel
// hitTest:withEvent:
// hmacSHA256:key:
// homeBottomBarBadgeEnabledSwitchChanged:
// homeBottomBarFollowThemeIconSwitchChanged:
// homeBottomBarStyleSwitchChanged:
// homeBottomBarTabLabelHiddenSwitchChanged:
// homeBottomBarWiderDockSwitchChanged:
// host
// hostVC
// hsbView
// hue
// hueStrip
// iconSize
// iconView
// identifier
// image
// imageBackgroundButtonTapped:
// imageBackgroundSwitchChanged:
// imageDropSwitchChanged:
// imageForFilename:
// imageForIndex:
// imageNamed:
// imageNamed:inBundle:compatibleWithTraitCollection:
// imageNames
// imageOrientation
// imagePickerController:didFinishPickingImage:editingInfo:
// imagePickerController:didFinishPickingMediaWithInfo:
// imagePickerControllerDidCancel:
// imageSize
// imageView
// imageWithActions:
// imageWithCGImage:
// imageWithCGImage:scale:orientation:
// imageWithContentsOfFile:
// imageWithData:
// imageWithData:scale:
// imageWithRenderingMode:
// images
// imagesFilter
// impactOccurred
// impactOccurredWithIntensity:
// indexOfObject:
// indexPathForCell:
// indexPathForPreferredFocusedViewInCollectionView:
// indexPathForPreferredFocusedViewInTableView:
// indexPathForRow:inSection:
// indexPathForRowAtPoint:
// indexPathsForVisibleRows
// indexSet
// indexSetWithIndex:
// indexSetWithIndexesInRange:
// indexTitlesForCollectionView:
// indicator
// infoDisclosureBase:section:row:
// infoSwitchBase:section:row:withSwitch:
// init
// initAndReturnError:
// initData
// initForOpeningContentTypes:asCopy:
// initHeadImageView
// initWithActivityIndicatorStyle:
// initWithArrangedSubviews:
// initWithBarButtonSystemItem:target:action:
// initWithBase64EncodedString:options:
// initWithBytes:length:encoding:
// initWithCalendarIdentifier:
// initWithConfiguration:
// initWithCurrentMembers:
// initWithData:encoding:
// initWithData:error:
// initWithDelegate:
// initWithDocumentTypes:inMode:
// initWithDropOperation:
// initWithEffect:
// initWithEventType:parameters:relativeTime:
// initWithEventType:parameters:relativeTime:duration:
// initWithEvents:parameters:error:
// initWithFrame:
// initWithFrame:collectionViewLayout:
// initWithFrame:configuration:
// initWithFrame:style:
// initWithFrame:viewModel:
// initWithGroupId:groupName:
// initWithHandler:
// initWithImage:
// initWithImage:style:target:action:
// initWithIndex:
// initWithIndex:lineType:
// initWithItems:
// initWithLatitude:longitude:
// initWithLocaleIdentifier:
// initWithMsgType:
// initWithMsgType:nsFromUsr:
// initWithParameterID:value:
// initWithParameterID:value:relativeTime:
// initWithRootViewController:
// initWithSize:
// initWithSource:injectionTime:forMainFrameOnly:
// initWithString:
// initWithString:attributes:
// initWithStyle:
// initWithStyle:reuseIdentifier:
// initWithSuiteName:
// initWithTabBar:
// initWithTarget:action:
// initWithTitle:style:target:action:
// initWithURL:presentModal:extraInfo:
// initWithURL:statusCode:HTTPVersion:headerFields:
// initWithUsrName:headImgUrl:bAutoUpdate:bRoundCorner:
// injectToSettingView:title:version:selector:
// insertObject:atIndex:
// insertRow:
// insertRowsAtIndexPaths:withRowAnimation:
// insertSection:At:
// insertSections:withRowAnimation:
// insertSessionCellAtIndexes:scrollToCell:
// insertString:atIndex:
// insertSublayer:atIndex:
// insertSubview:aboveSubview:
// insertSubview:atIndex:
// insertSubview:belowSubview:
// insertText:
// intValue
// integerForKey:
// integerValue
// interactions
// interruptibleAnimatorForTransition:
// intrinsicContentSize
// invalidate
// invalidateAndCancel
// invalidateIntrinsicContentSize
// invertedSet
// invocationWithMethodSignature:
// invoke
// isAnimating
// isAuthorized
// isBeingDismissed
// isBeingPresented
// isBottomMostMMUILabelInQuickReplyView
// isBrandServiceHolder
// isCombineSendHidden
// isDarkMode
// isDateInToday:
// isDecelerating
// isDescendantOfView:
// isDeviceMotionActive
// isDeviceMotionAvailable
// isDivider
// isDragging
// isEqual:
// isEqualToArray:
// isEqualToDate:
// isEqualToString:
// isFolded
// isFollowingOfficalAccount
// isHidden
// isHighlighted
// isInBannerNotify
// isInChatPage
// isKeyWindow
// isKindOfClass:
// isLoaded
// isLoading
// isMainThread
// isMemberOfClass:
// isMuted
// isOn
// isPeerMode
// isProxy
// isPush
// isReceiverEnabled
// isRegistered
// isSearching
// isSelected
// isSelfAvatar
// isSender
// isSenderEnabled
// isSessionsSection
// isShowChatRoomDisplayName
// isSourceTypeAvailable:
// isTopMostMMUILabelInQuickReplyView
// isTouchInView:
// isTracking
// isUserInteractionEnabled
// isViewLoaded
// item
// itemProvider
// items
// keyWindow
// labelColor
// labelWidth
// languageCode
// largeDetent
// lastObject
// lastPathComponent
// lastPreviewAt
// lastPreviewValid
// layer
// layoutAllComponents
// layoutContentView
// layoutIfNeeded
// layoutSubviews
// leadingAnchor
// leftBarButtonItem
// leftBarButtonItems
// length
// lightColorHex
// lightGrayColor
// lineFragmentUsedRectForGlyphAtIndex:effectiveRange:
// lineHeight
// lineType
// loadAllContacts
// loadBgSoundList
// loadColorForCurrentMode
// loadCoverImages
// loadDefaultVoices
// loadFileRepresentationForTypeIdentifier:completionHandler:
// loadHTMLString:baseURL:
// loadImageForCell:imageURL:
// loadImageForImageView:imageURL:
// loadNameplateImages
// loadObjectsOfClass:completion:
// loadSelfAvatarToImageView:
// loadUserPreferedTheme
// loadVoiceList
// loadVoiceListFromCache
// loadXOSAtPath:
// loadingIndicator
// localeWithLocaleIdentifier:
// locality
// localizedCaseInsensitiveCompare:
// localizedCompare:
// localizedDescription
// locationInView:
// logicGetCountForSection:
// logicGetSessionAtIndexPath:
// logicUpdateSession:
// logicalRowForVisibleRow:
// longLongValue
// lowercaseString
// m_cellData
// m_contact
// m_delegate
// m_nameLabel
// m_nsContent
// m_nsFromUsr
// m_nsFullPY
// m_nsHeadImgUrl
// m_nsNickName
// m_nsRealChatUsr
// m_nsRemark
// m_nsToUsr
// m_nsUserName
// m_nsUsrName
// m_sessionInfo
// m_tableView
// m_uiCreateTime
// m_uiMesLocalID
// m_uiMessageType
// main
// mainBundle
// mainQueue
// mainRunLoop
// mainScreen
// mainSwitch
// mainSwitchChanged:
// mainTableView
// makeBigSectionHeader:
// makeFormatField:placeholder:
// makeKeyAndVisible
// makePlayerActive:
// makePreviewLabel
// makeSectionHeader:
// makeSliderForBGOpacity
// makeSliderForFontSize
// makeSliderForMaxWidth
// makeSliderForYOffset
// makeSpacer:
// manualFvCheckin
// mask
// masksToBounds
// matchesInString:options:range:
// maximumFramesPerSecond
// mediumDetent
// mesRefreshTableView
// messagePrefix
// messageSuffix
// messageWrap
// methodForSelector:
// methodSignatureForSelector:
// mgr_resizeImage:toSize:
// mgr_saveCardImageData:extension:
// mgr_showAddOptions
// mgr_showImageScalePopup
// mgr_showOffsetPopupWithTitle:key:
// mgr_showOptionsForImage:
// minCount
// minimumInteritemSpacing
// modeChanged:
// modeSegment
// monospacedDigitSystemFontOfSize:weight:
// monospacedSystemFontOfSize:weight:
// month
// moveItemAtPath:toPath:error:
// moveToPoint:
// mp3ToSilk:
// msgMergeAvatarAboveChanged:
// msgMergeReverseChanged:
// msgWrap
// multipleSelectionBackgroundView
// musicRhythmVibrationSwitchChanged:
// mutableBytes
// mutableCopy
// name
// nameplateHomeSwitchChanged:
// nameplateImages
// nameplatePMSwitchChanged:
// nameplatePerUserSwitchChanged:
// nameplateSwitchChanged:
// navigationBar
// navigationController
// navigationController:animationControllerForOperation:fromViewController:toViewController:
// navigationController:didShowViewController:animated:
// navigationController:interactionControllerForAnimationController:
// navigationController:willShowViewController:animated:
// navigationControllerPreferredInterfaceOrientationForPresentation:
// navigationControllerSupportedInterfaceOrientations:
// navigationItem
// newAsyncDisplayTask
// newEditorVCForGroupId:
// newlineCharacterSet
// nextResponder
// nicknameColorButtonTapped:
// nicknameColorSwitchChanged:
// nonretainedObjectValue
// normalCellForSel:target:title:rightValue:canRightValueCopy:
// notificationObserver
// notifyTaskBarOnDidEndSearch
// null
// numberOfMatchesInString:options:range:
// numberOfRanges
// numberOfRowsInSection:
// numberOfSections
// numberOfSectionsInCollectionView:
// numberOfSectionsInTableView:
// numberWithBool:
// numberWithDouble:
// numberWithFloat:
// numberWithInt:
// numberWithInteger:
// numberWithLongLong:
// numberWithUnsignedInt:
// numberWithUnsignedInteger:
// numberWithUnsignedLongLong:
// object
// objectAtIndex:
// objectAtIndexedSubscript:
// objectForInfoDictionaryKey:
// objectForKey:
// objectForKeyedSubscript:
// offsetSlider
// offsetValueLabel
// onAICustomPromptSwitchChanged:
// onAISwitchChanged:
// onAboveExtraShiftPtChanged:
// onBGOpacityChanged:
// onBelowExtraShiftPtChanged:
// onBoldChanged:
// onButtonLongPress:
// onButtonTap:
// onChanged
// onChevronOffsetChanged:
// onChevronVisibilityChanged:
// onClear
// onColorChanged
// onColorEnableChanged:
// onDashExtendPtChanged:
// onDeduplicateContactsChanged:
// onDividerTitleColorEnabledChanged:
// onDone
// onDonePressed
// onFTSSearchEnd
// onFieldChanged
// onFlipOrderSwitchChanged:
// onFollowThemeBadgeChanged:
// onFontChanged:
// onFontSizeChanged:
// onGuideLineXPadChanged:
// onHueChanged
// onLevelMeterPeak:
// onLogicDeleteSessionByUsername:
// onLogicHideSession:
// onLongPress:
// onLongTouch
// onLongTouch:
// onMasterChanged:
// onMasterSwitchChanged:
// onMaxWidthChanged:
// onMenuItemSelected:itemView:
// onMenuOffsetChange:menuWidth:
// onMessageDownloadThumbImageOK
// onMsgMergeAvatarAboveChanged:
// onMsgMergeReverseChanged:
// onOffsetChanged:
// onPlayerChanged
// onReset
// onSave
// onSavePressed:
// onSearch
// onSearchPageClickCancel
// onSegmentChanged:
// onSelect
// onSelectAllPressed
// onSendTextMsg:
// onShadowChanged:
// onShowAllChanged:
// onShowCountChanged:
// onShowGroupChatChanged:
// onShowOfficialChanged:
// onShowPrivateChanged:
// onShowStickyChanged:
// onShowUnreadBadgeChanged:
// onShowUnreadChanged:
// onSideRailSelectedBackgroundColorEnabledChanged:
// onSideRailTitleColorEnabledChanged:
// onSizeChanged:
// onTagFilterPressed
// onTap
// onTapOnSearchButton
// onTextColorEnableChanged:
// onTitleSizeChanged:
// onToggleEnable:
// onTouchUpInside
// onTranslateMsg:
// onVoiceSelected
// onVoiceTransClose:
// onWrapReferDividerLeftExtendChanged:
// onWrapReferDividerRightExtendChanged:
// onWrapReferOffsetStepperChanged:
// onYOffsetChanged:
// openBubbleDownloadCenter
// openOfficialAccount
// openPhotoLibraryForImageSelection
// openPhotoLibraryForVideoSelection
// orderedButtons
// ordinalityOfUnit:inUnit:forDate:
// origRow
// origRowCount
// origSection
// panelActionWithIndex:
// parallaxLightingSwitchChanged:
// parentModel
// parentViewController
// path
// pathExtension
// pause
// pausePlayManual:pauseDownload:
// pausePlayManual:pauseDownload:reportScene:
// payBubbleSwitchChanged:
// pcvm_darkKeyForWxId:
// pcvm_dirName
// pcvm_filePrefix
// pcvm_keyPrefix
// pcvm_lightKeyForWxId:
// pcvm_partyTitle
// pendingIconGroupId
// pendingSideRailIcon
// performAsCurrentTraitCollection:
// performSelector:
// performSelector:withObject:
// performSelector:withObject:afterDelay:
// performSelector:withObject:withObject:
// performWithoutAnimation:
// personalCoverImages
// petView
// pickColor
// pickPosition
// picker:didFinishPicking:
// pickerSaveImageData:extension:
// pickerTitle
// pitch
// play
// playApp:onPlayTaskStatusChanged:tingItem:onEvent:withContext:
// playAudioFromURL:voiceId:
// playWithMusicInfo:
// playWithMusicInfo:updateSessionId:
// playerItemWithURL:
// playerLayerWithPlayer:
// playerWithPlayerItem:
// pointInside:withEvent:
// pointSize
// pointerValue
// popViewControllerAnimated:
// popoverPresentationController
// position
// positionForBar:
// postNotificationName:object:
// postNotificationName:object:userInfo:
// predicateWithBlock:
// predicateWithFormat:
// preferredFontForTextStyle:
// preferredLocalizations
// prepare
// prepareForReuse
// prepareToPlay
// presentActionsFrom:groupId:sourceView:sourceRect:
// presentAppearanceFrom:groupId:groupName:
// presentDocumentPicker
// presentFromViewController:title:lightColorHex:darkColorHex:completion:
// presentGroupOrderFrom:
// presentIconCodePromptFrom:groupId:groupName:
// presentIconSettingsFrom:groupId:groupName:
// presentImageImagePicker
// presentImagePickerWithSourceType:
// presentLocalNotificationNow:
// presentMemberEditorFrom:groupId:
// presentPersonalDocumentPicker
// presentPersonalImagePickerWithSourceType:
// presentRenamePromptFrom:groupId:currentName:defaultName:
// presentSideRailActionsFrom:groupId:sourceView:sourceRect:
// presentSideRailAppearanceFrom:groupId:groupName:
// presentSideRailIconCodePromptFrom:groupId:groupName:
// presentSideRailIconSettingsFrom:groupId:groupName:
// presentSideRailRenamePromptFrom:groupId:currentName:defaultName:
// presentSizeSavedAlertForLabel:size:
// presentSizeSavedAlertForSelf:size:
// presentVideoImagePicker
// presentViewController:animated:completion:
// presentationLayer
// presentedViewController
// presentingViewController
// presetContainer
// presetLongPressed:
// presetTapped:
// previewButton
// previewButtonItem
// previewButtonTapped:
// previewCardImage:
// previewChevron
// previewChevronTrailing
// previewContainer
// previewErrLabel
// previewImage:
// previewLabel
// previewLeading
// previewMode
// previewStrip
// previewVoice:withText:
// previewingVoiceId
// promptRename
// protectionSpace
// pushMemberPicker
// pushViewController:animated:
// queryFvCharacters
// queryFvCredits
// rSlider
// rValueLabel
// randomImageSwitchChanged:
// randomVideoSwitchChanged:
// range
// rangeAtIndex:
// rangeOfCharacterFromSet:
// rangeOfComposedCharacterSequenceAtIndex:
// rangeOfData:options:range:
// rangeOfString:
// rangeOfString:options:
// rangeOfString:options:range:
// rangeOfUnit:inUnit:forDate:
// rate
// readDataOfLength:
// reason
// rebuildPresetButtons
// receiveMessageWithCompletionHandler:
// rectForHeaderInSection:
// rectForRowAtIndexPath:
// redColor
// redeemFvCharacters
// referTextBlurColor
// refilter
// refreshAfterMuteFlagChange
// refreshBubbleFolders
// refreshBubbleList
// refreshSelectedName
// refreshSnowAnimationForVideoBackground
// refreshThemeStyle
// refreshVoiceList
// refreshWeatherWithAlert
// registerClass:forCellWithReuseIdentifier:
// registerClass:forSupplementaryViewOfKind:withReuseIdentifier:
// registerControllerWithTitle:version:controller:
// registerToPluginManager:version:controllerClass:
// registeredTypeIdentifiers
// regularExpressionWithPattern:options:error:
// release
// reloadAll
// reloadCardImages
// reloadData
// reloadRowsAtIndexPaths:withRowAnimation:
// reloadSections:withRowAnimation:
// reloadSessions
// reloadSettings
// reloadTableData
// reloadTableView
// reloadThemeResource
// removeAllAnimations
// removeAllObjects
// removeAnimationForKey:
// removeBorderAndCornerRadius
// removeBorderImageView
// removeContentColorIfNeeded
// removeCustomBackgroundColor
// removeCustomPrefixForVoice:
// removeFromSuperlayer
// removeFromSuperview
// removeGestureRecognizer:
// removeImageBackground
// removeInteraction:
// removeItemAtPath:error:
// removeNicknameColorIfNeeded
// removeNotificationObserver
// removeObject:
// removeObjectAtIndex:
// removeObjectForKey:
// removeObjectsForKeys:
// removeObserver:
// removeObserver:name:object:
// removeOuterGlowOverlay
// removeRotationAnimation
// removeRow:
// removeSnowAnimation
// removeVideoBackground
// renderPreview:forDate:
// replaceCharactersInRange:withString:
// replyToWebView:requestId:result:
// request
// requestAuthorizationForAccessLevel:handler:
// requestBubbleUpdate:originalVersion:updateVersion:bubbleName:downloadURL:bubbleDir:button:downloadVC:isCard:
// requestWithURL:
// requestWithURL:cachePolicy:timeoutInterval:
// resCount
// resetAllSettings
// resignFirstResponder
// resizableImageWithCapInsets:resizingMode:
// resizeImage:toSize:
// resizeImageToSize:targetSize:
// resolvedColorWithTraitCollection:
// responder
// respondsToSelector:
// responseUserClick
// responseUserClick:
// restoreOriginalAppearance
// restoreOriginalBackgrounds
// restoreSnowAnimationFullEffect
// resume
// resumePlay
// retain
// retainCount
// reuseIdentifier
// reverseGeocodeLocation:preferredLocale:completionHandler:
// reverseObjectEnumerator
// richTextView
// rightBarButtonItem
// rightMaskView
// roll
// rootViewController
// row
// rowButtons
// rowHeight
// safeAreaInsets
// safeAreaLayoutGuide
// saturation
// saveBorderColor:
// saveBorderWidth:
// saveCardImageData:extension:
// saveColorForCurrentMode
// saveContentColor:
// saveCustomPrompt:
// saveFavoriteColors
// saveGlowColor:
// saveMainSwitchState:
// saveNicknameColor:
// savePathCode:
// savePersonalCoverImage:
// savePersonalCoverImageData:extension:
// savePrompt
// saveSelectedColor:
// saveVoiceListToCache
// scale
// scanDouble:
// scanHexInt:
// scanLongLong:
// scannerWithString:
// scheduledTimerWithTimeInterval:repeats:block:
// scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:
// scheme
// scrollTableToBottomAnimated:init:
// scrollToRowAtIndexPath:atScrollPosition:animated:
// scrollView
// scrollViewDidChangeAdjustedContentInset:
// scrollViewDidEndDecelerating:
// scrollViewDidEndDragging:willDecelerate:
// scrollViewDidEndScrollingAnimation:
// scrollViewDidEndZooming:withView:atScale:
// scrollViewDidScroll:
// scrollViewDidScrollToTop:
// scrollViewDidZoom:
// scrollViewShouldScrollToTop:
// scrollViewWillBeginDecelerating:
// scrollViewWillBeginDragging:
// scrollViewWillBeginZooming:withView:
// scrollViewWillEndDragging:withVelocity:targetContentOffset:
// searchBar
// searchBar:selectedScopeButtonIndexDidChange:
// searchBar:shouldChangeTextInRange:replacementText:
// searchBar:shouldChangeTextInRanges:replacementText:
// searchBar:textDidChange:
// searchBarBookmarkButtonClicked:
// searchBarCancelButtonClicked:
// searchBarResultsListButtonClicked:
// searchBarSearchButtonClicked:
// searchBarShouldBeginEditing:
// searchBarShouldEndEditing:
// searchBarTextDidBeginEditing:
// searchBarTextDidEndEditing:
// searchResults
// searchTextLower
// searchVoicesWithKeyword:
// secondaryLabelColor
// secondarySystemBackgroundColor
// secondarySystemFillColor
// secondarySystemGroupedBackgroundColor
// section
// sectionIndexTitlesForTableView:
// sectionInset
// seedGids
// seekToFileOffset:
// seekToTime:completionHandler:
// segmentChanged:
// segmentControl
// selectAiCustomIcon
// selectCategory:
// selectCustomIcon
// selectImageFile:
// selectImageFromDocuments
// selectSubPackage:
// selectVideoFile:
// selectVideoFromDocuments
// selected
// selectedBackgroundView
// selectedBgSound
// selectedColor
// selectedCoverName
// selectedIndex
// selectedNameplateName
// selectedOrder
// selectedSegmentIndex
// selectedStyleName
// selectedTextRange
// selectedViewController
// selectedVoice
// selectedVoiceName
// self
// sendAIChatRequest:fromUser:toUser:isGroup:chatId:completion:
// sendAIChatRequest:fromUser:toUser:isGroup:completion:
// sendActionsForControlEvents:
// sendMessage:completionHandler:
// sendParameters:atTime:error:
// sendSubviewToBack:
// sendTextMsg:toContactUsrName:withAtList:
// separatorColor
// serveTask:filePath:rangeHeader:url:
// serverTrust
// serviceCenter
// sessionWithConfiguration:
// sessionWithConfiguration:delegate:delegateQueue:
// set
// setASlider:
// setAValueLabel:
// setAccessibilityIdentifier:
// setAccessibilityLabel:
// setAccessoryType:
// setAccessoryView:
// setAction:
// setActions:
// setActive:
// setActive:error:
// setAdditive:
// setAdjustsFontSizeToFitWidth:
// setAdjustsImageWhenHighlighted:
// setAffineTransform:
// setAlertBody:
// setAlertTitle:
// setAlignment:
// setAlignmentMode:
// setAllContacts:
// setAllFriendsEnabled:
// setAllSessionEntries:
// setAllSessions:
// setAllowsEditing:
// setAllowsInlineMediaPlayback:
// setAllowsMultipleSelection:
// setAllowsSelection:
// setAllowsSelectionDuringEditing:
// setAlpha:
// setAlphaRange:
// setAlphaSpeed:
// setAlwaysBounceVertical:
// setAnchorPoint:
// setAnimationDuration:
// setAnimationImages:
// setAnimationRepeatCount:
// setAnimations:
// setApiHintLabel:
// setArgument:atIndex:
// setArrMsgs:
// setAttributedString:
// setAttributedText:
// setAudioPlayer:
// setAutocapitalizationType:
// setAutocorrectionType:
// setAutorepeat:
// setAutoresizingMask:
// setAutoreverses:
// setAvailableTags:
// setAxis:
// setBShowTextView:
// setBSlider:
// setBValueLabel:
// setBackBarButtonItem:
// setBackButtonDisplayMode:
// setBackgroundColor:
// setBadge:
// setBarButtonItem:
// setBeginTime:
// setBgSoundList:
// setBgVolume:
// setBirthRate:
// setBool:forKey:
// setBorderColor:
// setBorderStyle:
// setBorderWidth:
// setBothShowIconAndTitle:
// setBounces:
// setBounds:
// setBrightness:
// setCachePolicy:
// setCalculationMode:
// setCameraCaptureMode:
// setCancelsTouchesInView:
// setCardImages:
// setCategory:error:
// setCategoryNames:
// setCategoryScrollView:
// setCenter:
// setChevronSlider:
// setChevronSwitch:
// setChevronValueLabel:
// setClearButtonMode:
// setClickAction:
// setClipsToBounds:
// setCodeView:
// setCollectionView:
// setCollectionViewLayout:animated:
// setColor:
// setColorFromHex:
// setColors:
// setCombineSendHidden:animated:
// setCompactAppearance:
// setCompactScrollEdgeAppearance:
// setCompletion:
// setCompletionHandler:
// setConfigurationSignature:
// setConstant:
// setContactCoverMappings:
// setContentEdgeInsets:
// setContentHorizontalAlignment:
// setContentInset:
// setContentInsetAdjustmentBehavior:
// setContentMode:
// setContentOffset:
// setContentOffset:animated:
// setContentSize:
// setContentVerticalAlignment:
// setContentView:
// setContents:
// setContentsGravity:
// setContentsScale:
// setCornerRadius:
// setCountLabel:
// setCountLimit:
// setCoverImageView:
// setCoverImages:
// setCurrentA:
// setCurrentB:
// setCurrentCategory:
// setCurrentChevronHidden:
// setCurrentChevronOffset:
// setCurrentFontSize:
// setCurrentG:
// setCurrentIconSize:
// setCurrentOffset:
// setCurrentR:
// setCurrentSelected:
// setCurrentTheme:
// setCurrentTitleSize:
// setCustomApiEnabled:
// setCustomApiUrl:
// setDarkColorHex:
// setDataSource:
// setDateFormat:
// setDay:
// setDelaysTouchesBegan:
// setDelaysTouchesEnded:
// setDelegate:
// setDetents:
// setDeviceMotionUpdateInterval:
// setDirection:
// setDirectionalLayoutMargins:
// setDisableActions:
// setDividerEntries:
// setDouble:forKey:
// setDuration:
// setEdgesForExtendedLayout:
// setEditIndex:
// setEditable:
// setEditing:
// setEditing:animated:
// setEditingDarkHex:
// setEditingLightHex:
// setEditingStyle:
// setEffect:
// setEmissionLongitude:
// setEmissionRange:
// setEmitterCells:
// setEmitterMode:
// setEmitterPosition:
// setEmitterShape:
// setEmitterSize:
// setEnabled:
// setEndPoint:
// setEntries:
// setEntry:
// setEstimatedRowHeight:
// setEstimatedSectionFooterHeight:
// setEstimatedSectionHeaderHeight:
// setExceptionHandler:
// setFallbackLabel:
// setFavoriteColors:
// setFill
// setFillColor:
// setFillMode:
// setFillRule:
// setFilter:
// setFilterMode:
// setFilteredContacts:
// setFilteredSessions:
// setFired:
// setFloat:forKey:
// setFont:
// setFontSize:
// setFontSlider:
// setFontValueLabel:
// setForegroundColor:
// setFrame:
// setFromValue:
// setGSlider:
// setGValueLabel:
// setGids:
// setGlowColor:
// setGlowRadius:
// setGroupCount:
// setGroupId:
// setGroupName:
// setGroupNoAtEnabled:
// setHTTPBody:
// setHTTPMethod:
// setHandler:
// setHasPreviewed:
// setHeaderView:
// setHexField:
// setHexPreview:
// setHidden:
// setHidesBottomBarWhenPushed:
// setHidesWhenStopped:
// setHighlighted:
// setHighlighted:animated:
// setHighlightedImage:
// setHintLabel:
// setHostVC:
// setHour:
// setHsbView:
// setHue:
// setHueStrip:
// setIconSize:
// setIconView:
// setImage:
// setImage:forState:
// setImageEdgeInsets:
// setImageNames:
// setImageSize:
// setImages:
// setIndicator:
// setInteger:forKey:
// setIsBrandServiceHolder:
// setIsDarkMode:
// setIsDeleteEmptyFolder:
// setIsDivider:
// setIsFolded:
// setIsFolding:foldCount:
// setIsLoading:
// setIsPeerMode:
// setIsPush:
// setIsSearching:
// setIsSessionsSection:
// setItemSize:
// setKeyTimes:
// setKeyboardAppearance:
// setKeyboardDismissMode:
// setKeyboardType:
// setLastPreviewAt:
// setLastPreviewValid:
// setLayoutMargins:
// setLayoutMarginsRelativeArrangement:
// setLeftBarButtonItem:
// setLeftBarButtonItems:
// setLifetime:
// setLifetimeRange:
// setLightColorHex:
// setLineBreakMode:
// setLineCap:
// setLineCapStyle:
// setLineDashPattern:
// setLineFragmentPadding:
// setLineJoin:
// setLineJoinStyle:
// setLineType:
// setLineWidth:
// setLoadingIndicator:
// setLocale:
// setLocations:
// setLoopEnabled:
// setM_dtVoice:
// setM_extendInfoWithMsgType:
// setM_isDeleteUnknow:
// setM_isReportDelUnknow:
// setM_nsBizCliMsgId:
// setM_nsContent:
// setM_nsFromUsr:
// setM_nsToUsr:
// setM_refMessageWrap:
// setM_uiCreateTime:
// setM_uiDownloadStatus:
// setM_uiImgStatus:
// setM_uiMesLocalID:
// setM_uiStatus:
// setM_uiVoiceEndFlag:
// setM_uiVoiceFormat:
// setM_uiVoiceTime:
// setMainSwitch:
// setMainTableView:
// setMask:
// setMaskedCorners:
// setMasksToBounds:
// setMaxConcurrentOperationCount:
// setMaximumTrackTintColor:
// setMaximumValue:
// setMediaTypes:
// setMediaTypesRequiringUserActionForPlayback:
// setMenuItems:
// setMenuVisible:animated:
// setMenuVisible:responder:animated:
// setMessagePrefix:
// setMessageSuffix:
// setMinimumInteritemSpacing:
// setMinimumLineSpacing:
// setMinimumPressDuration:
// setMinimumScaleFactor:
// setMinimumTrackTintColor:
// setMinimumValue:
// setMinute:
// setModalPresentationStyle:
// setModeSegment:
// setMonth:
// setMuted:
// setName:
// setNameplateImages:
// setNavigationDelegate:
// setNeedsDisplay
// setNeedsLayout
// setNotificationObserver:
// setNsTitle:
// setNumberOfLines:
// setOTextColor:
// setObject:atIndexedSubscript:
// setObject:forKey:
// setObject:forKey:cost:
// setObject:forKeyedSubscript:
// setOffsetSlider:
// setOffsetValueLabel:
// setOn:
// setOn:animated:
// setOnChanged:
// setOnClear:
// setOnColorChanged:
// setOnDone:
// setOnHueChanged:
// setOnSave:
// setOnSelect:
// setOnTap:
// setOnTintColor:
// setOnVoiceSelected:
// setOpacity:
// setOpaque:
// setOrderedButtons:
// setOrigRow:
// setOrigRowCount:
// setOrigSection:
// setPagingEnabled:
// setPath:
// setPaused:
// setPendingIconGroupId:
// setPendingSideRailIcon:
// setPermittedArrowDirections:
// setPersonalCoverImages:
// setPetView:
// setPickerTitle:
// setPlaceholder:
// setPlaysHapticsOnly:
// setPosition:
// setPreferredFrameRateRange:
// setPreferredFramesPerSecond:
// setPrefersGrabberVisible:
// setPresetContainer:
// setPreviewButton:
// setPreviewButtonItem:
// setPreviewChevron:
// setPreviewChevronTrailing:
// setPreviewContainer:
// setPreviewErrLabel:
// setPreviewLabel:
// setPreviewLeading:
// setPreviewMode:
// setPreviewStrip:
// setPreviewingVoiceId:
// setQualityOfService:
// setRSlider:
// setRValueLabel:
// setRasterizationScale:
// setRect:
// setReferTextBlurColor:
// setRemovedOnCompletion:
// setRepeatCount:
// setResetHandler:
// setReturnKeyType:
// setRightBarButtonItem:
// setRightBarButtonItems:
// setRowHeight:
// setSaturation:
// setSaturation:brightness:
// setScale:
// setScaleRange:
// setScaleSpeed:
// setScanLocation:
// setScene:
// setScrollDirection:
// setScrollEdgeAppearance:
// setScrollEnabled:
// setScrollIndicatorInsets:
// setScrollView:
// setSearchBar:
// setSearchBarStyle:
// setSearchBarToTableHeaderView
// setSearchResults:
// setSearchTextLower:
// setSecond:
// setSectionInset:
// setSegmentControl:
// setSelected:
// setSelected:animated:
// setSelectedBgSound:
// setSelectedColor:
// setSelectedCoverName:
// setSelectedIndex:
// setSelectedNameplateName:
// setSelectedOrder:
// setSelectedSegmentIndex:
// setSelectedStyleName:
// setSelectedVoice:
// setSelectedVoiceName:
// setSelectionLimit:
// setSelectionStyle:
// setSelector:
// setSeparatorInset:
// setSettingsVersion:
// setShadowColor:
// setShadowOffset:
// setShadowOpacity:
// setShadowPath:
// setShadowRadius:
// setShouldRasterize:
// setShouldShowFileExtensions:
// setShowsHorizontalScrollIndicator:
// setShowsReorderControl:
// setShowsVerticalScrollIndicator:
// setSize:
// setSizeSlider:
// setSizeValueLabel:
// setSmartDashesType:
// setSmartInsertDeleteType:
// setSmartQuotesType:
// setSnapshotWidth:
// setSourceRect:
// setSourceType:
// setSourceView:
// setSpacing:
// setSpeechRate:
// setSpeed:
// setSpellCheckingType:
// setSpin:
// setSpinRange:
// setStandardAppearance:
// setStartPoint:
// setStepValue:
// setStoppedHandler:
// setString:
// setStroke
// setStrokeColor:
// setStrokeEnd:
// setStyleName:
// setStyleType:
// setSupportsAlpha:
// setSwipeToTrigger:
// setSystemPrompt:
// setTabBar:
// setTableHeaderView:
// setTableView:
// setTag:
// setTagFilter:
// setTagFilterButton:
// setTarget:
// setTargetNickName:
// setTargetUserName:
// setTargetView:
// setTargetWidth:
// setText:
// setTextAlignment:
// setTextColor:
// setTextContainerInset:
// setThumbImage:forState:
// setTimeOffset:
// setTimeZone:
// setTimeoutInterval:
// setTimeoutIntervalForRequest:
// setTimeoutIntervalForResource:
// setTimingFunction:
// setTintColor:
// setTitle:
// setTitle:forState:
// setTitleColor:
// setTitleColor:forState:
// setTitleFontSize:
// setTitleLabel:
// setTitleSizeSlider:
// setTitleSizeValueLabel:
// setTitleTextAttributes:forState:
// setToValue:
// setTotalCostLimit:
// setTransform:
// setTranslatesAutoresizingMaskIntoConstraints:
// setTriggerPrefix:
// setTypeFilter:
// setTypeSegment:
// setUIDelegate:
// setURL:
// setURLSchemeHandler:forURLScheme:
// setUnderPageBackgroundColor:
// setUnreadCount:
// setUpdatingFromCode:
// setUserContentController:
// setUserInfo:
// setUserInteractionEnabled:
// setUserName:
// setUsername:
// setValue:
// setValue:forHTTPHeaderField:
// setValue:forKey:
// setValues:
// setVelocity:
// setVelocityRange:
// setVideoGravity:
// setVideoQuality:
// setVoiceCategories:
// setVoiceList:
// setVolume:
// setWaitsForConnectivity:
// setWebView:
// setWebsiteDataStore:
// setWithArray:
// setWithCapacity:
// setWxidToGid:
// setWxidToOrigIndexPath:
// setWxidToUnreadContribution:
// setWxidToVisualRow:
// setXAcceleration:
// setXzy_actionId:
// setXzy_tabBar:
// setXzy_tabIndex:
// setYAcceleration:
// setYear:
// setZPosition:
// settingsVersion
// setupAvatarCoverMask
// setupAvatarRotationCell:defaults:
// setupBackgroundColorCell:defaults:
// setupBannerHeightCell:defaults:
// setupBannerWidthCell:defaults:
// setupBorderColorWithSwitchCell:defaults:
// setupBorderImageHeightOffsetCell:defaults:
// setupBorderImageView
// setupBorderImageWidthOffsetCell:defaults:
// setupBorderImageXOffsetCell:defaults:
// setupBorderImageYOffsetCell:defaults:
// setupBorderWidthCell:defaults:
// setupCategoryBar
// setupContentCharLimitCell:defaults:
// setupContentColorCell:defaults:
// setupContentXOffsetCell:defaults:
// setupContentYOffsetCell:defaults:
// setupCornerRadiusCell:defaults:
// setupCoverImageView
// setupGlobalCoverForNonChat
// setupGlowColorWithSwitchCell:defaults:
// setupHSBPicker
// setupHeader
// setupHeaderView
// setupHexInput
// setupImageBackgroundCell:defaults:
// setupMainSwitchCell:defaults:
// setupModeSegment
// setupNicknameColorCell:defaults:
// setupPresetColors
// setupRGBSliders
// setupRandomImageCell:defaults:
// setupRandomVideoCell:defaults:
// setupScrollView
// setupSnowAnimationCell:defaults:
// setupTableView
// setupUI
// setupVideoBackgroundCell:defaults:
// setupVideoSoundCell:defaults:
// shadowOpacity
// shadowPath
// shareInstance
// shared
// sharedApplication
// sharedDriver
// sharedInstance
// sharedSession
// sheetPresentationController
// showAIChatSettings
// showAICustomPromptEditor
// showAddCardImageOptions
// showAddCustomGroupPrompt
// showAddImageOptions
// showAiCellInfo:
// showAiDefaultIconCodeSettings
// showAiIconSelector
// showAlphaAlert
// showAvatarSizeAlert
// showAvatarSpacingAlert
// showBannerCellInfo:
// showBannerNotifyBeautifySettings
// showBgSoundSelector
// showBgVolumeSettings
// showBorderWidthAlert
// showBubbleCropSettingsPage
// showBubbleDeleteConfirmation:downloadVC:collectionView:
// showBubbleDownloadError:inViewController:
// showBubbleList:inViewController:
// showBubblePetConfigForSender:position:tableView:
// showBubblePetPathCodeEditorForKey:tableView:
// showBubblePetSettingsPage
// showBubbleSettingsPage
// showBubbleShadowSettingsPage
// showCadisCellInfo:
// showCadisSettings
// showCardImageManager
// showCardImageOptionsForImage:
// showCardImagePickerForMode:
// showCardMarginAlert
// showColorPickerForTag:
// showColorSchemeSettingsPage
// showColorSelectionAlert
// showColorSelectionAlertForType:
// showContactBgHeightAlert
// showContentColorSelectionAlert
// showCornerRadiusInput
// showCornerRadiusInputAlertForKey:title:
// showCornerRadiusInputAlertForSelf:
// showCoverSubSettings
// showCoversSettings
// showCustomApiSubPage
// showCustomApiUrlEditor
// showCustomPrefixManager
// showCustomPrefixSettingForVoice:voiceName:
// showCustomSizeInput
// showCustomSizeInputForKey:labelName:
// showCustomSizeInputForSelf:
// showCustomSpeechRateInput
// showDashStylePickerForVariant:
// showDateTimeColorPicker
// showDateTimeDisplayModePicker
// showDefaultIconCodeSettings
// showDividerTitleColorPicker
// showDownloadResult:message:button:
// showEditCustomPrefixForVoice:voiceName:currentPrefix:
// showFishTokenSettings
// showFontSettings
// showFromViewController:animated:complete:
// showFvMessage:message:
// showFvTokenEditor
// showFvTokenSettings
// showGrayCellInfo:
// showGrayTestSettings
// showGroupGapInputAlert
// showGuideLinePosPickerForIsSelf:
// showGuideLineStylePickerForVariant:
// showHeightAlert
// showHeightReduceInputAlert
// showHighRefreshSettings
// showHomeBottomBarAddItemPicker
// showHomeBottomBarSettings
// showIconSelector
// showImageErrorAlert:
// showImageOptionsForImage:currentCover:selfWxId:
// showImageSelectionAlert:
// showImageSizePickerForKey:labelName:
// showImageSizePickerForSelf:
// showImageSizeSettings
// showMessageOffsetInputAlertForSelf:
// showMinCountPicker
// showMsgMergeSettings
// showNameplateSettings
// showNicknameColorSelectionAlert
// showOnlineDotPositionPicker
// showOtherFunctionsSettings
// showPercentAlertWithTitle:key:current:reloadSection:
// showPersonalCoverSettings
// showPersonalImageOptionsForImage:currentCover:selfWxId:
// showPluginJumpKeywordSettings
// showPositionModePickerForIsSelf:
// showPrefixEditor
// showPrivateGapInputAlert
// showQWeatherHostAlert
// showQWeatherKeyAlert
// showRestartAlert:
// showReverseAvatarDownOffsetInputAlert
// showSearchBar:
// showSearchBar:searchBar:
// showSelectedBorderColorPicker
// showSidePositionSheet
// showSideRailSelectedBackgroundColorPicker
// showSideRailTitleColorPicker
// showSideRailXOffsetPrompt
// showSideScopeSheet
// showSignedCardPointAlertWithTitle:key:current:message:
// showSpacingAlertWithTitle:key:current:reloadSection:
// showSpeechRateSettings
// showStickyOffSpacingPrompt
// showStickyTopSpacingPrompt
// showSubPackagesForBubble:
// showSubPageCellInfo:
// showSuffixEditor
// showSuffixTextInputAlert
// showSystemPromptEditor
// showTTSCellInfo:
// showTTSSettings
// showTimeFormatPicker
// showTimeLabelSettingsPage
// showTimeLocalePicker
// showTriggerPrefixSettings
// showUnselectedBorderColorPicker
// showUsageRules
// showVideoErrorAlert:
// showVideoSelectionAlert:
// showVoiceJumpKeywordSettings
// showVoiceSelector
// showVoicesForCategory:
// showVolumeSettings
// showWrapReferAlignmentPickerForCell:
// showWrapReferDividerLengthPickerForCell:
// showWrapReferDividerStylePickerForCell:variant:
// showWrapReferSubSettingsPage
// size
// sizeSlider
// sizeThatFits:
// sizeToFit
// sizeToFitWidth:
// sizeValueLabel
// sizeWithAttributes:
// sliderChanged:
// snowAnimationSwitchChanged:
// sortUsingComparator:
// sortUsingSelector:
// sortedArrayUsingComparator:
// sortedArrayUsingSelector:
// speechRate
// speed
// standardUserDefaults
// startAccessingSecurityScopedResource
// startAndReturnError:
// startAnimating
// startAtTime:error:
// startDeviceMotionUpdatesToQueue:withHandler:
// startIfNeeded
// startLoadingForSessionRebuild
// startWithScanConfig:
// state
// statusCode
// stop
// stopAccessingSecurityScopedResource
// stopAnimating
// stopAtTime:error:
// stopDeviceMotionUpdates
// stopLoadingForSessionRebuild
// stopPlay
// stopPreview
// stopTextAnimation
// stopWithCompletionHandler:
// string
// stringByAddingPercentEncodingWithAllowedCharacters:
// stringByAppendingFormat:
// stringByAppendingPathComponent:
// stringByAppendingString:
// stringByDeletingLastPathComponent
// stringByDeletingPathExtension
// stringByRemovingPercentEncoding
// stringByReplacingMatchesInString:options:range:withTemplate:
// stringByReplacingOccurrencesOfString:withString:
// stringByTrimmingCharactersInSet:
// stringForKey:
// stringFromDate:
// stringValue
// stringWithCapacity:
// stringWithContentsOfFile:encoding:error:
// stringWithFormat:
// stringWithString:
// stringWithUTF8String:
// stroke
// styleName
// styleType
// subViewModels
// subarrayWithRange:
// subdataWithRange:
// sublayers
// substringFromIndex:
// substringToIndex:
// substringWithRange:
// subviews
// superclass
// superlayer
// superview
// supportsHaptics
// svgImageNamed:size:color:
// svgImageNamed:size:color:alpha:angle:ignoreNotFound:
// svgInfoBtnBase:section:row:
// switchCellForSel:target:title:on:
// syncCurrentValue
// syncSlidersFromCurrent
// synchronize
// systemBackgroundColor
// systemBlueColor
// systemFontOfSize:
// systemFontOfSize:weight:
// systemGray3Color
// systemGray4Color
// systemGray5Color
// systemGray6Color
// systemGrayColor
// systemGreenColor
// systemGroupedBackgroundColor
// systemImageNamed:
// systemImageNamed:withConfiguration:
// systemIndigoColor
// systemLayoutSizeFittingSize:
// systemOrangeColor
// systemPinkColor
// systemPrompt
// systemPurpleColor
// systemRedColor
// systemTealColor
// systemYellowColor
// tabBar
// tabBarController
// tableFooterView
// tableHeaderView
// tableView
// tableView:accessoryButtonTappedForRowWithIndexPath:
// tableView:accessoryTypeForRowWithIndexPath:
// tableView:canEditRowAtIndexPath:
// tableView:canFocusRowAtIndexPath:
// tableView:canMoveRowAtIndexPath:
// tableView:canPerformAction:forRowAtIndexPath:withSender:
// tableView:canPerformPrimaryActionForRowAtIndexPath:
// tableView:cellForRowAtIndexPath:
// tableView:commitEditingStyle:forRowAtIndexPath:
// tableView:contextMenuConfigurationForRowAtIndexPath:point:
// tableView:didBeginMultipleSelectionInteractionAtIndexPath:
// tableView:didDeselectRowAtIndexPath:
// tableView:didEndDisplayingCell:forRowAtIndexPath:
// tableView:didEndDisplayingFooterView:forSection:
// tableView:didEndDisplayingHeaderView:forSection:
// tableView:didEndEditingRowAtIndexPath:
// tableView:didHighlightRowAtIndexPath:
// tableView:didSelectRowAtIndexPath:
// tableView:didUnhighlightRowAtIndexPath:
// tableView:didUpdateFocusInContext:withAnimationCoordinator:
// tableView:editActionsForRowAtIndexPath:
// tableView:editingStyleForRowAtIndexPath:
// tableView:estimatedHeightForFooterInSection:
// tableView:estimatedHeightForHeaderInSection:
// tableView:estimatedHeightForRowAtIndexPath:
// tableView:heightForFooterInSection:
// tableView:heightForHeaderInSection:
// tableView:heightForRowAtIndexPath:
// tableView:indentationLevelForRowAtIndexPath:
// tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:
// tableView:moveRowAtIndexPath:toIndexPath:
// tableView:numberOfRowsInSection:
// tableView:performAction:forRowAtIndexPath:withSender:
// tableView:performPrimaryActionForRowAtIndexPath:
// tableView:previewForDismissingContextMenuWithConfiguration:
// tableView:previewForHighlightingContextMenuWithConfiguration:
// tableView:sectionForSectionIndexTitle:atIndex:
// tableView:selectionFollowsFocusForRowAtIndexPath:
// tableView:shouldBeginMultipleSelectionInteractionAtIndexPath:
// tableView:shouldHighlightRowAtIndexPath:
// tableView:shouldIndentWhileEditingRowAtIndexPath:
// tableView:shouldShowMenuForRowAtIndexPath:
// tableView:shouldSpringLoadRowAtIndexPath:withContext:
// tableView:shouldUpdateFocusInContext:
// tableView:targetIndexPathForMoveFromRowAtIndexPath:toProposedIndexPath:
// tableView:titleForDeleteConfirmationButtonForRowAtIndexPath:
// tableView:titleForFooterInSection:
// tableView:titleForHeaderInSection:
// tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:
// tableView:viewForFooterInSection:
// tableView:viewForHeaderInSection:
// tableView:willBeginEditingRowAtIndexPath:
// tableView:willDeselectRowAtIndexPath:
// tableView:willDisplayCell:forRowAtIndexPath:
// tableView:willDisplayContextMenuWithConfiguration:animator:
// tableView:willDisplayFooterView:forSection:
// tableView:willDisplayHeaderView:forSection:
// tableView:willEndContextMenuInteractionWithConfiguration:animator:
// tableView:willPerformPreviewActionForMenuWithConfiguration:animator:
// tableView:willSelectRowAtIndexPath:
// tableViewDidEndMultipleSelectionInteraction:
// tag
// tagFilter
// tagFilterButton
// takeSnapshotWithConfiguration:completionHandler:
// targetNickName
// targetUserName
// targetView
// tertiaryLabelColor
// tertiarySystemFillColor
// testAIConnection
// text
// textColor
// textContentForIndex:
// textField:editMenuForCharactersInRange:suggestedActions:
// textField:editMenuForCharactersInRanges:suggestedActions:
// textField:insertInputSuggestion:
// textField:shouldChangeCharactersInRange:replacementString:
// textField:shouldChangeCharactersInRanges:replacementString:
// textField:willDismissEditMenuWithAnimator:
// textField:willPresentEditMenuWithAnimator:
// textFieldDidBeginEditing:
// textFieldDidChangeSelection:
// textFieldDidEndEditing:
// textFieldDidEndEditing:reason:
// textFieldShouldBeginEditing:
// textFieldShouldClear:
// textFieldShouldEndEditing:
// textFieldShouldReturn:
// textFields
// textInRange:
// textLabel
// textString
// textView:didBeginFormattingWithViewController:
// textView:didEndFormattingWithViewController:
// textView:editMenuForTextInRange:suggestedActions:
// textView:editMenuForTextInRanges:suggestedActions:
// textView:insertInputSuggestion:
// textView:menuConfigurationForTextItem:defaultMenu:
// textView:primaryActionForTextItem:defaultAction:
// textView:shouldChangeTextInRange:replacementText:
// textView:shouldChangeTextInRanges:replacementText:
// textView:shouldInteractWithTextAttachment:inRange:
// textView:shouldInteractWithTextAttachment:inRange:interaction:
// textView:shouldInteractWithURL:inRange:
// textView:shouldInteractWithURL:inRange:interaction:
// textView:textItemMenuWillDisplayForTextItem:animator:
// textView:textItemMenuWillEndForTextItem:animator:
// textView:willBeginFormattingWithViewController:
// textView:willDismissEditMenuWithAnimator:
// textView:willEndFormattingWithViewController:
// textView:willPresentEditMenuWithAnimator:
// textView:writingToolsIgnoredRangesInEnclosingRange:
// textViewDidBeginEditing:
// textViewDidChange:
// textViewDidChangeSelection:
// textViewDidEndEditing:
// textViewShouldBeginEditing:
// textViewShouldEndEditing:
// textViewWritingToolsDidEnd:
// textViewWritingToolsWillBegin:
// timeIntervalSince1970
// timeIntervalSinceReferenceDate
// timeLabelCheckmarkSwitchChanged:
// timeLabelEnableSwitchChanged:
// timeLabelNoMergeSwitchChanged:
// timeLabelSenderLeftSwitchChanged:
// timeLabelSuffixSwitchChanged:
// timeOffset
// timeZoneForSecondsFromGMT:
// timeZoneWithName:
// timerWithTimeInterval:target:selector:userInfo:repeats:
// timestamp
// tintColor
// title
// titleFontSize
// titleForState:
// titleLabel
// titleSizeSlider
// titleSizeValueLabel
// toArray
// toNumber
// toggleAIChat:
// toggleAvatarCorner:
// toggleBubbleDisplayMode:
// toggleBubbleEnabled:
// toggleCalendarMode:
// toggleCalendarPos:
// toggleCardBorder:
// toggleContactFullScreen:
// toggleContactHideNick:
// toggleContactMaxVisible:
// toggleContactMode:
// toggleContactPos:
// toggleCoverDisableHomeCardContactMask:
// toggleCoverDisableOnMainPage:
// toggleCoverFunction:
// toggleCoversFunction
// toggleCreatorSwitchVisibility:
// toggleEnabled:
// toggleFvAutoCheckin:
// toggleFvCheckinNotice:
// toggleHideGroupOtherAvatar:
// toggleHideGroupSelfAvatar:
// toggleHidePrivateOtherAvatar:
// toggleHidePrivateSelfAvatar:
// toggleImageBlur:
// toggleImageStack:
// toggleMsgMerge:
// toggleOnlineStatus:
// toggleOption:
// toggleOriginalImage:
// toggleReverseMerge:
// toggleSmoothScroll:
// toggleStackCheck:
// toggleTTSFunction:
// toggleWeatherMode:
// toggleWeatherPos:
// topAnchor
// topViewController
// touchesBegan:withEvent:
// touchesCancelled:withEvent:
// touchesEnded:withEvent:
// touchesMoved:withEvent:
// trailingAnchor
// traitCollection
// traitCollectionDidChange:
// transform
// transitionCoordinator
// transitionDuration:
// transitionWasCancelled
// transitionWithView:duration:options:animations:completion:
// translateMsg:
// translateMsg:translateNow:hideLoading:
// triggerPrefix
// tryAddBrandContact:context:
// ttsInfoSwitchForSection:row:withSwitch:
// ttsSvgInfoButtonForSection:row:
// tts_currentResponder
// tts_getCurrentChatUser
// tts_getSelectedText
// tts_getTopViewController
// tts_getTopViewControllerFrom:
// tts_handleTextToVoice
// type
// typeFilter
// typeSegment
// typeWithFilenameExtension:
// typeWithIdentifier:
// typeWithMIMEType:
// unarchivedObjectOfClass:fromData:error:
// unionSet:
// unload
// unreadCount
// unsignedIntValue
// unsignedIntegerValue
// unsignedLongLongValue
// unzipFileAtPath:toDestination:
// updateAuthorizationStatus
// updateBorderImageFrame
// updateCountLabel
// updateCoverImageViewLayout
// updateHSBFromRGB
// updateHexFromRGB
// updateImageLayerFrame
// updateIndicatorColor
// updateIndicatorPosition
// updateMoreMenu:
// updateNameLabel
// updateOuterGlowAppearance
// updateOuterGlowOverlay
// updatePlayRateButtonPosition
// updatePreview
// updatePreviewColor
// updatePreviews
// updateQuickTransTipButtonPosition
// updateResumePlayButtonPosition
// updateSelectAllButtonTitle
// updateSelectionBackground
// updateSession:
// updateSlidersFromRGB
// updateSnowEmitterPosition
// updateUnreadBadgesWithEntries:
// updateUnreadCountView
// updateVideoLayerFrame
// updateViewsForPanProgress:
// updateWithCellData:
// updateWithPoint:
// updatingFromCode
// uppercaseString
// userContentController
// userContentController:didReceiveScriptMessage:
// userInfo
// userInterfaceIdiom
// userInterfaceStyle
// userName
// value
// valueForKey:
// valueWithCGPoint:
// valueWithCGRect:
// valueWithNewArrayInContext:
// valueWithNonretainedObject:
// valueWithPointer:
// valueWithUIEdgeInsets:
// videoBackgroundButtonTapped:
// videoBackgroundSwitchChanged:
// videoDidFinishPlaying:
// videoSoundSwitchChanged:
// videosFilter
// view
// viewControllerForKey:
// viewControllers
// viewDidAppear:
// viewDidLayoutSubviews
// viewDidLoad
// viewForZoomingInScrollView:
// viewModel
// viewWillAppear:
// viewWillDisappear:
// viewWithTag:
// visibleCells
// visibleViewController
// voiceCategories
// voiceList
// volume
// weakObjectsHashTable
// webSocketTaskWithURL:
// webView
// webView:authenticationChallenge:shouldAllowDeprecatedTLS:
// webView:commitPreviewingViewController:
// webView:contextMenuConfigurationForElement:completionHandler:
// webView:contextMenuDidEndForElement:
// webView:contextMenuForElement:willCommitWithAnimator:
// webView:contextMenuWillPresentForElement:
// webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:
// webView:decidePolicyForNavigationAction:decisionHandler:
// webView:decidePolicyForNavigationAction:preferences:decisionHandler:
// webView:decidePolicyForNavigationResponse:decisionHandler:
// webView:didCommitNavigation:
// webView:didFailNavigation:withError:
// webView:didFailProvisionalNavigation:withError:
// webView:didFinishNavigation:
// webView:didReceiveAuthenticationChallenge:completionHandler:
// webView:didReceiveServerRedirectForProvisionalNavigation:
// webView:didStartProvisionalNavigation:
// webView:navigationAction:didBecomeDownload:
// webView:navigationResponse:didBecomeDownload:
// webView:previewingViewControllerForElement:defaultActions:
// webView:requestDeviceOrientationAndMotionPermissionForOrigin:initiatedByFrame:decisionHandler:
// webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:
// webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:
// webView:runJavaScriptConfirmPanelWithMessage:initiatedByFrame:completionHandler:
// webView:runJavaScriptTextInputPanelWithPrompt:defaultText:initiatedByFrame:completionHandler:
// webView:runOpenPanelWithParameters:initiatedByFrame:completionHandler:
// webView:shouldGoToBackForwardListItem:willUseInstantBack:completionHandler:
// webView:shouldPreviewElement:
// webView:showLockdownModeFirstUseMessage:completionHandler:
// webView:startURLSchemeTask:
// webView:stopURLSchemeTask:
// webView:willDismissEditMenuWithAnimator:
// webView:willPresentEditMenuWithAnimator:
// webViewDidClose:
// webViewWebContentProcessDidTerminate:
// weekOfYear
// weekday
// whiteColor
// whitespaceAndNewlineCharacterSet
// whitespaceCharacterSet
// widthAnchor
// willEndSearch
// window
// windowLevel
// windows
// wrapReferDividerSwitchChanged:
// wrapReferSwitchChanged:
// writeToFile:atomically:
// writeToFile:atomically:encoding:error:
// writeToFile:options:error:
// writeToURL:atomically:
// wxidToGid
// wxidToOrigIndexPath
// wxidToUnreadContribution
// wxidToVisualRow
// xzy_actionId
// xzy_addSettingRow:atIndex:title:detail:width:height:tag:
// xzy_clear
// xzy_customBubbleOrOrig:
// xzy_dismiss
// xzy_ensurePerUserSettingsExist
// xzy_handleDarkModeChange:
// xzy_handleLongPress:
// xzy_handleTap
// xzy_homeNameplateLongPress:
// xzy_loadImages
// xzy_removePerUserSettings
// xzy_settingRowTapped:
// xzy_showHeightInput
// xzy_showOffsetInput:key:
// xzy_showPositionPicker
// xzy_tabBar
// xzy_tabIndex
// xzy_updateClearButton
// year
// zone
